# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-10 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_auto_20190928_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder3PL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('keyword', models.CharField(max_length=100, unique=True, verbose_name='事务关键字')),
                ('information', models.TextField(max_length=600, verbose_name='初始问题信息')),
                ('submit_time', models.DateTimeField(blank=True, null=True, verbose_name='客服提交时间')),
                ('servicer', models.CharField(blank=True, max_length=60, null=True, verbose_name='客服')),
                ('services_interval', models.IntegerField(blank=True, null=True, verbose_name='客服处理间隔(分钟)')),
                ('handler', models.CharField(blank=True, max_length=30, null=True, verbose_name='供应处理人')),
                ('handle_time', models.DateTimeField(blank=True, null=True, verbose_name='供应处理时间')),
                ('express_interval', models.IntegerField(blank=True, null=True, verbose_name='供应处理间隔(分钟)')),
                ('feedback', models.TextField(blank=True, max_length=900, null=True, verbose_name='反馈内容')),
                ('is_losing', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否丢件')),
                ('return_express_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='返回单号')),
                ('is_return', models.IntegerField(choices=[(0, '否'), (1, '是')], default=1, verbose_name='是否返回')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('order_status', models.SmallIntegerField(choices=[(0, '已被取消'), (1, '逆向未递'), (2, '逆向未理'), (3, '正向未递'), (4, '仓储未理'), (5, '复核未理'), (6, '工单完结')], default=1, verbose_name='工单状态')),
                ('category', models.SmallIntegerField(choices=[(0, '入库错误'), (1, '系统问题'), (2, '单据问题'), (3, '订单类别'), (4, '入库咨询'), (5, '出库咨询')], default=0, verbose_name='工单事项类型')),
                ('wo_category', models.SmallIntegerField(choices=[(0, '正向工单'), (1, '逆向工单')], default=0, verbose_name='工单类型')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.LogisticsInfo', verbose_name='供应商')),
            ],
            options={
                'verbose_name': 'EXT-工单-查询',
                'verbose_name_plural': 'EXT-工单-查询',
                'db_table': 'ext_workorder3pl',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder3PLApp',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-工单-正向建单',
                'verbose_name_plural': 'EXT-工单-正向建单',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorder3pl.workorder3pl',),
        ),
        migrations.CreateModel(
            name='WorkOrder3PLAppRev',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-工单-逆向建单',
                'verbose_name_plural': 'EXT-工单-逆向建单',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorder3pl.workorder3pl',),
        ),
        migrations.CreateModel(
            name='WorkOrder3PLHandle',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-工单处理',
                'verbose_name_plural': 'EXT-工单处理',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorder3pl.workorder3pl',),
        ),
        migrations.CreateModel(
            name='WorkOrder3PLHandleSto',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-工单处理-供应商',
                'verbose_name_plural': 'EXT-工单处理-供应商',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorder3pl.workorder3pl',),
        ),
        migrations.CreateModel(
            name='WorkOrder3PLKeshen',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-工单复核',
                'verbose_name_plural': 'EXT-工单复核',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorder3pl.workorder3pl',),
        ),
        migrations.CreateModel(
            name='WorkOrder3PLMine',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-工单-只看自己',
                'verbose_name_plural': 'EXT-工单-只看自己',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorder3pl.workorder3pl',),
        ),
    ]
