# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-11 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder3pl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder3pl',
            name='is_losing',
            field=models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否涉及理赔'),
        ),
        migrations.AlterField(
            model_name='workorder3pl',
            name='is_return',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=1, verbose_name='是否反馈'),
        ),
        migrations.AlterField(
            model_name='workorder3pl',
            name='return_express_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='反馈内容'),
        ),
    ]
