# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-14 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder3pl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder3plmine',
            options={'verbose_name': 'EXT-仓储工单-财务审核', 'verbose_name_plural': 'EXT-仓储工单-财务审核'},
        ),
        migrations.AlterField(
            model_name='workorder3pl',
            name='order_status',
            field=models.SmallIntegerField(choices=[(0, '已被取消'), (1, '逆向未递'), (2, '逆向未理'), (3, '正向未递'), (4, '仓储未理'), (5, '复核未理'), (6, '财务审核'), (7, '工单完结')], default=1, verbose_name='工单状态'),
        ),
    ]
