# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-11 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder3pl', '0002_auto_20191011_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder3pl',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.WareInfo', verbose_name='供应商'),
        ),
    ]
