# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-21 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder3pl', '0002_auto_20200114_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder3PLProcess',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-仓储工单-未完结',
                'verbose_name_plural': 'EXT-仓储工单-未完结',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorder3pl.workorder3pl',),
        ),
    ]
