# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-24 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder3pl', '0003_auto_20191011_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder3pl',
            options={'verbose_name': 'EXT-仓储工单-查询', 'verbose_name_plural': 'EXT-仓储工单-查询'},
        ),
        migrations.AlterModelOptions(
            name='workorder3plapp',
            options={'verbose_name': 'EXT-仓储工单-正向', 'verbose_name_plural': 'EXT-仓储工单-正向'},
        ),
        migrations.AlterModelOptions(
            name='workorder3plapprev',
            options={'verbose_name': 'EXT-仓储工单-逆向', 'verbose_name_plural': 'EXT-仓储工单-逆向'},
        ),
        migrations.AlterModelOptions(
            name='workorder3plhandle',
            options={'verbose_name': 'EXT-仓储工单处理', 'verbose_name_plural': 'EXT-仓储工单处理'},
        ),
        migrations.AlterModelOptions(
            name='workorder3plhandlesto',
            options={'verbose_name': 'EXT-仓储工单处理-供应商', 'verbose_name_plural': 'EXT-仓储工单处理-供应商'},
        ),
        migrations.AlterModelOptions(
            name='workorder3plkeshen',
            options={'verbose_name': 'EXT-仓储工单复核', 'verbose_name_plural': 'EXT-仓储工单复核'},
        ),
        migrations.AlterModelOptions(
            name='workorder3plmine',
            options={'verbose_name': 'EXT-仓储工单-只看自己', 'verbose_name_plural': 'EXT-仓储工单-只看自己'},
        ),
        migrations.AlterField(
            model_name='workorder3pl',
            name='feedback',
            field=models.TextField(blank=True, max_length=900, null=True, verbose_name='逆向反馈内容'),
        ),
        migrations.AlterField(
            model_name='workorder3pl',
            name='return_express_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='正向反馈内容'),
        ),
    ]
