# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-27 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriorderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('order_id', models.CharField(max_length=30, verbose_name='订单编号')),
                ('nickname', models.CharField(max_length=60, verbose_name='买家会员名')),
                ('payment_amount', models.FloatField(verbose_name='买家实际支付金额')),
                ('buyer_message', models.TextField(verbose_name='买家留言')),
                ('order_create_time', models.DateTimeField(verbose_name='订单创建时间')),
                ('payment_time', models.DateTimeField(verbose_name='订单付款时间')),
                ('goods_title', models.CharField(max_length=150, verbose_name='宝贝标题')),
                ('memorandum', models.TextField(verbose_name='订单备注')),
                ('goods_quantity', models.IntegerField(verbose_name='宝贝总数量')),
                ('shop_name', models.CharField(max_length=30, verbose_name='店铺名称')),
                ('order_status', models.IntegerField(choices=[(0, '订单取消'), (1, '等待处理'), (2, '处理完成'), (3, '特殊订单')], default=0, verbose_name='单据处理状态')),
                ('status_tag', models.SmallIntegerField(choices=[(0, '未标记'), (1, '订金订单'), (2, '时效外'), (3, '时效内'), (4, '暂不发货'), (5, '有退款')], default=0, verbose_name='订单标记')),
            ],
            options={
                'verbose_name': 'ASS-后台-订单查询表',
                'verbose_name_plural': 'ASS-后台-订单查询表',
                'db_table': 'ass_und_undelivered',
            },
        ),
        migrations.CreateModel(
            name='PendingOrderInfo',
            fields=[
            ],
            options={
                'verbose_name': 'ASS-后台-待处理订单',
                'verbose_name_plural': 'ASS-后台-待处理订单',
                'proxy': True,
                'indexes': [],
            },
            bases=('undelivered.oriorderinfo',),
        ),
        migrations.CreateModel(
            name='RefundOrderInfo',
            fields=[
            ],
            options={
                'verbose_name': 'ASS-后台-特殊订单',
                'verbose_name_plural': 'ASS-后台-特殊订单',
                'proxy': True,
                'indexes': [],
            },
            bases=('undelivered.oriorderinfo',),
        ),
    ]
