# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-02 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undelivered', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oriorderinfo',
            name='status',
            field=models.IntegerField(choices=[(0, '未处理'), (1, '订金'), (2, '异常'), (3, '先不发货'), (4, '延保'), (5, '未超时'), (6, '已完成')], default=0, verbose_name='单据处理状态'),
        ),
    ]
