# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-24 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('undelivered', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oriorderinfo',
            options={'verbose_name': '订单查询表', 'verbose_name_plural': '订单查询表'},
        ),
    ]
