# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-04 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undelivered', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oriorderinfo',
            name='status_tag',
            field=models.SmallIntegerField(choices=[(0, '未标记'), (1, '订金订单'), (2, '时效外'), (3, '时效内'), (4, '暂不发货'), (5, '有退款')], default=0, verbose_name='订单标记'),
        ),
    ]
