# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-11 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undelivered', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oriorderinfo',
            name='order_status',
            field=models.CharField(max_length=70, verbose_name='订单状态'),
        ),
    ]
