# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-03 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('undelivered', '0002_auto_20191204_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oriorderinfo',
            name='account_payable',
        ),
        migrations.RemoveField(
            model_name='oriorderinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='oriorderinfo',
            name='alipay_desc',
        ),
        migrations.RemoveField(
            model_name='oriorderinfo',
            name='alipay_id',
        ),
        migrations.RemoveField(
            model_name='oriorderinfo',
            name='alipay_order_id',
        ),
        migrations.RemoveField(
            model_name='oriorderinfo',
            name='cause_closed',
        ),
        migrations.RemoveField(
            model_name='oriorderinfo',
            name='delivery_type',
        ),
        migrations.RemoveField(
            model_name='oriorderinfo',
            name='goods_type',
        ),
        migrations.RemoveField(
            model_name='oriorderinfo',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='oriorderinfo',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='oriorderinfo',
            name='payment_point',
        ),
        migrations.RemoveField(
            model_name='oriorderinfo',
            name='point',
        ),
        migrations.RemoveField(
            model_name='oriorderinfo',
            name='point_payable',
        ),
        migrations.RemoveField(
            model_name='oriorderinfo',
            name='post_fee',
        ),
        migrations.RemoveField(
            model_name='oriorderinfo',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='oriorderinfo',
            name='refund_amount',
        ),
        migrations.RemoveField(
            model_name='oriorderinfo',
            name='shop_id',
        ),
        migrations.RemoveField(
            model_name='oriorderinfo',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='oriorderinfo',
            name='total_amount',
        ),
    ]
