# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-11 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undelivered', '0002_auto_20190611_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oriorderinfo',
            name='account_payable',
            field=models.FloatField(verbose_name='买家应付货款'),
        ),
        migrations.AlterField(
            model_name='oriorderinfo',
            name='payment_amount',
            field=models.FloatField(verbose_name='买家实际支付金额'),
        ),
        migrations.AlterField(
            model_name='oriorderinfo',
            name='post_fee',
            field=models.FloatField(verbose_name='买家应付邮费'),
        ),
        migrations.AlterField(
            model_name='oriorderinfo',
            name='refund_amount',
            field=models.FloatField(verbose_name='退款金额'),
        ),
        migrations.AlterField(
            model_name='oriorderinfo',
            name='total_amount',
            field=models.FloatField(verbose_name='总金额'),
        ),
    ]
