# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-11 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('undelivered', '0003_auto_20190611_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oriorderinfo',
            name='created_by',
        ),
    ]
