# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-03 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('undelivered', '0003_auto_20200103_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oriorderinfo',
            old_name='status',
            new_name='order_status',
        ),
    ]
