# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-06-10 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0002_auto_20200103_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='WOCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='类别名称')),
                ('order_status', models.SmallIntegerField(choices=[(0, '已取消'), (1, '正常')], default=1, verbose_name='工单状态')),
            ],
            options={
                'verbose_name': 'EXT-技术工单-工单类别',
                'verbose_name_plural': 'EXT-技术工单-工单类别',
                'db_table': 'ext_workordergu_category',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('express_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='源单号')),
                ('information', models.TextField(max_length=600, verbose_name='初始问题信息')),
                ('submit_time', models.DateTimeField(blank=True, null=True, verbose_name='技术提交时间')),
                ('servicer', models.CharField(blank=True, max_length=60, null=True, verbose_name='技术')),
                ('services_interval', models.IntegerField(blank=True, null=True, verbose_name='技术处理间隔(分钟)')),
                ('servicer_feedback', models.TextField(blank=True, null=True, verbose_name='技术反馈')),
                ('handler', models.CharField(blank=True, max_length=30, null=True, verbose_name='客服处理人')),
                ('handle_time', models.DateTimeField(blank=True, null=True, verbose_name='客服处理时间')),
                ('process_interval', models.IntegerField(blank=True, null=True, verbose_name='客服处理间隔(分钟)')),
                ('feedback', models.TextField(blank=True, max_length=900, null=True, verbose_name='反馈内容')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('order_status', models.SmallIntegerField(choices=[(0, '已被取消'), (1, '技术未递'), (2, '正向未递'), (3, '客服在理'), (4, '技术未理'), (5, '终审未理'), (6, '工单完结')], default=1, verbose_name='工单状态')),
                ('wo_category', models.SmallIntegerField(choices=[(0, '正向工单'), (1, '逆向工单')], default=0, verbose_name='工单类型')),
                ('process_tag', models.SmallIntegerField(choices=[(0, '未分类'), (1, '待截单'), (2, '签复核'), (3, '改地址'), (4, '催派查'), (5, '丢件核'), (6, '纠纷中'), (7, '其他')], default=0, verbose_name='处理标签')),
                ('mistake_tag', models.SmallIntegerField(choices=[(0, '正常'), (1, '无发票号'), (2, '快递单错误'), (3, '快递未发货'), (4, '驳回出错')], default=0, verbose_name='异常原因')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorderguarantee.WOCategory', verbose_name='工单事项类型')),
                ('goods_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g_goods_name', to='goods.MachineInfo', verbose_name='型号')),
            ],
            options={
                'verbose_name': 'EXT-技术工单-查询',
                'verbose_name_plural': 'EXT-技术工单-查询',
                'db_table': 'ext_workordergu_order',
            },
        ),
        migrations.CreateModel(
            name='WOFinish',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-技术工单-终审确认',
                'verbose_name_plural': 'EXT-技术工单-终审确认',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorderguarantee.workorder',),
        ),
        migrations.CreateModel(
            name='WOPCreate',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-技术工单-正向创建',
                'verbose_name_plural': 'EXT-技术工单-正向创建',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorderguarantee.workorder',),
        ),
        migrations.CreateModel(
            name='WORCheck',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-技术工单-技术审核',
                'verbose_name_plural': 'EXT-技术工单-技术审核',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorderguarantee.workorder',),
        ),
        migrations.CreateModel(
            name='WORCreate',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-技术工单-逆向创建',
                'verbose_name_plural': 'EXT-技术工单-逆向创建',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorderguarantee.workorder',),
        ),
        migrations.CreateModel(
            name='WOSCheck',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-技术工单-客服审核',
                'verbose_name_plural': 'EXT-技术工单-客服审核',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorderguarantee.workorder',),
        ),
    ]
