# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-27 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('order_id', models.CharField(max_length=100, unique=True, verbose_name='源订单单号')),
                ('information', models.TextField(max_length=600, verbose_name='初始问题信息')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='经销商反馈')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('amount', models.FloatField(verbose_name='合计金额')),
                ('wo_category', models.SmallIntegerField(choices=[(0, '退货'), (1, '换货'), (2, '维修')], default=0, verbose_name='工单类型')),
                ('is_customer_post', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否客户邮寄')),
                ('return_express_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='返回快递公司')),
                ('return_express_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='返回单号')),
                ('submit_time', models.DateTimeField(blank=True, null=True, verbose_name='客服提交时间')),
                ('servicer', models.CharField(blank=True, max_length=60, null=True, verbose_name='客服')),
                ('services_interval', models.IntegerField(blank=True, null=True, verbose_name='客服处理间隔(分钟)')),
                ('is_losing', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否丢件')),
                ('feedback', models.TextField(blank=True, max_length=900, null=True, verbose_name='客服处理意见')),
                ('handler', models.CharField(blank=True, max_length=30, null=True, verbose_name='经销商处理人')),
                ('handle_time', models.DateTimeField(blank=True, null=True, verbose_name='经销商处理时间')),
                ('express_interval', models.IntegerField(blank=True, null=True, verbose_name='经销商处理间隔(分钟)')),
                ('order_status', models.SmallIntegerField(choices=[(0, '已被取消'), (1, '经销未递'), (2, '客服在理'), (3, '经销复核'), (4, '运营对账'), (5, '工单完结')], default=1, verbose_name='工单状态')),
                ('process_tag', models.SmallIntegerField(choices=[(0, '未处理'), (1, '处理中'), (2, '已在途'), (3, '收异常'), (4, '未退回'), (5, '丢件核'), (6, '已处理'), (7, '终端清'), (8, '已对账')], default=0, verbose_name='处理标签')),
                ('mistake_tag', models.SmallIntegerField(choices=[(0, '正常'), (1, '返回单号为空'), (2, '处理意见为空'), (3, '经销商反馈为空'), (4, '先标记为已处理才能审核'), (5, '先标记为已对账才能审核'), (6, '工单必须为取消状态'), (7, '先标记为终端清才能审核')], default=0, verbose_name='错误原因')),
                ('platform', models.SmallIntegerField(choices=[(0, '无'), (1, '淘系'), (2, '非淘')], default=0, verbose_name='平台')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer', to='company.DealerInfo', verbose_name='经销商')),
                ('goods_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.MachineInfo', verbose_name='机器型号')),
            ],
            options={
                'verbose_name': 'EXT-经销商工单-查询',
                'verbose_name_plural': 'EXT-经销商工单-查询',
                'db_table': 'ext_workorderdealer',
            },
        ),
        migrations.CreateModel(
            name='WOCreate',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-经销商工单-创建',
                'verbose_name_plural': 'EXT-经销商工单-创建',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorderdealer.workorder',),
        ),
        migrations.CreateModel(
            name='WODealer',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-经销商工单-经销商',
                'verbose_name_plural': 'EXT-经销商工单-经销商',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorderdealer.workorder',),
        ),
        migrations.CreateModel(
            name='WOOperator',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-经销商工单-运营',
                'verbose_name_plural': 'EXT-经销商工单-运营',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorderdealer.workorder',),
        ),
        migrations.CreateModel(
            name='WOService',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-经销商工单-客服',
                'verbose_name_plural': 'EXT-经销商工单-客服',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorderdealer.workorder',),
        ),
        migrations.CreateModel(
            name='WOTrack',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-经销商工单-跟进',
                'verbose_name_plural': 'EXT-经销商工单-跟进',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorderdealer.workorder',),
        ),
    ]
