# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-02-10 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderdealer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='is_customer_post',
            field=models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否客户邮寄'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='return_express_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='返回快递公司'),
        ),
    ]
