# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-02-10 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorderdealer', '0002_auto_20200210_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer', to='company.DealerInfo', verbose_name='经销商'),
        ),
    ]
