# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-02-14 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderdealer', '0003_auto_20200210_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '返回单号为空'), (2, '处理意见为空'), (3, '正常'), (4, '正常'), (5, '正常'), (6, '正常'), (7, '正常'), (8, '正常')], default=0, verbose_name='错误原因'),
        ),
    ]
