# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-02-21 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderdealer', '0004_workorder_mistake_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '返回单号为空'), (2, '处理意见为空'), (3, '经销商反馈为空'), (4, '正常'), (5, '正常'), (6, '正常'), (7, '正常'), (8, '正常')], default=0, verbose_name='错误原因'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='process_tag',
            field=models.SmallIntegerField(choices=[(0, '未处理'), (1, '处理中'), (2, '已在途'), (3, '收异常'), (4, '未退回'), (5, '丢件核'), (6, '纠纷中'), (7, '已处理'), (8, '其他')], default=0, verbose_name='处理标签'),
        ),
    ]
