# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-02-21 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderdealer', '0006_auto_20200221_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='process_tag',
            field=models.SmallIntegerField(choices=[(0, '未处理'), (1, '处理中'), (2, '已在途'), (3, '收异常'), (4, '未退回'), (5, '丢件核'), (6, '纠纷中'), (7, '已处理'), (8, '已对账')], default=0, verbose_name='处理标签'),
        ),
    ]
