# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-02-21 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderdealer', '0009_auto_20200221_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='platform',
            field=models.SmallIntegerField(choices=[(0, '无'), (1, '淘系'), (2, '非淘')], default=0, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '返回单号为空'), (2, '处理意见为空'), (3, '经销商反馈为空'), (4, '先标记为已处理才能审核'), (5, '先标记为已对账才能审核'), (6, '工单必须为取消状态'), (7, '先标记为终端清才能审核')], default=0, verbose_name='错误原因'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='process_tag',
            field=models.SmallIntegerField(choices=[(0, '未处理'), (1, '处理中'), (2, '已在途'), (3, '收异常'), (4, '未退回'), (5, '丢件核'), (6, '已处理'), (7, '终端清'), (8, '已对账')], default=0, verbose_name='处理标签'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='wo_category',
            field=models.SmallIntegerField(choices=[(0, '退货'), (1, '换货'), (2, '维修')], default=0, verbose_name='工单类型'),
        ),
    ]
