# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-28 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufactory', '0001_initial'),
        ('goods', '0001_initial'),
        ('cusrequisition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CusPartOrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('planorder_id', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='计划采购单号')),
                ('quantity', models.IntegerField(verbose_name='采购数量')),
                ('estimated_time', models.DateTimeField(verbose_name='期望到货时间')),
                ('status', models.IntegerField(choices=[(0, '已取消'), (1, '未处理'), (2, '已确认'), (3, '异常'), (4, '已入库')], default=1, verbose_name='采购单状态')),
                ('category', models.IntegerField(choices=[(0, '常规'), (1, '加急'), (2, '大促')], default=0, verbose_name='采购单类别')),
                ('order_attribute', models.IntegerField(choices=[(0, '配件采购单'), (1, '客供件采购单')], default=0, verbose_name='采购单类别')),
                ('goods_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.PartInfo', verbose_name='配件名称')),
                ('manufactory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufactory.ManufactoryInfo', verbose_name='工厂名称')),
                ('source_order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cusrequisition.CusRequisitionInfo', verbose_name='来源单号')),
            ],
            options={
                'verbose_name': 'OMS-CP-非整机采购申请单',
                'verbose_name_plural': 'OMS-CP-非整机采购申请单',
                'db_table': 'oms_pp_purchaseorder',
            },
        ),
        migrations.CreateModel(
            name='CusPartPenddingOrderInfo',
            fields=[
            ],
            options={
                'verbose_name': 'OMS-CP-未审核非整机采购申请单',
                'verbose_name_plural': 'OMS-CP-未审核非整机采购申请单',
                'proxy': True,
                'indexes': [],
            },
            bases=('planorderofpart.cuspartorderinfo',),
        ),
        migrations.CreateModel(
            name='CusPartProductOrderInfo',
            fields=[
            ],
            options={
                'verbose_name': 'OMS-CP-在生产非整机采购申请单',
                'verbose_name_plural': 'OMS-CP-在生产非整机采购申请单',
                'proxy': True,
                'indexes': [],
            },
            bases=('planorderofpart.cuspartorderinfo',),
        ),
    ]
