# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-18 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planorderofpart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuspartorderinfo',
            name='status',
        ),
        migrations.AddField(
            model_name='cuspartorderinfo',
            name='order_status',
            field=models.IntegerField(choices=[(0, '已取消'), (1, '未处理'), (2, '已确认'), (3, '已入库'), (4, '异常')], default=1, verbose_name='采购单状态'),
        ),
        migrations.AlterField(
            model_name='cuspartorderinfo',
            name='manufactory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.ManuInfo', verbose_name='工厂名称'),
        ),
    ]
