# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-16 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refurbishment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefurbishGoodSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('statistical_time', models.DateTimeField(verbose_name='统计时间')),
                ('goods_name', models.CharField(max_length=60, verbose_name='机器名称')),
                ('goods_id', models.CharField(max_length=30, verbose_name='机器编码')),
                ('quantity', models.IntegerField(verbose_name='翻新数量')),
                ('submit_tag', models.IntegerField(choices=[(0, '未递交'), (1, '已处理'), (2, '已出库'), (3, '异常')], default=0, verbose_name='生成状态')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RefurbishTechSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('statistical_time', models.DateTimeField(verbose_name='统计时间')),
                ('technician', models.CharField(max_length=30, verbose_name='技术员')),
                ('quantity', models.IntegerField(verbose_name='翻新数量')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='RefurbishSummary',
        ),
    ]
