# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-18 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refurbishment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orirefurbishinfo',
            name='goods_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.GoodsInfo', verbose_name='机器名称'),
        ),
    ]
