# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-29 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refurbishment', '0002_auto_20190629_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orirefurbishinfo',
            name='created_by',
        ),
    ]
