# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-17 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refurbishment', '0002_auto_20190516_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateRefurbishTechSummary',
            fields=[
            ],
            options={
                'verbose_name': '私有技术员翻新统计列表',
                'verbose_name_plural': '私有技术员翻新统计列表',
                'proxy': True,
                'indexes': [],
            },
            bases=('refurbishment.orirefurbishinfo',),
        ),
        migrations.AlterModelOptions(
            name='refurbishgoodsummary',
            options={'verbose_name': '翻新机器统计列表', 'verbose_name_plural': '翻新机器统计列表'},
        ),
        migrations.AlterModelOptions(
            name='refurbishtechsummary',
            options={'verbose_name': '技术员翻新统计列表', 'verbose_name_plural': '技术员翻新统计列表'},
        ),
        migrations.AlterModelTable(
            name='refurbishgoodsummary',
            table='crm_ref_refurbishgoodsummary',
        ),
        migrations.AlterModelTable(
            name='refurbishtechsummary',
            table='crm_ref_refurbishtechsummary',
        ),
    ]
