# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-28 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('goods_id', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='货品编码')),
                ('goods_name', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='货品名称')),
                ('category', models.CharField(choices=[('VAC', '吸尘器'), ('DMC', '除螨仪'), ('VAR', '智能机器人'), ('OTH', '其他')], default='OTH', max_length=10, verbose_name='货品类别')),
                ('goods_attribute', models.IntegerField(choices=[(0, '整机'), (1, '配件'), (2, '礼品')], default=0, verbose_name='货品属性')),
                ('goods_number', models.CharField(max_length=10, unique=True, verbose_name='机器排序')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='规格')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='长')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='宽')),
                ('depth', models.IntegerField(blank=True, null=True, verbose_name='高')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='重量')),
            ],
            options={
                'verbose_name': 'BASE-货品信息表',
                'verbose_name_plural': 'BASE-货品信息表',
                'db_table': 'base_goodsinfo',
            },
        ),
        migrations.CreateModel(
            name='MachineInfo',
            fields=[
            ],
            options={
                'verbose_name': 'BASE-机器信息表',
                'verbose_name_plural': 'BASE-机器信息表',
                'proxy': True,
                'indexes': [],
            },
            bases=('goods.goodsinfo',),
        ),
        migrations.CreateModel(
            name='PartInfo',
            fields=[
            ],
            options={
                'verbose_name': 'BASE-配件信息表',
                'verbose_name_plural': 'BASE-配件信息表',
                'proxy': True,
                'indexes': [],
            },
            bases=('goods.goodsinfo',),
        ),
    ]
