# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-03 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='category',
            field=models.CharField(choices=[('VAC', '吸尘器'), ('DMC', '除螨仪'), ('VAR', '智能机器人'), ('HUM', '加湿器'), ('MOP', '拖把'), ('ETB', '电动牙刷'), ('KIT', '烤箱'), ('OTH', '其他')], default='OTH', max_length=10, verbose_name='货品类别'),
        ),
    ]
