# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-18 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='catalog_num',
            field=models.CharField(blank=True, max_length=230, null=True, verbose_name='爆炸图号'),
        ),
    ]
