# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-24 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManuOrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('batch_num', models.CharField(max_length=30, unique=True, verbose_name='批次号')),
                ('planorder_id', models.CharField(max_length=30, unique=True, verbose_name='计划采购单号')),
                ('goods_id', models.CharField(max_length=30, verbose_name='货品编码')),
                ('goods_name', models.CharField(max_length=60, verbose_name='货品名称')),
                ('quantity', models.IntegerField(verbose_name='货品数量')),
                ('status', models.IntegerField(choices=[(0, '未处理'), (1, '已确认'), (2, '在生产'), (2, '已完成'), (3, '取消')], default=0, verbose_name='生产单状态')),
                ('manufactory', models.CharField(max_length=30, verbose_name='工厂名称')),
                ('completed_num', models.IntegerField(verbose_name='已完成量')),
                ('estimated_time', models.DateTimeField(verbose_name='期望到货时间')),
            ],
            options={
                'verbose_name': '工厂生产列表',
                'verbose_name_plural': '工厂生产列表',
                'db_table': 'oms_mfo_manuorder',
            },
        ),
    ]
