# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-29 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufactory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManuOrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('batch_num', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='批次号')),
                ('planorder_id', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='计划采购单号')),
                ('goods_id', models.CharField(max_length=30, verbose_name='货品编码')),
                ('goods_name', models.CharField(max_length=60, verbose_name='货品名称')),
                ('quantity', models.IntegerField(verbose_name='货品数量')),
                ('status', models.IntegerField(choices=[(0, '取消'), (1, '待处理'), (2, '异常'), (3, '待生产'), (4, '在生产'), (5, '已完成')], default=1, verbose_name='生产单状态')),
                ('estimated_time', models.DateTimeField(verbose_name='期望到货时间')),
                ('start_sn', models.CharField(max_length=30, null=True, verbose_name='首号')),
                ('end_sn', models.CharField(max_length=30, null=True, verbose_name='尾号')),
                ('manufactory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.ManufactoryInfo', verbose_name='工厂名称')),
            ],
            options={
                'verbose_name': 'OMS-M-工厂生产列表',
                'verbose_name_plural': 'OMS-M-工厂生产列表',
                'db_table': 'oms_mfo_manuorder',
            },
        ),
        migrations.CreateModel(
            name='ManuOrderPenddingInfo',
            fields=[
            ],
            options={
                'verbose_name': 'OMS-M-待客供生产列表',
                'verbose_name_plural': 'OMS-M-待客供生产列表',
                'proxy': True,
                'indexes': [],
            },
            bases=('manuorder.manuorderinfo',),
        ),
        migrations.CreateModel(
            name='ManuOrderProcessingInfo',
            fields=[
            ],
            options={
                'verbose_name': 'OMS-M-待生产列表',
                'verbose_name_plural': 'OMS-M-待生产列表',
                'proxy': True,
                'indexes': [],
            },
            bases=('manuorder.manuorderinfo',),
        ),
    ]
