# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-30 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuorderinfo',
            name='tag_sign',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '超期跟进'), (2, '主动延期'), (3, '等待核实'), (4, '紧急叫停'), (5, '特殊情况'), (6, '其他')], default=0, verbose_name='标记'),
        ),
    ]
