# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-24 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManuOrderPenddingInfo',
            fields=[
            ],
            options={
                'verbose_name': '待客供生产列表',
                'verbose_name_plural': '待客供生产列表',
                'proxy': True,
                'indexes': [],
            },
            bases=('manuorder.manuorderinfo',),
        ),
        migrations.CreateModel(
            name='ManuOrderProcessingInfo',
            fields=[
            ],
            options={
                'verbose_name': '待生产列表',
                'verbose_name_plural': '待生产列表',
                'proxy': True,
                'indexes': [],
            },
            bases=('manuorder.manuorderinfo',),
        ),
        migrations.AlterField(
            model_name='manuorderinfo',
            name='status',
            field=models.IntegerField(choices=[(0, '待客供'), (1, '已确认'), (2, '在生产'), (3, '已完成'), (4, '取消')], default=0, verbose_name='生产单状态'),
        ),
    ]
