# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-18 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuorder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuorderinfo',
            name='status',
        ),
        migrations.AddField(
            model_name='manuorderinfo',
            name='order_status',
            field=models.IntegerField(choices=[(0, '取消'), (1, '待处理'), (2, '待生产'), (3, '在生产'), (4, '已完成')], default=1, verbose_name='生产单状态'),
        ),
        migrations.AlterField(
            model_name='manuorderinfo',
            name='manufactory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.ManuInfo', verbose_name='工厂名称'),
        ),
    ]
