# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-30 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuorder', '0002_auto_20191018_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuorderinfo',
            name='planorder_id',
            field=models.CharField(db_index=True, max_length=30, verbose_name='计划采购单号'),
        ),
    ]
