# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-24 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuorder', '0002_auto_20190624_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuorderinfo',
            name='completed_num',
        ),
    ]
