# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-25 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuorder', '0003_remove_manuorderinfo_completed_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuorderinfo',
            name='end_sn',
            field=models.CharField(max_length=30, null=True, verbose_name='尾号'),
        ),
        migrations.AddField(
            model_name='manuorderinfo',
            name='start_sn',
            field=models.CharField(max_length=30, null=True, verbose_name='首号'),
        ),
        migrations.AlterField(
            model_name='manuorderinfo',
            name='batch_num',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='批次号'),
        ),
        migrations.AlterField(
            model_name='manuorderinfo',
            name='planorder_id',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='计划采购单号'),
        ),
    ]
