# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-26 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuorder', '0004_auto_20190625_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuorderinfo',
            name='manufactory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.ManufactoryInfo', verbose_name='工厂名称'),
        ),
    ]
