# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-28 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('express_id', models.CharField(max_length=100, unique=True, verbose_name='源单号')),
                ('information', models.TextField(max_length=600, verbose_name='初始问题信息')),
                ('submit_time', models.DateTimeField(blank=True, null=True, verbose_name='客服提交时间')),
                ('servicer', models.CharField(blank=True, max_length=60, null=True, verbose_name='客服')),
                ('services_interval', models.IntegerField(blank=True, null=True, verbose_name='客服处理间隔(分钟)')),
                ('handler', models.CharField(blank=True, max_length=30, null=True, verbose_name='快递处理人')),
                ('handle_time', models.DateTimeField(blank=True, null=True, verbose_name='快递处理时间')),
                ('express_interval', models.IntegerField(blank=True, null=True, verbose_name='快递处理间隔(分钟)')),
                ('feedback', models.TextField(blank=True, max_length=900, null=True, verbose_name='反馈内容')),
                ('is_losing', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否丢件')),
                ('return_express_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='返回单号')),
                ('is_return', models.IntegerField(choices=[(0, '否'), (1, '是')], default=1, verbose_name='是否返回')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('order_status', models.SmallIntegerField(choices=[(0, '已被取消'), (1, '快递未递'), (2, '逆向未理'), (3, '正向未递'), (4, '快递未理'), (5, '复核未理'), (6, '工单完结')], default=1, verbose_name='工单状态')),
                ('category', models.SmallIntegerField(choices=[(0, '截单退回'), (1, '无人收货'), (2, '客户拒签'), (3, '修改地址'), (4, '催件派送'), (5, '虚假签收'), (6, '其他异常')], default=0, verbose_name='工单事项类型')),
                ('wo_category', models.SmallIntegerField(choices=[(0, '正向工单'), (1, '逆向工单')], default=0, verbose_name='工单类型')),
                ('company', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='company.CompanyInfo', verbose_name='快递公司')),
            ],
            options={
                'verbose_name': 'EXT-工单-查询',
                'verbose_name_plural': 'EXT-工单-查询',
                'db_table': 'ext_workorder',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderApp',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-工单-正向建单',
                'verbose_name_plural': 'EXT-工单-正向建单',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorder.workorder',),
        ),
        migrations.CreateModel(
            name='WorkOrderAppRev',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-工单-逆向建单',
                'verbose_name_plural': 'EXT-工单-逆向建单',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorder.workorder',),
        ),
        migrations.CreateModel(
            name='WorkOrderHandle',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-工单处理-客服',
                'verbose_name_plural': 'EXT-工单处理-客服',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorder.workorder',),
        ),
        migrations.CreateModel(
            name='WorkOrderHandleSto',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-工单处理-申通',
                'verbose_name_plural': 'EXT-工单处理-申通',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorder.workorder',),
        ),
        migrations.CreateModel(
            name='WorkOrderKeshen',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-工单复核-客审',
                'verbose_name_plural': 'EXT-工单复核-客审',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorder.workorder',),
        ),
        migrations.CreateModel(
            name='WorkOrderMine',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-工单-只看自己',
                'verbose_name_plural': 'EXT-工单-只看自己',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorder.workorder',),
        ),
    ]
