# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-20 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchFaultSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('statistic_time', models.DateTimeField(verbose_name='统计时间')),
                ('batch_number', models.CharField(max_length=50, verbose_name='批次号')),
                ('cumulation', models.IntegerField(verbose_name='生产数量累计')),
            ],
            options={
                'verbose_name': '批次故障数量统计表',
                'verbose_name_plural': '批次故障数量统计表',
                'db_table': 'oms_m_batchfaultsummary',
            },
        ),
        migrations.CreateModel(
            name='BatchSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('statistic_time', models.DateTimeField(verbose_name='统计时间')),
                ('batch_number', models.CharField(max_length=50, verbose_name='批次号')),
                ('cumulation', models.IntegerField(verbose_name='生产数量累计')),
            ],
            options={
                'verbose_name': '批次汇总表',
                'verbose_name_plural': '批次汇总表',
                'db_table': 'oms_m_batchsummary',
            },
        ),
        migrations.CreateModel(
            name='FactoryFaultSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('statistic_time', models.DateTimeField(verbose_name='统计时间')),
                ('manufactory', models.CharField(max_length=50, verbose_name='工厂')),
                ('cumulation', models.IntegerField(verbose_name='生产数量累计')),
            ],
            options={
                'verbose_name': '工厂故障数量汇总表',
                'verbose_name_plural': '工厂故障数量汇总表',
                'db_table': 'oms_m_factoryfaultsummary',
            },
        ),
        migrations.CreateModel(
            name='FactorySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('statistic_time', models.DateTimeField(verbose_name='统计时间')),
                ('manufactory', models.CharField(max_length=50, verbose_name='工厂')),
                ('cumulation', models.IntegerField(verbose_name='生产数量累计')),
            ],
            options={
                'verbose_name': '工厂汇总表',
                'verbose_name_plural': '工厂汇总表',
                'db_table': 'oms_m_factorysummary',
            },
        ),
        migrations.CreateModel(
            name='GoodFaultSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('statistic_time', models.DateTimeField(verbose_name='统计时间')),
                ('goods_id', models.CharField(max_length=30, verbose_name='型号')),
                ('cumulation', models.IntegerField(verbose_name='生产数量累计')),
            ],
            options={
                'verbose_name': '机器故障数量汇总表',
                'verbose_name_plural': '机器故障数量汇总表',
                'db_table': 'oms_m_goodfaultsummary',
            },
        ),
        migrations.CreateModel(
            name='GoodSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('statistic_time', models.DateTimeField(verbose_name='统计时间')),
                ('goods_id', models.CharField(max_length=30, verbose_name='型号')),
                ('cumulation', models.IntegerField(verbose_name='生产数量累计')),
            ],
            options={
                'verbose_name': '机器汇总表',
                'verbose_name_plural': '机器汇总表',
                'db_table': 'oms_m_goodsummary',
            },
        ),
        migrations.CreateModel(
            name='MachineOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('mfd', models.DateTimeField(verbose_name='要求交期')),
                ('goods_id', models.CharField(max_length=30, verbose_name='型号')),
                ('manufactory', models.CharField(max_length=50, verbose_name='工厂')),
                ('order_id', models.CharField(max_length=50, verbose_name='生产单号')),
                ('quantity', models.IntegerField(verbose_name='生产数量')),
                ('msn', models.CharField(max_length=150, verbose_name='序列号段')),
            ],
            options={
                'verbose_name': '生产订单列表',
                'verbose_name_plural': '生产订单列表',
                'db_table': 'oms_m_machineorder',
            },
        ),
        migrations.CreateModel(
            name='MachineSN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('mfd', models.DateTimeField(verbose_name='要求交期')),
                ('m_sn', models.CharField(max_length=50, verbose_name='机器序列号')),
                ('batch_number', models.CharField(max_length=50, verbose_name='批次号')),
                ('manufactory', models.CharField(max_length=50, verbose_name='工厂')),
                ('goods_id', models.CharField(max_length=30, verbose_name='型号')),
                ('m_q', models.IntegerField(default=0, verbose_name='维修次数')),
            ],
            options={
                'verbose_name': '机器序列号列表',
                'verbose_name_plural': '机器序列号列表',
                'db_table': 'oms_m_machinsn',
            },
        ),
    ]
