# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-06 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchFaultSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('statistic_time', models.DateTimeField(verbose_name='统计时间')),
                ('batch_number', models.CharField(max_length=50, verbose_name='批次号')),
                ('fault_cumulation', models.IntegerField(verbose_name='故障数量累计')),
                ('cumulation', models.IntegerField(verbose_name='生产数量累计')),
            ],
            options={
                'verbose_name': '批次故障数量统计表',
                'verbose_name_plural': '批次故障数量统计表',
                'db_table': 'oms_m_batchfaultsummary',
            },
        ),
        migrations.CreateModel(
            name='FactoryFaultSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('statistic_time', models.DateTimeField(verbose_name='统计时间')),
                ('manufactory', models.CharField(max_length=50, verbose_name='工厂')),
                ('cumulation', models.IntegerField(verbose_name='生产数量累计')),
            ],
            options={
                'verbose_name': '工厂故障数量汇总表',
                'verbose_name_plural': '工厂故障数量汇总表',
                'db_table': 'oms_m_factoryfaultsummary',
            },
        ),
        migrations.CreateModel(
            name='FaultMachineSN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('mfd', models.DateTimeField(verbose_name='生产日期')),
                ('finish_time', models.DateTimeField(verbose_name='保修完成时间')),
                ('m_sn', models.CharField(max_length=50, verbose_name='机器序列号')),
                ('batch_number', models.CharField(max_length=50, verbose_name='批次号')),
                ('manufactory', models.CharField(max_length=50, verbose_name='工厂')),
                ('goods_id', models.CharField(max_length=30, verbose_name='型号')),
                ('appraisal', models.CharField(max_length=200, verbose_name='保修结束语')),
            ],
            options={
                'verbose_name': '维修序列号列表',
                'verbose_name_plural': '维修序列号列表',
                'db_table': 'oms_m_faultmachinesn',
            },
        ),
        migrations.CreateModel(
            name='GoodFaultSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('statistic_time', models.DateTimeField(verbose_name='统计时间')),
                ('production_quantity', models.IntegerField(default=0, verbose_name='生产数量')),
                ('production_cumulation', models.IntegerField(default=0, verbose_name='生产累计数量')),
                ('fault_quantity', models.IntegerField(default=0, verbose_name='故障数量')),
                ('fault_cumulation', models.IntegerField(default=0, verbose_name='故障累计数量')),
                ('goods_id', models.CharField(max_length=30, verbose_name='型号')),
            ],
            options={
                'verbose_name': '机器故障数量汇总表',
                'verbose_name_plural': '机器故障数量汇总表',
                'db_table': 'oms_m_goodfaultsummary',
            },
        ),
        migrations.CreateModel(
            name='MachineInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('machine_id', models.CharField(max_length=30, unique=True, verbose_name='商家编码')),
                ('machine_name', models.CharField(max_length=60, unique=True, verbose_name='名称')),
                ('machine_type', models.CharField(choices=[('VAC', '吸尘器'), ('DMC', '除螨仪'), ('VAR', '智能机器人')], max_length=30, verbose_name='机器类型')),
                ('machine_number', models.CharField(max_length=10, unique=True, verbose_name='机器排序')),
                ('sales_distriction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geography.NationalityInfo', verbose_name='销售区域')),
            ],
            options={
                'verbose_name': '机器信息表',
                'verbose_name_plural': '机器信息表',
                'db_table': 'oms_m_manchineinfo',
            },
        ),
        migrations.CreateModel(
            name='MachineOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('identification', models.IntegerField(unique=True, verbose_name='订单序号')),
                ('mfd', models.DateTimeField(verbose_name='要求交期')),
                ('goods_id', models.CharField(max_length=30, verbose_name='型号')),
                ('manufactory', models.CharField(max_length=50, verbose_name='工厂')),
                ('order_id', models.CharField(max_length=50, verbose_name='生产单号')),
                ('quantity', models.IntegerField(verbose_name='生产数量')),
                ('msn_segment', models.CharField(max_length=150, verbose_name='序列号段')),
                ('tosn_status', models.SmallIntegerField(choices=[(0, '未递交'), (1, '已处理'), (2, '无效'), (3, '异常')], default=0, verbose_name='sn列表生成状态')),
            ],
            options={
                'verbose_name': '生产订单列表',
                'verbose_name_plural': '生产订单列表',
                'db_table': 'oms_m_machineorder',
            },
        ),
        migrations.CreateModel(
            name='MachineSN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('mfd', models.DateTimeField(verbose_name='要求交期')),
                ('m_sn', models.CharField(max_length=50, verbose_name='机器序列号')),
                ('batch_number', models.CharField(max_length=50, verbose_name='批次号')),
                ('manufactory', models.CharField(max_length=50, verbose_name='工厂')),
                ('goods_id', models.CharField(max_length=30, verbose_name='型号')),
            ],
            options={
                'verbose_name': '机器序列号列表',
                'verbose_name_plural': '机器序列号列表',
                'db_table': 'oms_m_machinsn',
            },
        ),
        migrations.CreateModel(
            name='PartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('part_id', models.CharField(max_length=30, unique=True, verbose_name='配件编码')),
                ('part_name', models.CharField(max_length=60, unique=True, verbose_name='配件名称')),
                ('category', models.IntegerField(choices=[(0, '客供配件'), (1, '常规配件'), (2, '礼品'), (3, '其他')], default=0, verbose_name='配件类别')),
                ('size', models.CharField(blank=True, max_length=15, null=True, verbose_name='规格')),
            ],
            options={
                'verbose_name': '配件信息表',
                'verbose_name_plural': '配件信息表',
                'db_table': 'oms_m_partinfo',
            },
        ),
        migrations.AlterIndexTogether(
            name='machineinfo',
            index_together=set([('machine_name', 'machine_id')]),
        ),
    ]
