# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-07 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodfaultsummary',
            name='cumulation',
        ),
        migrations.AddField(
            model_name='goodfaultsummary',
            name='fault_cumulation',
            field=models.IntegerField(default=0, verbose_name='故障累计数量'),
        ),
        migrations.AddField(
            model_name='goodfaultsummary',
            name='fault_quantity',
            field=models.IntegerField(default=0, verbose_name='故障数量'),
        ),
        migrations.AddField(
            model_name='goodfaultsummary',
            name='production_cumulation',
            field=models.IntegerField(default=0, verbose_name='生产累计数量'),
        ),
        migrations.AddField(
            model_name='goodfaultsummary',
            name='production_quantity',
            field=models.IntegerField(default=0, verbose_name='生产数量'),
        ),
    ]
