# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-20 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineorder',
            name='tosn_status',
            field=models.SmallIntegerField(choices=[(0, '未递交'), (1, '已处理'), (2, '无效'), (3, '异常')], default=0, verbose_name='sn列表生成状态'),
        ),
        migrations.AddField(
            model_name='machineorder',
            name='tosum_status',
            field=models.SmallIntegerField(choices=[(0, '未递交'), (1, '已处理'), (2, '无效'), (3, '异常')], default=0, verbose_name='汇总列表生成状态'),
        ),
    ]
