# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-22 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_auto_20190420_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultMachineSN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('finish_time', models.DateTimeField(verbose_name='保修完成时间')),
                ('m_sn', models.CharField(max_length=50, verbose_name='机器序列号')),
                ('batch_number', models.CharField(max_length=50, verbose_name='批次号')),
                ('manufactory', models.CharField(max_length=50, verbose_name='工厂')),
                ('goods_id', models.CharField(max_length=30, verbose_name='型号')),
            ],
            options={
                'verbose_name': '维修序列号列表',
                'verbose_name_plural': '维修序列号列表',
                'db_table': 'oms_m_faultmachinesn',
            },
        ),
        migrations.RemoveField(
            model_name='machinesn',
            name='m_q',
        ),
    ]
