# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-18 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_auto_20190618_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartInfo',
            fields=[
            ],
            options={
                'verbose_name': '配件信息表',
                'verbose_name_plural': '配件信息表',
                'proxy': True,
                'indexes': [],
            },
            bases=('machine.goodsinfo',),
        ),
        migrations.RenameField(
            model_name='goodsinfo',
            old_name='machine_number',
            new_name='good_number',
        ),
    ]
