# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-11 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_auto_20190507_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('machine_id', models.CharField(max_length=30, verbose_name='商家编码')),
                ('machine_name', models.CharField(max_length=60, verbose_name='名称')),
                ('machine_type', models.CharField(choices=[('VAC', '吸尘器'), ('DMC', '除螨仪'), ('VAR', '智能机器人')], max_length=30, verbose_name='机器类型')),
                ('machine_number', models.CharField(max_length=10, unique=True, verbose_name='机器排序')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FactorySummary',
        ),
        migrations.DeleteModel(
            name='GoodSummary',
        ),
    ]
