# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-13 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_auto_20190511_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machineinfo',
            options={'verbose_name': '机器信息表', 'verbose_name_plural': '机器信息表'},
        ),
        migrations.AlterModelTable(
            name='machineinfo',
            table='oms_m_manchineinfo',
        ),
    ]
