# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-19 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_auto_20190618_2108'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='machineinfo',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='machineinfo',
            name='sales_distriction',
        ),
        migrations.RenameField(
            model_name='goodsinfo',
            old_name='good_attribute',
            new_name='goods_attribute',
        ),
        migrations.RenameField(
            model_name='goodsinfo',
            old_name='good_id',
            new_name='goods_id',
        ),
        migrations.RenameField(
            model_name='goodsinfo',
            old_name='good_name',
            new_name='goods_name',
        ),
        migrations.RenameField(
            model_name='goodsinfo',
            old_name='good_number',
            new_name='goods_number',
        ),
        migrations.DeleteModel(
            name='MachineInfo',
        ),
        migrations.CreateModel(
            name='MachineInfo',
            fields=[
            ],
            options={
                'verbose_name': '机器信息表',
                'verbose_name_plural': '机器信息表',
                'proxy': True,
                'indexes': [],
            },
            bases=('machine.goodsinfo',),
        ),
    ]
