# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-13 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_auto_20190513_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineinfo',
            name='machine_id',
            field=models.CharField(max_length=30, unique=True, verbose_name='商家编码'),
        ),
    ]
