# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-22 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_auto_20190422_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineorder',
            name='identification',
            field=models.IntegerField(default=0, verbose_name='订单序号'),
        ),
    ]
