# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-24 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0005_machineorder_identification'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='machinesn',
            index_together=set([('m_sn',)]),
        ),
    ]
