# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-24 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0006_auto_20190424_2044'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='machinesn',
            index_together=set([('mfd', 'm_sn', 'batch_number', 'manufactory', 'goods_id')]),
        ),
    ]
