# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-24 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0007_auto_20190424_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinesn',
            name='m_sn',
            field=models.CharField(max_length=50, unique=True, verbose_name='机器序列号'),
        ),
    ]
