# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-25 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0008_auto_20190424_2049'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='machinesn',
            index_together=set([('m_sn',)]),
        ),
    ]
