# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-29 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('mobile', models.CharField(max_length=30, verbose_name='手机')),
                ('satisficing', models.IntegerField(default=100, verbose_name='客户满意指数')),
                ('category', models.CharField(blank=True, max_length=30, null=True, verbose_name='客户类别')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, max_length=30, null=True, verbose_name='性别')),
                ('nationality', models.CharField(blank=True, max_length=30, null=True, verbose_name='国家')),
                ('province', models.CharField(max_length=30, verbose_name='省份')),
                ('city', models.CharField(max_length=30, verbose_name='城市')),
                ('district', models.CharField(blank=True, max_length=30, null=True, verbose_name='区县')),
                ('address', models.CharField(max_length=300, verbose_name='地址')),
                ('e_mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='电子邮件')),
                ('qq', models.CharField(blank=True, max_length=30, null=True, verbose_name='QQ')),
                ('wangwang', models.CharField(blank=True, max_length=60, null=True, verbose_name='旺旺')),
                ('jdfbp_id', models.CharField(blank=True, max_length=60, null=True, verbose_name='京东FBP账号')),
                ('jdzy_id', models.CharField(blank=True, max_length=60, null=True, verbose_name='京东自营账号')),
                ('gfsc_id', models.CharField(blank=True, max_length=60, null=True, verbose_name='官方商城账号')),
                ('wxxcx_id', models.CharField(blank=True, max_length=60, null=True, verbose_name='微信小程序账号')),
                ('alipay_id', models.CharField(blank=True, max_length=60, null=True, verbose_name='支付宝账号')),
                ('pdd_id', models.CharField(blank=True, max_length=60, null=True, verbose_name='拼多多账号')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='生日')),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='购买总金额')),
                ('total_times', models.IntegerField(default=0, verbose_name='购买总次数')),
                ('last_time', models.DateTimeField(blank=True, null=True, verbose_name='上次购买时间')),
                ('tag', models.CharField(blank=True, max_length=30, null=True, verbose_name='用户标签')),
                ('gift_times', models.IntegerField(default=0, verbose_name='赠品次数')),
                ('vip_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='特殊类型')),
                ('return_time', models.DateTimeField(blank=True, null=True, verbose_name='最后一次回访时间')),
                ('contact_times', models.IntegerField(blank=True, default=0, null=True, verbose_name='回访关怀次数')),
                ('wechat', models.CharField(blank=True, max_length=60, null=True, verbose_name='微信号')),
                ('customers_service_times', models.IntegerField(default=0, verbose_name='售后次数')),
                ('maintenance_times', models.IntegerField(default=0, verbose_name='中央维修次数')),
                ('momery', models.CharField(blank=True, max_length=30, null=True, verbose_name='备注')),
                ('order_failure_times', models.IntegerField(default=0, verbose_name='订单失败')),
            ],
            options={
                'verbose_name': 'CRM-C-客户信息',
                'verbose_name_plural': 'CRM-C-客户信息',
                'db_table': 'crm_c_customerinfo',
            },
        ),
        migrations.CreateModel(
            name='CustomerTendency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('customer_id', models.IntegerField(default=0, verbose_name='客户编号')),
                ('mobile', models.CharField(max_length=30, verbose_name='手机')),
                ('habit_time', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='习惯趋向-时间')),
                ('habit_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='习惯趋向-区域')),
                ('ability_consume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='消费能力趋向')),
            ],
            options={
                'verbose_name': 'CRM-C-客户积分卡',
                'verbose_name_plural': 'CRM-C-客户积分卡',
                'db_table': 'crm_c_customertendency',
            },
        ),
    ]
