# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-20 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('mobile', models.CharField(max_length=30, verbose_name='手机')),
                ('satisficing', models.IntegerField(default=100, verbose_name='客户满意指数')),
                ('category', models.CharField(blank=True, max_length=30, null=True, verbose_name='客户类别')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, max_length=30, null=True, verbose_name='性别')),
                ('nationality', models.CharField(blank=True, max_length=30, null=True, verbose_name='国家')),
                ('province', models.CharField(max_length=30, verbose_name='省份')),
                ('city', models.CharField(max_length=30, verbose_name='城市')),
                ('district', models.CharField(blank=True, max_length=30, null=True, verbose_name='区县')),
                ('address', models.CharField(max_length=30, verbose_name='地址')),
                ('e_mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='电子邮件')),
                ('qq', models.CharField(blank=True, max_length=30, null=True, verbose_name='QQ')),
                ('wangwang', models.CharField(max_length=30, verbose_name='旺旺')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='生日')),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='购买总金额')),
                ('total_times', models.IntegerField(verbose_name='购买总次数')),
                ('last_time', models.DateTimeField(verbose_name='上次购买时间')),
                ('tag', models.CharField(blank=True, max_length=30, null=True, verbose_name='用户标签')),
                ('gift_times', models.IntegerField(blank=True, null=True, verbose_name='赠品次数')),
                ('vip_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='特殊类型')),
                ('return_time', models.DateTimeField(blank=True, null=True, verbose_name='最后一次回访时间')),
                ('contact_times', models.IntegerField(blank=True, default=0, null=True, verbose_name='回访关怀次数')),
                ('wechat', models.CharField(blank=True, max_length=30, null=True, verbose_name='微信号')),
                ('customers_service_times', models.IntegerField(default=0, verbose_name='售后次数')),
                ('maintenance_times', models.IntegerField(default=0, verbose_name='中央维修次数')),
                ('momery', models.CharField(blank=True, max_length=30, null=True, verbose_name='备注')),
                ('custom_field2', models.CharField(blank=True, max_length=30, null=True, verbose_name='未定义标签2')),
                ('custom_field3', models.CharField(blank=True, max_length=30, null=True, verbose_name='未定义标签3')),
                ('custom_field4', models.CharField(blank=True, max_length=30, null=True, verbose_name='未定义标签4')),
                ('custom_field5', models.CharField(blank=True, max_length=30, null=True, verbose_name='未定义标签5')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
            },
        ),
        migrations.CreateModel(
            name='CustomerTendency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('customer_id', models.IntegerField(default=0, verbose_name='客户编号')),
                ('mobile', models.CharField(max_length=30, verbose_name='手机')),
                ('habit_time', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='习惯趋向-时间')),
                ('habit_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='习惯趋向-区域')),
                ('ability_consume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='消费能力趋向')),
                ('conformity_imitate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='心里趋向-从众-效仿')),
                ('divergent_difference', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='心里趋向-求异-特立')),
                ('comparing_varity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='心里趋向-攀比-虚荣')),
                ('realistic_economy', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='心里趋向-求实-经济')),
            ],
            options={
                'verbose_name': '客户积分卡',
                'verbose_name_plural': '客户积分卡',
            },
        ),
    ]
