# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-21 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoutIdList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('ori_order_trade_no', models.CharField(db_index=True, max_length=120, unique=True, verbose_name='计数单号列表')),
            ],
            options={
                'verbose_name': 'CRM-C-计数单号列表',
                'verbose_name_plural': 'CRM-C-计数单号列表',
                'db_table': 'crm_c_order_countlist',
            },
        ),
    ]
