# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-21 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='alipay_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='支付宝账号'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='wangwang',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='旺旺'),
        ),
    ]
