# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-21 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_coutidlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoutIdList',
            new_name='CountIdList',
        ),
    ]
