# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-21 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20181221_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='gfsc_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='官方商城账号'),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='jdfbp_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='京东FBP账号'),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='jdzy_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='京东自营账号'),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='pdd_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='拼多多账号'),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='wxxcx_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='微信小程序账号'),
        ),
    ]
