# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-21 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20181221_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertendency',
            name='conformity_imitate',
        ),
        migrations.RemoveField(
            model_name='customertendency',
            name='divergent_difference',
        ),
        migrations.AlterField(
            model_name='customertendency',
            name='comparing_varity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='心里趋向-攀比'),
        ),
        migrations.AlterField(
            model_name='customertendency',
            name='realistic_economy',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='心里趋向-求实'),
        ),
    ]
