# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-21 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20201121_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinfo',
            old_name='momery',
            new_name='memorandum',
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='order_failure_times',
            field=models.IntegerField(default=0, verbose_name='退款次数'),
        ),
    ]
