# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-25 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20181221_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='last_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次购买时间'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='购买总金额'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='total_times',
            field=models.IntegerField(default=0, verbose_name='购买总次数'),
        ),
    ]
