# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-21 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20201121_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='total_amount',
            field=models.FloatField(default=0, verbose_name='购买总金额'),
        ),
    ]
