# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-09 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20181230_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='order_failure_times',
            field=models.IntegerField(default=0, verbose_name='订单失败'),
        ),
    ]
