# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-09 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customerinfo_order_failure_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='alipay_id',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='支付宝账号'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='gfsc_id',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='官方商城账号'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='jdfbp_id',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='京东FBP账号'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='jdzy_id',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='京东自营账号'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='pdd_id',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='拼多多账号'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='wangwang',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='旺旺'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='wechat',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='微信号'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='wxxcx_id',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='微信小程序账号'),
        ),
    ]
