# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-08 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_auto_20190109_1643'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerinfo',
            table='customerinfo',
        ),
        migrations.AlterModelTable(
            name='customertendency',
            table='customertendency',
        ),
    ]
