# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-20 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_auto_20190408_2119'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerinfo',
            table='crm_c_customerinfo',
        ),
        migrations.AlterModelTable(
            name='customertendency',
            table='crm_c_customertendency',
        ),
    ]
