# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-22 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_auto_20190420_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='custom_field2',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='custom_field3',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='custom_field4',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='custom_field5',
        ),
    ]
