# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-18 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseinfo',
            name='address',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='warehouseinfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='电话'),
        ),
        migrations.AddField(
            model_name='warehouseinfo',
            name='receiver',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='收货人'),
        ),
    ]
