# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-06 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='category',
            field=models.SmallIntegerField(choices=[(0, '截单退回'), (1, '无人收货'), (2, '客户拒签'), (3, '修改地址'), (4, '催件派送'), (5, '虚假签收'), (6, '丢件破损'), (7, '其他异常')], default=0, verbose_name='工单事项类型'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='process_tag',
            field=models.SmallIntegerField(choices=[(0, '未分类'), (1, '待截单'), (2, '签复核'), (3, '改地址'), (4, '催派查'), (5, '丢件核'), (6, '纠纷中'), (7, '其他')], default=0, verbose_name='处理标签'),
        ),
    ]
