# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-04 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='order_status',
            field=models.SmallIntegerField(choices=[(0, '已被取消'), (1, '快递未递'), (2, '逆向未理'), (3, '正向未递'), (4, '快递在理'), (5, '复核未理'), (6, '终审未理'), (7, '工单完结')], default=1, verbose_name='工单状态'),
        ),
    ]
