# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-24 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorderex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'verbose_name': 'EXT-快递工单-查询', 'verbose_name_plural': 'EXT-快递工单-查询'},
        ),
        migrations.AlterModelOptions(
            name='workorderapp',
            options={'verbose_name': 'EXT-快递工单-正向', 'verbose_name_plural': 'EXT-快递工单-正向'},
        ),
        migrations.AlterModelOptions(
            name='workorderapprev',
            options={'verbose_name': 'EXT-快递工单-逆向', 'verbose_name_plural': 'EXT-快递工单-逆向'},
        ),
        migrations.AlterModelOptions(
            name='workorderhandle',
            options={'verbose_name': 'EXT-快递工单处理-客服', 'verbose_name_plural': 'EXT-快递工单处理-客服'},
        ),
        migrations.AlterModelOptions(
            name='workorderhandlesto',
            options={'verbose_name': 'EXT-快递工单处理-供应商', 'verbose_name_plural': 'EXT-快递工单处理-供应商'},
        ),
        migrations.AlterModelOptions(
            name='workorderkeshen',
            options={'verbose_name': 'EXT-快递工单复核-客审', 'verbose_name_plural': 'EXT-快递工单复核-客审'},
        ),
        migrations.AlterModelOptions(
            name='workordermine',
            options={'verbose_name': 'EXT-快递工单-只看自己', 'verbose_name_plural': 'EXT-快递工单-只看自己'},
        ),
    ]
