# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-12 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderex', '0002_auto_20191204_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderFinance',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-快递工单-财务审核',
                'verbose_name_plural': 'EXT-快递工单-财务审核',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorderex.workorder',),
        ),
        migrations.AlterModelOptions(
            name='workorderapp',
            options={'verbose_name': 'EXT-快递工单-正向创建', 'verbose_name_plural': 'EXT-快递工单-正向创建'},
        ),
        migrations.AlterModelOptions(
            name='workorderapprev',
            options={'verbose_name': 'EXT-快递工单-逆向创建', 'verbose_name_plural': 'EXT-快递工单-逆向创建'},
        ),
        migrations.AlterModelOptions(
            name='workorderhandle',
            options={'verbose_name': 'EXT-快递工单-客服处理', 'verbose_name_plural': 'EXT-快递工单-客服处理'},
        ),
        migrations.AlterModelOptions(
            name='workorderhandlesto',
            options={'verbose_name': 'EXT-快递工单-供应商处理', 'verbose_name_plural': 'EXT-快递工单-供应商处理'},
        ),
        migrations.AlterModelOptions(
            name='workorderkeshen',
            options={'verbose_name': 'EXT-快递工单-客审复核', 'verbose_name_plural': 'EXT-快递工单-客审复核'},
        ),
        migrations.AlterModelOptions(
            name='workordermine',
            options={'verbose_name': 'EXT-快递工单-终审确认', 'verbose_name_plural': 'EXT-快递工单-终审确认'},
        ),
        migrations.AlterField(
            model_name='workorder',
            name='order_status',
            field=models.SmallIntegerField(choices=[(0, '已被取消'), (1, '快递未递'), (2, '逆向未理'), (3, '正向未递'), (4, '快递在理'), (5, '复核未理'), (6, '终审未理'), (7, '财务审核'), (8, '工单完结')], default=1, verbose_name='工单状态'),
        ),
    ]
