# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-29 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderex', '0002_auto_20191024_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='process_tag',
            field=models.SmallIntegerField(choices=[(0, '未分类别'), (1, '截单等待'), (2, '催派查件'), (3, '签收复核'), (4, '丢件核实'), (5, '客户冲突'), (6, '其他异常')], default=0, verbose_name='处理标签'),
        ),
    ]
