# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-08 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDMirror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('target', models.CharField(max_length=150, verbose_name='任务对象')),
                ('is_completed', models.BooleanField(default=True, verbose_name='目标是否达成')),
                ('outcome', models.SmallIntegerField(blank=True, choices=[(1, '电话连通'), (2, '电话未通'), (3, '旺旺留言有效'), (4, '旺旺留言无效')], null=True, verbose_name='结果')),
                ('handler', models.CharField(blank=True, max_length=60, null=True, verbose_name='实施人')),
                ('memorandum', models.CharField(blank=True, max_length=220, null=True, verbose_name='备注')),
                ('order_status', models.SmallIntegerField(choices=[(0, '已取消'), (1, '待生成'), (2, '待执行'), (3, '待分配'), (4, '待完成'), (5, '已完成')], db_index=True, default=1, verbose_name='单据状态')),
                ('process_tag', models.SmallIntegerField(choices=[(0, '未处理'), (1, '待分配'), (2, '已领取'), (3, '待清理'), (4, '已处理'), (5, '驳回'), (6, '特殊订单')], default=0, verbose_name='处理标签')),
                ('mistake_tag', models.SmallIntegerField(choices=[(0, '正常'), (1, '无结果任务不可审核'), (2, 'UT中无此店铺'), (3, 'UT中店铺关联平台'), (4, '保存出错')], default=0, verbose_name='错误列表')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.CustomerInfo', verbose_name='客户')),
            ],
            options={
                'verbose_name': 'crm-关系任务明细-查询',
                'verbose_name_plural': 'crm-关系任务明细-查询',
                'db_table': 'crm_ser_orderdetail_mirror',
            },
        ),
        migrations.CreateModel(
            name='SIMirror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True, verbose_name='任务名称')),
                ('order_category', models.SmallIntegerField(choices=[(1, '电话'), (2, '短信'), (3, '旺旺留言')], db_index=True, default=1, verbose_name='订单类型')),
                ('prepare_time', models.DateTimeField(blank=True, null=True, verbose_name='预计开始时间')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='实际开始时间')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('services_info', models.TextField(blank=True, null=True, verbose_name='任务说明和要点')),
                ('quantity', models.IntegerField(verbose_name='任务客户数量')),
                ('memorandum', models.CharField(blank=True, max_length=150, null=True, verbose_name='备注')),
                ('order_status', models.SmallIntegerField(choices=[(0, '已取消'), (1, '待生成'), (2, '待执行'), (3, '待分配'), (4, '待完成'), (5, '已完成')], db_index=True, default=1, verbose_name='单据状态')),
                ('process_tag', models.SmallIntegerField(choices=[(0, '未处理'), (1, '待核实'), (2, '已确认'), (3, '待清理'), (4, '已处理'), (5, '驳回'), (6, '特殊订单')], default=0, verbose_name='处理标签')),
                ('mistake_tag', models.SmallIntegerField(choices=[(0, '正常'), (1, '已导入过的订单'), (2, 'UT中无此店铺'), (3, 'UT中店铺关联平台'), (4, '保存出错')], default=0, verbose_name='错误列表')),
                ('ori_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ServicesInfo', verbose_name='源订单')),
            ],
            options={
                'verbose_name': 'crm-关系任务-查询',
                'verbose_name_plural': 'crm-关系任务-查询',
                'db_table': 'crm_ser_orderinfo_mirror',
            },
        ),
        migrations.AddField(
            model_name='sdmirror',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.SIMirror', verbose_name='关系任务'),
        ),
    ]
