# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-10 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20201208_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdmirror',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sdmirror',
            name='services',
        ),
        migrations.RemoveField(
            model_name='simirror',
            name='ori_order',
        ),
        migrations.DeleteModel(
            name='SDMirror',
        ),
        migrations.DeleteModel(
            name='SIMirror',
        ),
    ]
