# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-10 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20201210_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesdetail',
            name='services_info',
            field=models.TextField(blank=True, null=True, verbose_name='任务说明和要点'),
        ),
        migrations.AlterField(
            model_name='servicesdetail',
            name='memorandum',
            field=models.TextField(blank=True, max_length=220, null=True, verbose_name='备注'),
        ),
    ]
