# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-10 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20201210_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesinfo',
            name='count_down',
            field=models.IntegerField(blank=True, null=True, verbose_name='预计开始倒计时'),
        ),
    ]
