# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-10 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicesinfo_count_down'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SSIOnProcess',
        ),
        migrations.AlterModelOptions(
            name='ssidistribute',
            options={'verbose_name': 'crm-关系任务-可分配', 'verbose_name_plural': 'crm-关系任务-可分配'},
        ),
        migrations.AlterModelOptions(
            name='ssiprocess',
            options={'verbose_name': 'crm-关系任务-待分配', 'verbose_name_plural': 'crm-关系任务-待分配'},
        ),
        migrations.AddField(
            model_name='servicesdetail',
            name='hande_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实施时间'),
        ),
        migrations.AlterField(
            model_name='servicesdetail',
            name='order_status',
            field=models.SmallIntegerField(choices=[(0, '已取消'), (1, '待生成'), (2, '待分配'), (3, '待执行'), (4, '已完成')], db_index=True, default=1, verbose_name='单据状态'),
        ),
        migrations.AlterField(
            model_name='servicesinfo',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '任务说明和要点为必填项'), (2, 'UT中无此店铺'), (3, 'UT中店铺关联平台'), (4, '保存出错')], default=0, verbose_name='错误列表'),
        ),
    ]
