# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-10 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20201210_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesinfo',
            name='completed_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='已完成数量'),
        ),
        migrations.AddField(
            model_name='servicesinfo',
            name='received_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='已领取数量'),
        ),
        migrations.AlterField(
            model_name='servicesdetail',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '无实施时间'), (2, '无处理结果')], default=0, verbose_name='错误列表'),
        ),
    ]
