# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-10 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20201210_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSIFinished',
            fields=[
            ],
            options={
                'verbose_name': 'crm-关系任务-待完结',
                'verbose_name_plural': 'crm-关系任务-待完结',
                'proxy': True,
                'indexes': [],
            },
            bases=('services.servicesinfo',),
        ),
        migrations.RenameField(
            model_name='servicesdetail',
            old_name='hande_time',
            new_name='handle_time',
        ),
        migrations.AlterField(
            model_name='servicesinfo',
            name='completed_num',
            field=models.IntegerField(default=0, verbose_name='已完成数量'),
        ),
        migrations.AlterField(
            model_name='servicesinfo',
            name='received_num',
            field=models.IntegerField(default=0, verbose_name='在执行数量'),
        ),
    ]
