# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-15 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20201212_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesdetail',
            name='order_type',
            field=models.SmallIntegerField(choices=[(1, '常规任务'), (2, '快捷注册任务')], default=1, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='servicesinfo',
            name='order_type',
            field=models.SmallIntegerField(choices=[(1, '常规任务'), (2, '快捷注册任务')], default=1, verbose_name='任务类型'),
        ),
    ]
