# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-16 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20201215_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesdetail',
            name='process_tag',
            field=models.SmallIntegerField(choices=[(0, '未处理'), (1, '待分配'), (2, '已领取'), (3, '待清理'), (4, '已处理'), (5, '驳回'), (6, '特殊订单'), (7, '自动过滤')], default=0, verbose_name='处理标签'),
        ),
    ]
