# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-16 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20201216_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesdetail',
            name='warranty_sn',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='延保码'),
        ),
    ]
