# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-16 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_servicesdetail_warranty_sn'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDCreate',
            fields=[
            ],
            options={
                'verbose_name': 'crm-关系任务明细-待生成',
                'verbose_name_plural': 'crm-关系任务明细-待生成',
                'proxy': True,
                'indexes': [],
            },
            bases=('services.servicesdetail',),
        ),
    ]
