# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-17 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_sdcreate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDFeedback',
            fields=[
            ],
            options={
                'verbose_name': 'crm-关系任务明细-待反馈',
                'verbose_name_plural': 'crm-关系任务明细-待反馈',
                'proxy': True,
                'indexes': [],
            },
            bases=('services.servicesdetail',),
        ),
        migrations.AlterField(
            model_name='servicesdetail',
            name='order_status',
            field=models.SmallIntegerField(choices=[(0, '已取消'), (1, '待生成'), (2, '待分配'), (3, '待执行'), (4, '待反馈'), (5, '已完成')], db_index=True, default=1, verbose_name='单据状态'),
        ),
        migrations.AlterField(
            model_name='servicesdetail',
            name='outcome',
            field=models.SmallIntegerField(choices=[(0, '未执行'), (1, '电话连通'), (2, '电话未通'), (3, '短信已发'), (4, '旺旺已留言'), (5, '旺旺留言失败')], default=0, verbose_name='结果'),
        ),
    ]
