# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-18 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20201217_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesdetail',
            name='outcome',
            field=models.SmallIntegerField(choices=[(0, '未执行'), (1, '电话连通'), (2, '电话未通'), (3, '短信已发'), (4, '旺旺已留言'), (5, '旺旺留言失败'), (6, '客户自行注册')], default=0, verbose_name='结果'),
        ),
    ]
