# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-25 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20201218_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesdetail',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '无实施时间'), (2, '无处理结果'), (3, '非旺旺任务无法批量完结')], default=0, verbose_name='错误列表'),
        ),
        migrations.AlterField(
            model_name='servicesinfo',
            name='received_num',
            field=models.IntegerField(default=0, verbose_name='待反馈数量'),
        ),
    ]
