# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-19 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('erp_order_id', models.CharField(max_length=30, verbose_name='订单编号')),
                ('shop', models.CharField(max_length=30, verbose_name='店铺')),
                ('order_source', models.CharField(max_length=30, verbose_name='订单来源')),
                ('warehouse', models.CharField(max_length=30, verbose_name='仓库')),
                ('sub_original_order_id', models.CharField(max_length=30, verbose_name='子单原始单号')),
                ('status', models.CharField(max_length=30, verbose_name='订单状态')),
                ('order_type', models.CharField(max_length=30, verbose_name='订单类型')),
                ('cash_on_delivery', models.CharField(max_length=30, verbose_name='货到付款')),
                ('refund_status', models.CharField(max_length=30, verbose_name='订单退款状态')),
                ('order_time', models.DateTimeField(blank=True, null=True, verbose_name='交易时间')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='付款时间')),
                ('buyer_nick', models.CharField(max_length=100, verbose_name='客户网名')),
                ('receiver_name', models.CharField(max_length=100, verbose_name='收件人')),
                ('receiver_area', models.CharField(max_length=30, verbose_name='收货地区')),
                ('receiver_address', models.CharField(max_length=200, verbose_name='收货地址')),
                ('receiver_mobile', models.CharField(max_length=30, verbose_name='收件人手机')),
                ('distributor', models.CharField(max_length=30, verbose_name='分销商')),
                ('discreteness_source_id', models.CharField(max_length=30, verbose_name='来源组合装编号')),
                ('receiver_telephone', models.CharField(max_length=30, verbose_name='收件人电话')),
                ('zip_code', models.CharField(max_length=30, verbose_name='邮编')),
                ('order_area', models.CharField(max_length=30, verbose_name='区域')),
                ('logistics_company', models.CharField(max_length=30, verbose_name='物流公司')),
                ('invoice_no', models.CharField(max_length=30, verbose_name='物流单号')),
                ('buyer_message', models.CharField(max_length=500, verbose_name='买家留言')),
                ('seller_remark', models.CharField(max_length=500, verbose_name='客服备注')),
                ('print_remark', models.CharField(max_length=500, verbose_name='打印备注')),
                ('payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='订单支付金额')),
                ('post_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='邮费')),
                ('discount_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='订单总优惠')),
                ('total_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='应收金额')),
                ('payment_and_delivery_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='款到发货金额')),
                ('cod_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='货到付款金额')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预估重量')),
                ('has_invoice', models.CharField(max_length=30, verbose_name='需要发票')),
                ('invoice_rise', models.CharField(max_length=30, verbose_name='发票抬头')),
                ('invoice_content', models.CharField(max_length=30, verbose_name='发票内容')),
                ('salesman', models.CharField(max_length=30, verbose_name='业务员')),
                ('auditor', models.CharField(max_length=30, verbose_name='审核人')),
                ('goods_id', models.CharField(max_length=30, verbose_name='商家编码')),
                ('goods_code', models.CharField(max_length=30, verbose_name='货品编号')),
                ('goods_name', models.CharField(max_length=30, verbose_name='货品名称')),
                ('goods_specification', models.CharField(max_length=30, verbose_name='规格名称')),
                ('platform_goods_name', models.CharField(max_length=150, verbose_name='平台货品名称')),
                ('platform_goods_specification', models.CharField(max_length=150, verbose_name='平台规格名称')),
                ('quantity', models.IntegerField(verbose_name='下单数量')),
                ('fixed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='标价')),
                ('goods_discount_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='货品总优惠')),
                ('goods_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='成交价')),
                ('allocated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='分摊后价格')),
                ('discount_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='打折比')),
                ('real_quantity', models.IntegerField(verbose_name='实发数量')),
                ('allocated_total_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='分摊后总价')),
                ('before_refund_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='退款前支付金额')),
                ('allocated_post_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='分摊邮费')),
                ('goods_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='单品支付金额')),
                ('discreteness_id', models.CharField(max_length=30, verbose_name='拆自组合装')),
                ('gift_type', models.CharField(max_length=30, verbose_name='赠品方式')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
    ]
