# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-19 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='handlingstatus',
            field=models.CharField(choices=[(0, '未审核'), (1, '已处理'), (2, '已完结')], default=0, max_length=30, verbose_name='生成客户信息状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='buyer_nick',
            field=models.CharField(db_index=True, max_length=100, verbose_name='客户网名'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='receiver_mobile',
            field=models.CharField(db_index=True, max_length=30, verbose_name='收件人手机'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='sub_original_order_id',
            field=models.CharField(db_index=True, max_length=30, verbose_name='子单原始单号'),
        ),
    ]
