# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-12 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='shop_name',
            field=models.CharField(db_index=True, max_length=128, verbose_name='店铺'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='warehouse_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='仓库'),
        ),
    ]
