# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-21 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='process_tag',
            field=models.SmallIntegerField(choices=[(0, '未处理'), (1, '待核实'), (2, '已确认'), (3, '待清账'), (4, '已处理'), (5, '驳回'), (6, '特殊订单'), (7, '手工设置成功')], default=0, verbose_name='处理标签'),
        ),
    ]
