# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-11-01 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleorderinfo',
            name='shop_name',
        ),
    ]
