# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-11-03 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_simpleorderinfo_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oriorderinfo',
            name='deliver_time',
            field=models.DateTimeField(db_index=True, verbose_name='发货时间'),
        ),
        migrations.AlterField(
            model_name='oriorderinfo',
            name='share_amount',
            field=models.FloatField(verbose_name='货品成交总价'),
        ),
    ]
