# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-22 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201121_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelOrder',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-UT订单-可标签查询',
                'verbose_name_plural': 'CRM-UT订单-可标签查询',
                'proxy': True,
                'indexes': [],
            },
            bases=('orders.orderinfo',),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='process_tag',
            field=models.SmallIntegerField(choices=[(0, '未处理'), (1, '待核实'), (2, '已确认'), (3, '待清理'), (4, '已处理'), (5, '驳回'), (6, '特殊订单'), (7, '手工设置成功')], default=0, verbose_name='处理标签'),
        ),
        migrations.AlterField(
            model_name='oriorderinfo',
            name='process_tag',
            field=models.SmallIntegerField(choices=[(0, '未处理'), (1, '待核实'), (2, '已确认'), (3, '待清理'), (4, '已处理'), (5, '驳回'), (6, '特殊订单')], default=0, verbose_name='处理标签'),
        ),
    ]
