# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-22 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201122_1656'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabelOrder',
        ),
        migrations.CreateModel(
            name='LabelOptions',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-UT订单-可标签查询',
                'verbose_name_plural': 'CRM-UT订单-可标签查询',
                'proxy': True,
                'indexes': [],
            },
            bases=('orders.orderinfo',),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_status',
            field=models.SmallIntegerField(choices=[(0, '已取消'), (1, '未处理'), (2, '未关联'), (3, '未财审'), (4, '已完成')], db_index=True, default=1, verbose_name='单据状态'),
        ),
    ]
