# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-21 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181219_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='platform',
            field=models.CharField(default='淘宝', max_length=30, verbose_name='平台'),
        ),
    ]
