# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-26 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_oribmsorderinfo_submitobmsorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oribmsorderinfo',
            name='deliver_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='发货时间'),
        ),
    ]
