# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-21 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderinfo_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='handlingstatus',
            new_name='tocustomer_status',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='totendency_ac_status',
            field=models.CharField(choices=[(0, '未审核'), (1, '已处理'), (2, '已完结')], default=0, max_length=30, verbose_name='生成消费能力状态'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='totendency_cv_status',
            field=models.CharField(choices=[(0, '未审核'), (1, '已处理'), (2, '已完结')], default=0, max_length=30, verbose_name='生成心里攀比状态'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='totendency_ha_status',
            field=models.CharField(choices=[(0, '未审核'), (1, '已处理'), (2, '已完结')], default=0, max_length=30, verbose_name='生成习惯区域状态'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='totendency_ht_status',
            field=models.CharField(choices=[(0, '未审核'), (1, '已处理'), (2, '已完结')], default=0, max_length=30, verbose_name='生成习惯时间状态'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='totendency_re_status',
            field=models.CharField(choices=[(0, '未审核'), (1, '已处理'), (2, '已完结')], default=0, max_length=30, verbose_name='生成心里求实状态'),
        ),
    ]
