# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-24 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201122_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labeloptions',
            options={'verbose_name': 'CRM-UT订单-未标记', 'verbose_name_plural': 'CRM-UT订单-未标记'},
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_status',
            field=models.SmallIntegerField(choices=[(0, '已取消'), (1, '未处理'), (2, '未标记'), (3, '未财审'), (4, '已完成')], db_index=True, default=1, verbose_name='单据状态'),
        ),
    ]
