# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-26 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201226_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oribmsorderinfo',
            name='deliver_time',
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='src_tids',
            field=models.CharField(blank=True, db_index=True, max_length=101, null=True, verbose_name='原始子订单号'),
        ),
        migrations.AlterField(
            model_name='oriorderinfo',
            name='src_tids',
            field=models.CharField(blank=True, db_index=True, max_length=101, null=True, verbose_name='原始子订单号'),
        ),
    ]
