# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-11-03 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201103_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oriorderinfo',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '14天内重复订单')], default=0, verbose_name='错误列表'),
        ),
        migrations.AlterField(
            model_name='oriorderinfo',
            name='src_tids',
            field=models.TextField(blank=True, null=True, verbose_name='原始子订单号'),
        ),
    ]
