# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-26 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20181221_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='totendency_cv_status',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='totendency_re_status',
        ),
    ]
