# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-27 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20181226_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='exception_tag',
            field=models.BooleanField(default=0, verbose_name='手机异常标记'),
        ),
    ]
