# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-28 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20181228_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='buyer_message',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='买家留言'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='invoice_content',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='发票内容'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='invoice_rise',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='发票抬头'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='seller_remark',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='客服备注'),
        ),
    ]
