# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-28 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20181228_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='goods_name',
            field=models.CharField(max_length=150, verbose_name='货品名称'),
        ),
    ]
