# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-09 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20181228_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='tocustomer_status',
            field=models.CharField(choices=[(0, '未审核'), (1, '已处理'), (2, '无效'), (3, '异常')], default=0, max_length=30, verbose_name='生成客户信息状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='totendency_ac_status',
            field=models.CharField(choices=[(0, '未审核'), (1, '已处理'), (2, '无效'), (3, '异常')], default=0, max_length=30, verbose_name='生成消费能力状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='totendency_ha_status',
            field=models.CharField(choices=[(0, '未审核'), (1, '已处理'), (2, '无效'), (3, '异常')], default=0, max_length=30, verbose_name='生成习惯区域状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='totendency_ht_status',
            field=models.CharField(choices=[(0, '未审核'), (1, '已处理'), (2, '无效'), (3, '异常')], default=0, max_length=30, verbose_name='生成习惯时间状态'),
        ),
    ]
