# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-10 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20190410_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='tocustomer_status',
            field=models.SmallIntegerField(choices=[(0, '未审核'), (1, '已处理'), (2, '无效'), (3, '异常')], default=0, verbose_name='生成客户信息状态'),
        ),
    ]
