# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-11-12 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('company', '0005_companyinfo_discount_rate'),
        ('shop', '0004_auto_20200401_0943'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderDealerPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('order_id', models.CharField(max_length=150, verbose_name='源订单号')),
                ('nickname', models.CharField(max_length=150, verbose_name='客户网名')),
                ('sent_consignee', models.CharField(max_length=150, verbose_name='收件人姓名')),
                ('sent_smartphone', models.CharField(max_length=30, verbose_name='收件人手机')),
                ('sent_district', models.CharField(blank=True, max_length=30, null=True, verbose_name='收件区县')),
                ('sent_address', models.CharField(max_length=200, verbose_name='收件地址')),
                ('parts_info', models.CharField(max_length=300, verbose_name='配件信息')),
                ('message', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('submit_time', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('handler', models.CharField(blank=True, max_length=150, null=True, verbose_name='处理人')),
                ('handle_time', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('handle_interval', models.IntegerField(blank=True, null=True, verbose_name='处理间隔(分钟)')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='订单反馈')),
                ('process_tag', models.SmallIntegerField(choices=[(0, '未处理'), (1, '待核实'), (2, '已确认'), (3, '待清账'), (4, '已处理'), (5, '驳回'), (6, '特殊订单')], default=0, verbose_name='处理标签')),
                ('mistake_tag', models.SmallIntegerField(choices=[(0, '正常'), (1, '一个订单不可重复递交'), (2, '同一收件人有多个订单'), (3, '货品名称包含整机不是配件'), (4, '货品名称错误，或者货品格式错误'), (5, '店铺错误'), (6, '手机号错误'), (7, '地址是集运仓'), (8, '收货人信息不全'), (9, '14天内重复递交过订单'), (10, '14天外重复递交过订单'), (11, '创建配件发货单错误')], default=0, verbose_name='错误原因')),
                ('order_status', models.SmallIntegerField(choices=[(0, '已取消'), (1, '未递交'), (2, '未审核'), (3, '已生成')], default=1, verbose_name='订单状态')),
                ('order_category', models.SmallIntegerField(choices=[(1, '质量问题'), (2, '开箱即损'), (3, '礼品赠品')], default=3, verbose_name='单据类型')),
                ('sent_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.CityInfo', verbose_name='收件城市')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ShopInfo', verbose_name='店铺')),
                ('sign_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wodp_company', to='company.CompanyInfo', verbose_name='创建公司')),
                ('sign_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wodp_department', to='department.DepartmentInfo', verbose_name='创建部门')),
            ],
            options={
                'verbose_name': 'EXT-经销商配件-查询',
                'verbose_name_plural': 'EXT-经销商配件-查询',
                'db_table': 'ext_wo_dealerpart',
            },
        ),
        migrations.CreateModel(
            name='CheckWODP',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-经销商配件-未审核',
                'verbose_name_plural': 'EXT-经销商配件-未审核',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorderdp.workorderdealerpart',),
        ),
        migrations.CreateModel(
            name='SubmitWODP',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-经销商配件-未提交',
                'verbose_name_plural': 'EXT-经销商配件-未提交',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorderdp.workorderdealerpart',),
        ),
    ]
