# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-13 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderdp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderdealerpart',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '一个订单不可重复递交'), (2, '同一收件人有多个订单'), (3, '货品名称包含整机不是配件'), (4, '货品名称错误，或者货品格式错误'), (5, '店铺错误'), (6, '手机号错误'), (7, '地址是集运仓'), (8, '收货人信息不全'), (9, '14天内重复递交过订单'), (10, '14天外重复递交过订单'), (11, '创建配件发货单错误'), (12, '无三级区县')], default=0, verbose_name='错误原因'),
        ),
    ]
