# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-28 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufactoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='工厂名称')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='工厂代码')),
                ('category', models.IntegerField(choices=[(0, '整机厂'), (1, '配件厂')], default=0, verbose_name='工厂类型')),
                ('contacts', models.CharField(max_length=60, verbose_name='联系人')),
                ('contacts_phone', models.CharField(max_length=30, verbose_name='电话')),
                ('memorandum', models.CharField(max_length=150, verbose_name='备注')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.CityInfo', verbose_name='城市')),
            ],
            options={
                'verbose_name': 'BASE-工厂信息',
                'verbose_name_plural': 'BASE-工厂信息',
                'db_table': 'base_manu_manufactory',
            },
        ),
    ]
