# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-27 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufactory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufactoryinfo',
            old_name='address',
            new_name='city',
        ),
    ]
