# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-28 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('manufactory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufactoryinfo',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.CompanyInfo', verbose_name='所属公司'),
        ),
    ]
