# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-27 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SFConsignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('application_time', models.CharField(max_length=20, verbose_name='日期')),
                ('consignor', models.CharField(max_length=30, verbose_name='委托人')),
                ('information', models.CharField(max_length=600, verbose_name='信息')),
                ('remark', models.CharField(blank=True, max_length=300, null=True, verbose_name='异常知会')),
                ('is_operate', models.CharField(max_length=20, verbose_name='是否操作')),
                ('feedback_time', models.CharField(max_length=20, verbose_name='反馈日期')),
                ('express_id', models.CharField(max_length=100, verbose_name='单号')),
                ('handlingstatus', models.SmallIntegerField(choices=[(0, '未审核'), (1, '已处理'), (2, '已完结')], default=0, verbose_name='委托单状态')),
            ],
            options={
                'verbose_name': 'EXT-顺丰委托单',
                'verbose_name_plural': 'EXT-顺丰委托单',
                'db_table': 'ext_c_sfconsignation',
            },
        ),
    ]
