# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-07-29 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailpartsorder',
            name='order_category',
            field=models.SmallIntegerField(choices=[(1, '质量问题'), (2, '开箱即损'), (3, '礼品赠品')], default=3, verbose_name='单据类型'),
        ),
        migrations.AlterField(
            model_name='tailpartsorder',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '货品包含整机'), (2, '配件名称错误或未添加'), (3, '没收货人'), (4, '14天内重复'), (5, '14天外重复'), (6, '手机号错误'), (7, '地址是集运仓'), (8, '收货人信息不全'), (9, '城市错误'), (10, '单据生成出错')], default=0, verbose_name='错误原因'),
        ),
    ]
