# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-07-25 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='mode_warehouse',
            field=models.SmallIntegerField(blank=True, choices=[(0, '回流'), (1, '二手')], null=True, verbose_name='发货模式'),
        ),
        migrations.AlterField(
            model_name='arrearsbillorder',
            name='mode_warehouse',
            field=models.SmallIntegerField(blank=True, choices=[(0, '回流'), (1, '二手')], null=True, verbose_name='发货模式'),
        ),
        migrations.AlterField(
            model_name='finalstatement',
            name='mode_warehouse',
            field=models.SmallIntegerField(blank=True, choices=[(0, '回流'), (1, '二手')], null=True, verbose_name='发货模式'),
        ),
        migrations.AlterField(
            model_name='refundorder',
            name='mode_warehouse',
            field=models.SmallIntegerField(blank=True, choices=[(0, '回流'), (1, '二手')], null=True, verbose_name='发货模式'),
        ),
    ]
