# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-01 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailpartsorder',
            name='broken_part',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='故障部位'),
        ),
        migrations.AddField(
            model_name='tailpartsorder',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='故障描述'),
        ),
        migrations.AddField(
            model_name='tailpartsorder',
            name='m_sn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='机器序列号'),
        ),
        migrations.AlterField(
            model_name='tailpartsorder',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '货品包含整机'), (2, '配件名称错误或未添加'), (3, '没收货人'), (4, '14天内重复'), (5, '14天外重复'), (6, '手机号错误'), (7, '地址是集运仓'), (8, '收货人信息不全'), (9, '城市错误'), (10, '单据生成出错'), (11, '店铺错误'), (12, '电话重复'), (13, '售后配件需要补全sn、部件和描述')], default=0, verbose_name='错误原因'),
        ),
    ]
