# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-07-07 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oritailorder',
            name='amount',
            field=models.FloatField(default=0, verbose_name='尾货订单总价'),
        ),
    ]
