# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-07-14 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tailsale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABillToAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('abo_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tailsale.ArrearsBillOrder', verbose_name='退款单货品明细')),
            ],
            options={
                'verbose_name': 'EXT-尾货退款对账对照表',
                'verbose_name_plural': 'EXT-尾货退款对账对照表',
                'db_table': 'ext_tailorder_a2a',
            },
        ),
        migrations.CreateModel(
            name='PBillToAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'EXT-尾货付款对账对照表',
                'verbose_name_plural': 'EXT-尾货付款对账对照表',
                'db_table': 'ext_tailorder_p2a',
            },
        ),
        migrations.CreateModel(
            name='AccountCheck',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-尾货对账明细-未处理',
                'verbose_name_plural': 'EXT-尾货对账明细-未处理',
                'proxy': True,
                'indexes': [],
            },
            bases=('tailsale.accountinfo',),
        ),
        migrations.CreateModel(
            name='AccountUnfinished',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-尾货对账明细-未完成',
                'verbose_name_plural': 'EXT-尾货对账明细-未完成',
                'proxy': True,
                'indexes': [],
            },
            bases=('tailsale.accountinfo',),
        ),
        migrations.AlterModelOptions(
            name='accountinfo',
            options={'verbose_name': 'EXT-尾货对账明细-查询', 'verbose_name_plural': 'EXT-尾货对账明细-查询'},
        ),
        migrations.AlterModelOptions(
            name='finalstatement',
            options={'verbose_name': 'EXT-尾货账单', 'verbose_name_plural': 'EXT-尾货账单'},
        ),
        migrations.AlterModelOptions(
            name='finalstatementgoods',
            options={'verbose_name': 'EXT-尾货账单-货品明细', 'verbose_name_plural': 'EXT-尾货账单-货品明细'},
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='order_category',
            field=models.SmallIntegerField(choices=[(1, '销售'), (2, '退货'), (3, '换货'), (4, '售后')], default=1, verbose_name='结算类型'),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='order_status',
            field=models.SmallIntegerField(choices=[(0, '已取消'), (1, '待生成'), (2, '待支付'), (3, '已完成')], default=1, verbose_name='单据状态'),
        ),
        migrations.AlterField(
            model_name='finalstatement',
            name='amount',
            field=models.FloatField(verbose_name='账单金额'),
        ),
        migrations.AlterField(
            model_name='tailorder',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '快递单号错误'), (2, '重复递交'), (3, '结算单保存出错'), (4, '结算单货品保存出错')], default=0, verbose_name='错误原因'),
        ),
        migrations.AddField(
            model_name='pbilltoaccount',
            name='account_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailsale.AccountInfo', verbose_name='对账明细单'),
        ),
        migrations.AddField(
            model_name='pbilltoaccount',
            name='pbo_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tailsale.PBOGoods', verbose_name='付款单货品明细'),
        ),
        migrations.AddField(
            model_name='abilltoaccount',
            name='account_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailsale.AccountInfo', verbose_name='对账明细单'),
        ),
    ]
