# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-07-07 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsale', '0002_oritailorder_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oritailorder',
            old_name='memorandum',
            new_name='feedback',
        ),
        migrations.AlterField(
            model_name='oritailorder',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '账号未设置公司'), (2, '货品金额是零'), (3, '收件人手机错误'), (4, '单号不符合规则')], default=0, verbose_name='错误原因'),
        ),
    ]
