# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-07-31 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsale', '0002_auto_20200729_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalstatement',
            options={'verbose_name': 'EXT-尾货账单-查询', 'verbose_name_plural': 'EXT-尾货账单-查询'},
        ),
        migrations.AlterModelOptions(
            name='rogcheck',
            options={'verbose_name': 'EXT-尾货退换单-待收货', 'verbose_name_plural': 'EXT-尾货退换单-待收货'},
        ),
        migrations.AlterModelOptions(
            name='rogoods',
            options={'verbose_name': 'EXT-尾货退换单-货品明细', 'verbose_name_plural': 'EXT-尾货退换单-货品明细'},
        ),
        migrations.AlterField(
            model_name='oritailorder',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '账号未设置公司'), (2, '货品金额是零'), (3, '收件人手机错误'), (4, '单号不符合规则'), (5, '需要选择拆单发货'), (6, '递交订单出错'), (7, '生成订单货品出错'), (8, '货品数量错误'), (9, '重复生成订单，联系管理员'), (10, '重复生成订单，联系管理员'), (11, '生成订单货品出错，联系管理员'), (12, '发货仓库和单据类型不符'), (13, '订单货品导入出错'), (14, '导入货品编码错误')], default=0, verbose_name='错误原因'),
        ),
        migrations.AlterField(
            model_name='otogoods',
            name='price',
            field=models.FloatField(verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='tailpartsorder',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '货品包含整机'), (2, '配件名称错误或未添加'), (3, '没收货人'), (4, '14天内重复'), (5, '14天外重复'), (6, '手机号错误'), (7, '地址是集运仓'), (8, '收货人信息不全'), (9, '城市错误'), (10, '单据生成出错'), (11, '店铺错误')], default=0, verbose_name='错误原因'),
        ),
    ]
