# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-07-31 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailsale', '0003_auto_20200731_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOPrivilegeGoods',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-尾货订单-完整查询',
                'verbose_name_plural': 'EXT-尾货订单-完整查询',
                'proxy': True,
                'indexes': [],
            },
            bases=('tailsale.togoods',),
        ),
    ]
