# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-07-07 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsale', '0003_auto_20200707_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundorder',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='tailorder',
            name='is_deliver',
        ),
        migrations.RemoveField(
            model_name='tailorder',
            name='memorandum',
        ),
        migrations.RemoveField(
            model_name='tailorder',
            name='nickname',
        ),
        migrations.AddField(
            model_name='tailorder',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='工单反馈'),
        ),
        migrations.AlterField(
            model_name='oritailorder',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='订单反馈'),
        ),
        migrations.AlterField(
            model_name='oritailorder',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='订单留言'),
        ),
        migrations.AlterField(
            model_name='refundorder',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='工单反馈'),
        ),
        migrations.AlterField(
            model_name='refundorder',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='工单留言'),
        ),
        migrations.AlterField(
            model_name='refundorder',
            name='track_no',
            field=models.TextField(blank=True, null=True, verbose_name='返回快递信息'),
        ),
        migrations.AlterField(
            model_name='tailorder',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='工单留言'),
        ),
        migrations.AlterField(
            model_name='tailorder',
            name='track_no',
            field=models.TextField(blank=True, null=True, verbose_name='快递信息'),
        ),
    ]
