# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-07-31 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsale', '0004_toprivilegegoods'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refundorder',
            options={'verbose_name': 'EXT-尾货退货单-查询', 'verbose_name_plural': 'EXT-尾货退货单-查询'},
        ),
        migrations.AlterModelOptions(
            name='rocheck',
            options={'verbose_name': 'EXT-尾货退货单-待处理', 'verbose_name_plural': 'EXT-尾货退货单-待处理'},
        ),
        migrations.AlterModelOptions(
            name='rogcheck',
            options={'verbose_name': 'EXT-尾货退货单-待收货', 'verbose_name_plural': 'EXT-尾货退货单-待收货'},
        ),
        migrations.AlterModelOptions(
            name='rogoods',
            options={'verbose_name': 'EXT-尾货退货单-货品明细', 'verbose_name_plural': 'EXT-尾货退货单-货品明细'},
        ),
        migrations.AlterModelOptions(
            name='rohandle',
            options={'verbose_name': 'EXT-尾货退货单-待递交', 'verbose_name_plural': 'EXT-尾货退货单-待递交'},
        ),
        migrations.AlterField(
            model_name='oritailorder',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '账号未设置公司'), (2, '货品金额是零'), (3, '收件人手机错误'), (4, '单号不符合规则'), (5, '需要选择拆单发货'), (6, '递交订单出错'), (7, '生成订单货品出错'), (8, '货品数量错误'), (9, '重复生成订单，联系管理员'), (10, '重复生成订单，联系管理员'), (11, '生成订单货品出错，联系管理员'), (12, '发货仓库和单据类型不符'), (13, '订单货品导入出错'), (14, '导入货品编码错误'), (15, '重复订单')], default=0, verbose_name='错误原因'),
        ),
        migrations.AlterField(
            model_name='oritailorder',
            name='process_tag',
            field=models.SmallIntegerField(choices=[(0, '未处理'), (1, '待核实'), (2, '已确认'), (3, '待清账'), (4, '已处理'), (5, '驳回'), (6, '物流订单'), (7, '部分发货'), (8, '重损发货'), (9, '非重损发货'), (10, '特殊发货')], default=0, verbose_name='处理标签'),
        ),
        migrations.AlterField(
            model_name='refundorder',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '退换数量超出原单数量'), (2, '退换金额超出原单金额'), (3, '无退货原因'), (4, '无返回快递单号'), (5, '换货单必须要先进行标记'), (6, '非换货单不可以标记'), (7, '非已到货状态不可以审核'), (8, '退换数量和收货数量不一致'), (9, '退换金额和收货金额不一致'), (10, '退换结算单重复'), (11, '生成结算单出错'), (12, '生成结算单货品出错'), (13, '关联的订单未发货'), (14, '不是退货单不可以审核')], default=0, verbose_name='错误原因'),
        ),
        migrations.AlterField(
            model_name='refundorder',
            name='order_category',
            field=models.SmallIntegerField(choices=[(3, '退-退货退款'), (4, '退-换货退回'), (5, '退-仅退款')], default=3, verbose_name='退款类型'),
        ),
    ]
