# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-07-07 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsale', '0004_auto_20200707_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='otogoods',
            name='order_status',
            field=models.SmallIntegerField(choices=[(0, '已取消'), (1, '正常')], default=1, verbose_name='货品状态'),
        ),
        migrations.AddField(
            model_name='rogoods',
            name='order_status',
            field=models.SmallIntegerField(choices=[(0, '已取消'), (1, '正常')], default=1, verbose_name='货品状态'),
        ),
        migrations.AlterField(
            model_name='oritailorder',
            name='order_status',
            field=models.SmallIntegerField(choices=[(0, '已被取消'), (1, '申请未报'), (2, '正在审核'), (3, '单据生成'), (4, '发货完成'), (5, '结算完成')], default=1, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='oritailorder',
            name='process_tag',
            field=models.SmallIntegerField(choices=[(0, '未处理'), (1, '待核实'), (2, '已确认'), (3, '待清账'), (4, '已处理'), (5, '驳回')], default=0, verbose_name='处理标签'),
        ),
    ]
