# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-08-06 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsale', '0005_auto_20200731_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oritailorder',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '账号未设置公司'), (2, '货品金额是零'), (3, '收件人手机错误'), (4, '单号不符合规则'), (5, '需要选择拆单发货'), (6, '递交订单出错'), (7, '生成订单货品出错'), (8, '货品数量错误'), (9, '重复生成订单，联系管理员'), (10, '重复生成订单，联系管理员'), (11, '生成订单货品出错，联系管理员'), (12, '发货仓库和单据类型不符'), (13, '订单货品导入出错'), (14, '导入货品编码错误'), (15, '重复订单'), (16, '型号错误')], default=0, verbose_name='错误原因'),
        ),
    ]
