# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-07-08 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsale', '0005_auto_20200707_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='togoods',
            name='settlement_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='结算总价'),
        ),
        migrations.AddField(
            model_name='togoods',
            name='settlement_price',
            field=models.FloatField(blank=True, null=True, verbose_name='结算单价'),
        ),
        migrations.AlterField(
            model_name='oritailorder',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '账号未设置公司'), (2, '货品金额是零'), (3, '收件人手机错误'), (4, '单号不符合规则'), (5, '需要拆弹发货')], default=0, verbose_name='错误原因'),
        ),
        migrations.AlterField(
            model_name='oritailorder',
            name='process_tag',
            field=models.SmallIntegerField(choices=[(0, '未处理'), (1, '待核实'), (2, '已确认'), (3, '待清账'), (4, '已处理'), (5, '驳回'), (6, '物流订单')], default=0, verbose_name='处理标签'),
        ),
        migrations.AlterField(
            model_name='togoods',
            name='amount',
            field=models.FloatField(verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='togoods',
            name='price',
            field=models.FloatField(verbose_name='单价'),
        ),
    ]
