# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-08-08 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsale', '0007_auto_20200807_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailpartsorder',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '货品包含整机'), (2, '配件名称错误或未添加'), (3, '没收货人'), (4, '14天内重复'), (5, '14天外重复'), (6, '手机号错误'), (7, '地址是集运仓'), (8, '收货人信息不全'), (9, '城市错误'), (10, '单据生成出错'), (11, '店铺错误'), (12, '电话重复')], default=0, verbose_name='错误原因'),
        ),
        migrations.AlterField(
            model_name='tailpartsorder',
            name='process_tag',
            field=models.SmallIntegerField(choices=[(0, '未处理'), (1, '待核实'), (2, '已确认'), (3, '待清账'), (4, '已处理'), (5, '驳回'), (6, '特殊订单')], default=0, verbose_name='处理标签'),
        ),
    ]
