# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-19 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsale', '0009_todelivergoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundorder',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '退换数量超出原单数量'), (2, '退换金额超出原单金额'), (3, '无退货原因'), (4, '无返回快递单号'), (5, '换货单必须要先进行标记'), (6, '非换货单不可以标记'), (7, '非已到货状态不可以审核'), (8, '退换数量和收货数量不一致'), (9, '退换金额和收货金额不一致'), (10, '退换结算单重复'), (11, '生成结算单出错'), (12, '生成结算单货品出错'), (13, '关联的订单未发货'), (14, '不是退货单不可以审核'), (15, '物流单号重复')], default=0, verbose_name='错误原因'),
        ),
    ]
