# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-21 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('maintenance_order_id', models.CharField(max_length=50, verbose_name='保修单号')),
                ('order_status', models.CharField(max_length=30, verbose_name='保修单状态')),
                ('warehouse', models.CharField(max_length=50, verbose_name='收发仓库')),
                ('completer', models.CharField(max_length=50, verbose_name='处理登记人')),
                ('maintenance_type', models.CharField(max_length=50, verbose_name='保修类型')),
                ('fault_type', models.CharField(max_length=50, verbose_name='故障类型')),
                ('transport_type', models.CharField(max_length=50, verbose_name='送修类型')),
                ('machine_sn', models.CharField(max_length=50, verbose_name='序列号')),
                ('new_machine_sn', models.CharField(max_length=50, verbose_name='换新序列号')),
                ('send_order_id', models.CharField(max_length=50, verbose_name='发货订单编号')),
                ('appraisal', models.CharField(max_length=200, verbose_name='保修结束语')),
                ('shop', models.CharField(max_length=60, verbose_name='关联店铺')),
                ('date_of_purchase', models.DateTimeField(verbose_name='购买时间')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('creator', models.CharField(max_length=50, verbose_name='创建人')),
                ('handle_time', models.DateTimeField(verbose_name='审核时间')),
                ('handler_name', models.CharField(max_length=50, verbose_name='审核人')),
                ('finish_time', models.DateTimeField(verbose_name='保修完成时间')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='保修金额')),
                ('quantity', models.IntegerField(verbose_name='保修数量')),
                ('last_handle_time', models.DateTimeField(verbose_name='最后修改时间')),
                ('buyer_nick', models.CharField(max_length=200, verbose_name='客户网名')),
                ('sender_name', models.CharField(max_length=100, verbose_name='寄件客户姓名')),
                ('sender_mobile', models.CharField(max_length=50, verbose_name='寄件客户手机')),
                ('sender_area', models.CharField(max_length=50, verbose_name='寄件客户省市县')),
                ('sender_address', models.CharField(max_length=50, verbose_name='寄件客户地址')),
                ('send_logistics_company', models.CharField(max_length=50, verbose_name='收件物流公司')),
                ('send_logistics_no', models.CharField(max_length=50, verbose_name='收件物流单号')),
                ('send_memory', models.CharField(max_length=200, verbose_name='收件备注')),
                ('return_name', models.CharField(max_length=50, verbose_name='寄回客户姓名')),
                ('return_mobile', models.CharField(max_length=50, verbose_name='寄回客户手机')),
                ('return_area', models.CharField(max_length=50, verbose_name='寄回省市区')),
                ('return_address', models.CharField(max_length=50, verbose_name='寄回地址')),
                ('return_logistics_company', models.CharField(max_length=50, verbose_name='寄件指定物流公司')),
                ('return_logistics_no', models.CharField(max_length=50, verbose_name='寄件物流单号')),
                ('return_memory', models.CharField(max_length=200, verbose_name='寄件备注')),
                ('goods_id', models.CharField(max_length=60, verbose_name='保修货品商家编码')),
                ('goods_name', models.CharField(max_length=150, verbose_name='保修货品名称')),
                ('goods_abbreviation', models.CharField(max_length=60, verbose_name='保修货品简称')),
                ('description', models.CharField(max_length=500, verbose_name='故障描述')),
                ('is_guarantee', models.CharField(max_length=50, verbose_name='是否在保修期内')),
                ('repeat_tag', models.CharField(choices=[(0, '正常'), (1, '未处理'), (2, '产品'), (3, '维修')], default=0, max_length=30, verbose_name='重复维修标记')),
                ('tocustomer_status', models.CharField(choices=[(0, '未审核'), (1, '已处理'), (2, '无效'), (3, '异常')], default=0, max_length=30, verbose_name='更新客户信息状态')),
                ('toproduct_status', models.CharField(choices=[(0, '未审核'), (1, '已处理'), (2, '无效'), (3, '异常')], default=0, max_length=30, verbose_name='更新产品信息状态')),
            ],
            options={
                'verbose_name': '保修单',
                'verbose_name_plural': '保修单',
            },
        ),
    ]
