# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-30 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCalcInfo',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-M-保修单计算',
                'verbose_name_plural': 'CRM-M-保修单计算',
                'proxy': True,
                'indexes': [],
            },
            bases=('maintenance.maintenancehandlinginfo',),
        ),
        migrations.CreateModel(
            name='MaintenanceJudgeInfo',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-M-保修单判责',
                'verbose_name_plural': 'CRM-M-保修单判责',
                'proxy': True,
                'indexes': [],
            },
            bases=('maintenance.maintenancehandlinginfo',),
        ),
        migrations.CreateModel(
            name='MaintenanceSubmitInfo',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-M-未递原始单',
                'verbose_name_plural': 'CRM-M-未递原始单',
                'proxy': True,
                'indexes': [],
            },
            bases=('maintenance.maintenanceinfo',),
        ),
        migrations.AlterModelOptions(
            name='maintenanceinfo',
            options={'verbose_name': 'CRM-M-原始单查询', 'verbose_name_plural': 'CRM-M-原始单查询'},
        ),
        migrations.AlterModelOptions(
            name='maintenancesummary',
            options={'verbose_name': 'CRM-M-保修统计表', 'verbose_name_plural': 'CRM-M-保修统计表'},
        ),
        migrations.RemoveField(
            model_name='maintenancesummary',
            name='repeat_count',
        ),
        migrations.AddField(
            model_name='maintenancesummary',
            name='repeat_found',
            field=models.IntegerField(default=0, verbose_name='当天发现30天二次维修量'),
        ),
        migrations.AddField(
            model_name='maintenancesummary',
            name='repeat_today',
            field=models.IntegerField(default=0, verbose_name='当天二次维修量'),
        ),
    ]
