# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-02 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceinfo',
            name='charge_amount',
            field=models.IntegerField(default=0, verbose_name='收费金额'),
        ),
        migrations.AddField(
            model_name='maintenanceinfo',
            name='charge_memory',
            field=models.TextField(default='', verbose_name='收费说明'),
        ),
        migrations.AddField(
            model_name='maintenanceinfo',
            name='charge_status',
            field=models.CharField(default='', max_length=30, verbose_name='收费状态'),
        ),
    ]
