# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-05 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20190305_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenanceinfo',
            old_name='toproduct_status',
            new_name='towork_status',
        ),
        migrations.RemoveField(
            model_name='maintenancehandlinginfo',
            name='repeat_time_range',
        ),
        migrations.AddField(
            model_name='maintenancehandlinginfo',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='maintenancehandlinginfo',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='区县'),
        ),
        migrations.AddField(
            model_name='maintenancehandlinginfo',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='省份'),
        ),
    ]
