# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-02 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20190302_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceinfo',
            name='return_address',
            field=models.CharField(max_length=200, verbose_name='寄回地址'),
        ),
        migrations.AlterField(
            model_name='maintenanceinfo',
            name='sender_address',
            field=models.CharField(max_length=200, verbose_name='寄件客户地址'),
        ),
    ]
