# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-02 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20190930_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancesummary',
            name='thirty_day_count',
        ),
    ]
