# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-06 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_auto_20190305_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancehandlinginfo',
            name='finish_date',
            field=models.CharField(max_length=20, verbose_name='保修完成日期'),
        ),
        migrations.AlterField(
            model_name='maintenancehandlinginfo',
            name='finish_month',
            field=models.CharField(max_length=20, verbose_name='保修完成月度'),
        ),
        migrations.AlterField(
            model_name='maintenancehandlinginfo',
            name='finish_year',
            field=models.CharField(max_length=20, verbose_name='保修完成年度'),
        ),
    ]
