# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-02 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_auto_20190302_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenanceinfo',
            old_name='date_of_purchase',
            new_name='purchase_time',
        ),
    ]
