# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-06 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_auto_20190306_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceinfo',
            name='goods_type',
            field=models.CharField(max_length=60, null=True, verbose_name='保修货品型号'),
        ),
    ]
