# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-06 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_maintenanceinfo_goods_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceinfo',
            name='goods_type',
        ),
        migrations.AddField(
            model_name='maintenancehandlinginfo',
            name='goods_type',
            field=models.CharField(max_length=60, null=True, verbose_name='保修货品型号'),
        ),
    ]
