# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-08 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_auto_20190308_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancehandlinginfo',
            name='finish_month',
            field=models.CharField(max_length=50, verbose_name='保修完成月度'),
        ),
        migrations.AlterField(
            model_name='maintenancehandlinginfo',
            name='finish_year',
            field=models.CharField(max_length=50, verbose_name='保修完成年度'),
        ),
    ]
