# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-15 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_auto_20190315_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancesummary',
            old_name='finish_date',
            new_name='finish_time',
        ),
    ]
