# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-23 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_auto_20190315_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancehandlinginfo',
            options={'verbose_name': '保修单明细', 'verbose_name_plural': '保修单明细'},
        ),
        migrations.AlterModelOptions(
            name='maintenanceinfo',
            options={'verbose_name': '原始保修单', 'verbose_name_plural': '原始保修单'},
        ),
        migrations.AlterModelOptions(
            name='maintenancesummary',
            options={'verbose_name': '保修单汇总', 'verbose_name_plural': '保修单汇总'},
        ),
    ]
