# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-10 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0016_auto_20190410_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancehandlinginfo',
            name='handling_status',
            field=models.SmallIntegerField(choices=[(0, '未审核'), (1, '已处理'), (2, '无效'), (3, '异常')], default=0, verbose_name='操作状态'),
        ),
        migrations.AlterField(
            model_name='maintenancehandlinginfo',
            name='repeat_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '未处理'), (2, '产品'), (3, '维修'), (4, '客服')], default=0, verbose_name='重复维修标记'),
        ),
    ]
