# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-10 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0018_auto_20190410_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancehandlinginfo',
            name='completer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='处理登记人'),
        ),
        migrations.AlterField(
            model_name='maintenancehandlinginfo',
            name='machine_sn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='序列号'),
        ),
        migrations.AlterField(
            model_name='maintenanceinfo',
            name='machine_sn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='序列号'),
        ),
        migrations.AlterField(
            model_name='maintenanceinfo',
            name='new_machine_sn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='换新序列号'),
        ),
    ]
