# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-09 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0021_maintenancehandlinginfo_tomachinesn_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancehandlinginfo',
            name='reason_analysis',
            field=models.CharField(max_length=200, null=True, verbose_name='原因分析'),
        ),
    ]
