# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-10 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0023_remove_maintenancehandlinginfo_reason_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancehandlinginfo',
            name='maintenance_order_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='保修单号'),
        ),
    ]
