# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-28 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('stockin_id', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='入库单号')),
                ('source_order_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='来源单号')),
                ('status', models.IntegerField(choices=[(0, '已取消'), (1, '未处理'), (2, '异常'), (3, '已入库')], default=1, verbose_name='状态')),
                ('category', models.IntegerField(choices=[(0, '质检入库'), (1, '采购入库')], default=0, verbose_name='入库单类型')),
                ('batch_num', models.CharField(blank=True, max_length=30, null=True, verbose_name='批次号')),
                ('planorder_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='采购单号')),
                ('goods_name', models.CharField(max_length=60, verbose_name='货品名称')),
                ('goods_id', models.CharField(max_length=30, verbose_name='货品编码')),
                ('quantity', models.IntegerField(verbose_name='入库数量')),
            ],
            options={
                'verbose_name': 'WMS-I-入库单',
                'verbose_name_plural': 'WMS-I-入库单',
                'db_table': 'wms_stk_stockin',
            },
        ),
    ]
