# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-27 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        ('manuorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('stockin_id', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='入库单号')),
                ('source_order_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='来源单号')),
                ('order_status', models.IntegerField(choices=[(0, '已取消'), (1, '未处理'), (2, '已入库'), (3, '异常')], default=1, verbose_name='状态')),
                ('category', models.IntegerField(choices=[(0, '质检入库'), (1, '采购入库')], default=0, verbose_name='入库单类型')),
                ('planorder_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='采购单号')),
                ('goods_name', models.CharField(max_length=60, verbose_name='货品名称')),
                ('goods_id', models.CharField(max_length=30, verbose_name='货品编码')),
                ('quantity', models.IntegerField(verbose_name='入库数量')),
                ('memorandum', models.CharField(blank=True, max_length=300, null=True, verbose_name='备注')),
                ('error_tag', models.SmallIntegerField(choices=[(0, '正常'), (1, '入库单保存错误'), (2, '货品错误')], default=0, verbose_name='错误原因')),
                ('batch_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manuorder.ManuOrderInfo', verbose_name='批次号')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseInfo', verbose_name='仓库名称')),
            ],
            options={
                'verbose_name': 'WMS-I-入库单',
                'verbose_name_plural': 'WMS-I-入库单',
                'db_table': 'wms_stk_stockin',
            },
        ),
        migrations.CreateModel(
            name='StockInPenddingInfo',
            fields=[
            ],
            options={
                'verbose_name': 'WMS-I-未审核入库单',
                'verbose_name_plural': 'WMS-I-未审核入库单',
                'proxy': True,
                'indexes': [],
            },
            bases=('stockin.stockininfo',),
        ),
    ]
