# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-28 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stockin', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockininfo',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseInfo', verbose_name='仓库名称'),
        ),
        migrations.CreateModel(
            name='StockInPenddingInfo',
            fields=[
            ],
            options={
                'verbose_name': 'WMS-I-未审核入库单',
                'verbose_name_plural': 'WMS-I-未审核入库单',
                'proxy': True,
                'indexes': [],
            },
            bases=('stockin.stockininfo',),
        ),
    ]
