# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-26 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockininfo',
            name='error_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '入库单保存错误'), (2, '货品错误')], default=0, verbose_name='错误原因'),
        ),
        migrations.AddField(
            model_name='stockininfo',
            name='memorandum',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='stockininfo',
            name='batch_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manuorder.ManuOrderInfo', verbose_name='批次号'),
        ),
    ]
