# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-18 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('district', models.CharField(max_length=100, verbose_name='区县')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.CityInfo', verbose_name='城市')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.NationalityInfo', verbose_name='国家')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.ProvinceInfo', verbose_name='省份')),
            ],
            options={
                'verbose_name': 'UTL-G-区县',
                'verbose_name_plural': 'UTL-G-区县',
                'db_table': 'util_geo_district',
            },
        ),
    ]
