# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-06 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationalityinfo',
            options={'verbose_name': '国家及地区', 'verbose_name_plural': '国家及地区'},
        ),
        migrations.AlterField(
            model_name='nationalityinfo',
            name='nationality',
            field=models.CharField(max_length=100, unique=True, verbose_name='国家及地区'),
        ),
        migrations.AlterModelTable(
            name='cityinfo',
            table='util_geo_city',
        ),
        migrations.AlterModelTable(
            name='nationalityinfo',
            table='util_geo_nationality',
        ),
        migrations.AlterModelTable(
            name='provinceinfo',
            table='util_geo_province',
        ),
    ]
