# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-06 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_auto_20190606_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityinfo',
            name='area_code',
            field=models.CharField(max_length=10, verbose_name='电话区号'),
        ),
    ]
