# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-24 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0005_auto_20190624_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchOrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('planorder_id', models.CharField(max_length=30, unique=True, verbose_name='计划采购单号')),
                ('batch_num', models.CharField(max_length=30, unique=True, verbose_name='批次号')),
                ('goods_id', models.CharField(max_length=30, verbose_name='货品编码')),
                ('goods_name', models.CharField(max_length=60, verbose_name='货品名称')),
                ('quantity', models.IntegerField(verbose_name='货品数量')),
                ('estimated_time', models.DateTimeField(verbose_name='期望到货时间')),
                ('status', models.IntegerField(choices=[(0, '未处理'), (1, '已确认'), (2, '已递交'), (3, '取消')], default=0, verbose_name='批次单状态')),
                ('manufactory', models.CharField(max_length=30, verbose_name='工厂名称')),
            ],
            options={
                'verbose_name': '批次单',
                'verbose_name_plural': '批次单',
                'db_table': 'oms_po_batchorder',
            },
        ),
        migrations.CreateModel(
            name='CusPartOrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('planorder_id', models.CharField(max_length=30, unique=True, verbose_name='客供计划单采购单号')),
                ('quantity', models.IntegerField(verbose_name='采购数量')),
                ('estimated_time', models.DateTimeField(verbose_name='期望到货时间')),
                ('status', models.IntegerField(choices=[(0, '未处理'), (1, '已确认'), (2, '已递交'), (3, '取消')], default=0, verbose_name='采购单状态')),
                ('category', models.IntegerField(choices=[(0, '常规'), (1, '加急'), (2, '大促')], default=0, verbose_name='采购单类别')),
                ('order_attribute', models.IntegerField(choices=[(0, '配件采购单'), (1, '客供件采购单')], default=0, verbose_name='采购单类别')),
                ('goods_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.PartInfo', verbose_name='配件名称')),
            ],
            options={
                'verbose_name': '非整机采购申请单',
                'verbose_name_plural': '非整机采购申请单',
                'db_table': 'oms_po_csorder',
            },
        ),
        migrations.CreateModel(
            name='CusRequisitionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('planorder_id', models.CharField(max_length=30, unique=True, verbose_name='计划采购单号')),
                ('batch_num', models.CharField(max_length=30, unique=True, verbose_name='批次号')),
                ('goods_id', models.CharField(max_length=30, verbose_name='货品编码')),
                ('goods_name', models.CharField(max_length=60, verbose_name='货品名称')),
                ('quantity', models.IntegerField(verbose_name='货品数量')),
                ('estimated_time', models.DateTimeField(verbose_name='期望到货时间')),
                ('status', models.IntegerField(choices=[(0, '未处理'), (1, '已确认'), (2, '已递交'), (3, '取消')], default=0, verbose_name='需求单单状态')),
                ('manufactory', models.CharField(max_length=30, verbose_name='工厂名称')),
            ],
            options={
                'verbose_name': '需求单',
                'verbose_name_plural': '需求单',
                'db_table': 'oms_po_crorder',
            },
        ),
        migrations.CreateModel(
            name='PlanOrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('planorder_id', models.CharField(max_length=50, unique=True, verbose_name='计划采购单号')),
                ('quantity', models.IntegerField(verbose_name='订单数量')),
                ('estimated_time', models.DateTimeField(verbose_name='期望到货时间')),
                ('order_status', models.IntegerField(choices=[(0, '未处理'), (1, '已确认'), (2, '已递交'), (3, '取消')], default=0, verbose_name='计划采购单状态')),
                ('category', models.IntegerField(choices=[(0, '常规'), (1, '加急'), (2, '大促')], default=0, verbose_name='订单类型')),
                ('goods_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.MachineInfo', verbose_name='机器名称')),
            ],
            options={
                'verbose_name': '整机采购申请单',
                'verbose_name_plural': '整机采购申请单',
                'db_table': 'oms_po_order',
            },
        ),
    ]
