# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-27 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriPlanOrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('planorder_id', models.CharField(max_length=30, unique=True, verbose_name='计划采购单号')),
                ('goods_name', models.CharField(db_index=True, max_length=30, verbose_name='机器名称')),
                ('quantity', models.IntegerField(verbose_name='订单数量')),
                ('estimated_time', models.DateTimeField(verbose_name='期望到货时间')),
                ('order_status', models.IntegerField(choices=[(0, '取消'), (1, '未处理'), (2, '已递交')], db_index=True, default=1, verbose_name='计划采购单状态')),
                ('category', models.IntegerField(choices=[(0, '常规'), (1, '加急'), (2, '大促')], default=0, verbose_name='订单类型')),
                ('tag_sign', models.SmallIntegerField(choices=[(0, '正常'), (1, '重复递交'), (2, '有已经取消的计划单'), (3, '货品非法'), (4, '保存单据出错')], default=0, verbose_name='错误原因')),
            ],
            options={
                'verbose_name': 'OMS-P-原始整机计划单',
                'verbose_name_plural': 'OMS-P-原始整机计划单',
                'db_table': 'oms_po_oriorder',
            },
        ),
        migrations.CreateModel(
            name='PlanOrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('planorder_id', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='计划采购单号')),
                ('quantity', models.IntegerField(verbose_name='订单数量')),
                ('estimated_time', models.DateTimeField(verbose_name='期望到货时间')),
                ('order_status', models.IntegerField(choices=[(0, '取消'), (1, '未处理'), (2, '待确认'), (3, '已递交'), (4, '异常')], default=1, verbose_name='计划采购单状态')),
                ('category', models.IntegerField(choices=[(0, '常规'), (1, '加急'), (2, '大促')], default=0, verbose_name='订单类型')),
                ('tag_sign', models.SmallIntegerField(choices=[(0, '正常'), (1, '重复递交'), (2, '系统错误'), (3, '货品未关联工厂'), (4, '保存单据出错')], default=0, verbose_name='错误原因')),
                ('goods_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.MachineInfo', verbose_name='机器名称')),
            ],
            options={
                'verbose_name': 'OMS-P-整机计划单',
                'verbose_name_plural': 'OMS-P-整机计划单',
                'db_table': 'oms_po_order',
            },
        ),
        migrations.CreateModel(
            name='OriPlanOrderSubmitInfo',
            fields=[
            ],
            options={
                'verbose_name': 'OMS-P-原始整机计划单未递交',
                'verbose_name_plural': 'OMS-P-原始整机计划单未递交',
                'proxy': True,
                'indexes': [],
            },
            bases=('planorder.oriplanorderinfo',),
        ),
        migrations.CreateModel(
            name='PlanOrderPenddingInfo',
            fields=[
            ],
            options={
                'verbose_name': 'OMS-P-整机计划单未处理',
                'verbose_name_plural': 'OMS-P-整机计划单未处理',
                'proxy': True,
                'indexes': [],
            },
            bases=('planorder.planorderinfo',),
        ),
        migrations.CreateModel(
            name='PlanOrderSubmitInfo',
            fields=[
            ],
            options={
                'verbose_name': 'OMS-P-整机计划单未递交',
                'verbose_name_plural': 'OMS-P-整机计划单未递交',
                'proxy': True,
                'indexes': [],
            },
            bases=('planorder.planorderinfo',),
        ),
    ]
