# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-28 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanOrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('planorder_id', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='计划采购单号')),
                ('quantity', models.IntegerField(verbose_name='订单数量')),
                ('estimated_time', models.DateTimeField(verbose_name='期望到货时间')),
                ('status', models.IntegerField(choices=[(0, '取消'), (1, '未处理'), (2, '待确认'), (3, '异常'), (4, '已递交')], default=1, verbose_name='计划采购单状态')),
                ('category', models.IntegerField(choices=[(0, '常规'), (1, '加急'), (2, '大促')], default=0, verbose_name='订单类型')),
                ('goods_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.MachineInfo', verbose_name='机器名称')),
            ],
            options={
                'verbose_name': 'OMS-P-整机采购申请单',
                'verbose_name_plural': 'OMS-P-整机采购申请单',
                'db_table': 'oms_po_order',
            },
        ),
        migrations.CreateModel(
            name='PlanOrderPenddingInfo',
            fields=[
            ],
            options={
                'verbose_name': 'OMS-P-未处理计划单',
                'verbose_name_plural': 'OMS-P-未处理计划单',
                'proxy': True,
                'indexes': [],
            },
            bases=('planorder.planorderinfo',),
        ),
        migrations.CreateModel(
            name='PlanOrderSubmitInfo',
            fields=[
            ],
            options={
                'verbose_name': 'OMS-P-未递交计划单',
                'verbose_name_plural': 'OMS-P-未递交计划单',
                'proxy': True,
                'indexes': [],
            },
            bases=('planorder.planorderinfo',),
        ),
    ]
