# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-24 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanOrderPenddingInfo',
            fields=[
            ],
            options={
                'verbose_name': '未处理计划单',
                'verbose_name_plural': '未处理计划单',
                'proxy': True,
                'indexes': [],
            },
            bases=('planorder.planorderinfo',),
        ),
        migrations.CreateModel(
            name='PlanOrderSubmitInfo',
            fields=[
            ],
            options={
                'verbose_name': '未递交计划单',
                'verbose_name_plural': '未递交计划单',
                'proxy': True,
                'indexes': [],
            },
            bases=('planorder.planorderinfo',),
        ),
        migrations.RemoveField(
            model_name='planorderinfo',
            name='order_status',
        ),
        migrations.AddField(
            model_name='planorderinfo',
            name='status',
            field=models.IntegerField(choices=[(0, '未处理'), (1, '待确认'), (2, '已递交'), (3, '取消')], default=0, verbose_name='计划采购单状态'),
        ),
    ]
