# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-19 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planorderinfo',
            options={'verbose_name': 'OMS-P-整机采购计划单', 'verbose_name_plural': 'OMS-P-整机采购计划单'},
        ),
    ]
