# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-25 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planorder', '0002_auto_20190624_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BatchOrderInfo',
        ),
        migrations.AlterField(
            model_name='planorderinfo',
            name='planorder_id',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='计划采购单号'),
        ),
        migrations.AlterField(
            model_name='planorderinfo',
            name='status',
            field=models.IntegerField(choices=[(0, '未处理'), (1, '待确认'), (2, '异常'), (3, '已递交'), (4, '取消')], default=0, verbose_name='计划采购单状态'),
        ),
    ]
