# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-25 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planorder', '0003_auto_20190625_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cusrequisitioninfo',
            name='manufactory',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='工厂名称'),
        ),
    ]
