# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-01 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planorder', '0003_planorderinfo_tag_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planorderinfo',
            name='tag_sign',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '重复递交'), (2, '系统错误'), (3, '货品未关联工厂'), (4, '保存单据出错')], default=0, verbose_name='错误原因'),
        ),
    ]
