# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-25 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planorder', '0004_auto_20190625_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cusrequisitioninfo',
            name='batch_num',
            field=models.CharField(db_index=True, max_length=30, verbose_name='批次号'),
        ),
        migrations.AlterField(
            model_name='cusrequisitioninfo',
            name='planorder_id',
            field=models.CharField(db_index=True, max_length=30, verbose_name='计划采购单号'),
        ),
    ]
