# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-02-14 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planorder', '0005_auto_20200109_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oriplanorderinfo',
            name='tag_sign',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '重复递交'), (2, '有已经取消的计划单'), (3, '货品非法'), (4, '保存单据出错')], default=0, verbose_name='错误原因'),
        ),
    ]
