# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-25 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planorder', '0005_auto_20190625_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='CusRequisitionSubmitInfo',
            fields=[
            ],
            options={
                'verbose_name': '未递交需求单',
                'verbose_name_plural': '未递交需求单',
                'proxy': True,
                'indexes': [],
            },
            bases=('planorder.cusrequisitioninfo',),
        ),
        migrations.AlterField(
            model_name='cusrequisitioninfo',
            name='status',
            field=models.IntegerField(choices=[(0, '未处理'), (1, '异常'), (2, '已递交'), (3, '取消')], default=0, verbose_name='需求单单状态'),
        ),
    ]
