# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-26 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planorder', '0008_auto_20190626_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planorderinfo',
            name='planorder_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='计划采购单号'),
        ),
    ]
