# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-27 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planorder', '0009_auto_20190626_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='cusrequisitioninfo',
            name='cus_requisition_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='需求单号'),
        ),
    ]
