# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-27 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planorder', '0010_cusrequisitioninfo_cus_requisition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cusrequisitioninfo',
            name='manufactory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufactory.ManufactoryInfo', verbose_name='工厂名称'),
        ),
    ]
