# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-27 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planorder', '0011_auto_20190627_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuspartorderinfo',
            name='source_order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planorder.CusRequisitionInfo', verbose_name='来源单号'),
        ),
    ]
