# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-27 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planorder', '0012_cuspartorderinfo_source_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuspartorderinfo',
            name='planorder_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='客供计划单采购单号'),
        ),
    ]
