# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-27 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufactory', '0002_auto_20190627_1401'),
        ('planorder', '0013_auto_20190627_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuspartorderinfo',
            name='manufactory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufactory.ManufactoryInfo', verbose_name='工厂名称'),
        ),
        migrations.AlterField(
            model_name='cuspartorderinfo',
            name='planorder_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='计划采购单号'),
        ),
    ]
