# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-05 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerInfo',
            fields=[
            ],
            options={
                'verbose_name': 'BASE-公司-经销代理',
                'verbose_name_plural': 'BASE-公司-经销代理',
                'proxy': True,
                'indexes': [],
            },
            bases=('company.companyinfo',),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='category',
            field=models.IntegerField(choices=[(0, '小狗体系'), (1, '物流快递'), (2, '仓库存储'), (3, '生产制造'), (4, '经销代理'), (5, '其他类型')], default=1, verbose_name='公司类型'),
        ),
    ]
