# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-28 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManufactoryInfo',
        ),
        migrations.DeleteModel(
            name='WarehouseInfo',
        ),
        migrations.CreateModel(
            name='ManuInfo',
            fields=[
            ],
            options={
                'verbose_name': 'BASE-生产制造',
                'verbose_name_plural': 'BASE-生产制造',
                'proxy': True,
                'indexes': [],
            },
            bases=('company.companyinfo',),
        ),
        migrations.CreateModel(
            name='WareInfo',
            fields=[
            ],
            options={
                'verbose_name': 'BASE-仓库存储',
                'verbose_name_plural': 'BASE-仓库存储',
                'proxy': True,
                'indexes': [],
            },
            bases=('company.companyinfo',),
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'BASE-公司管理', 'verbose_name_plural': 'BASE-公司管理'},
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='company',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='category',
            field=models.IntegerField(choices=[(0, '小狗体系'), (1, '物流快递'), (2, '仓库存储'), (3, '生产制造'), (4, '其他类型')], default=1, verbose_name='公司类型'),
        ),
    ]
