# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-24 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190928_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'BASE-公司-公司管理', 'verbose_name_plural': 'BASE-公司-公司管理'},
        ),
        migrations.AlterModelOptions(
            name='logisticsinfo',
            options={'verbose_name': 'BASE-公司-快递物流', 'verbose_name_plural': 'BASE-公司-快递物流'},
        ),
        migrations.AlterModelOptions(
            name='manuinfo',
            options={'verbose_name': 'BASE-公司-生产制造', 'verbose_name_plural': 'BASE-公司-生产制造'},
        ),
        migrations.AlterModelOptions(
            name='wareinfo',
            options={'verbose_name': 'BASE-公司-仓库存储', 'verbose_name_plural': 'BASE-公司-仓库存储'},
        ),
    ]
