# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-26 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200323_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='spain_invoice',
            field=models.FloatField(blank=True, null=True, verbose_name='普票限额'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='special_invoice',
            field=models.FloatField(blank=True, null=True, verbose_name='专票限额'),
        ),
    ]
