# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-07-08 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20200326_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='discount_rate',
            field=models.FloatField(default=1.0, verbose_name='折扣率'),
        ),
    ]
