# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-28 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufactory', '0001_initial'),
        ('cusrequisition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cusrequisitioninfo',
            name='manufactory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufactory.ManufactoryInfo', verbose_name='工厂名称'),
        ),
        migrations.CreateModel(
            name='CusRequisitionSubmitInfo',
            fields=[
            ],
            options={
                'verbose_name': 'OMS-R-未递交需求单',
                'verbose_name_plural': 'OMS-R-未递交需求单',
                'proxy': True,
                'indexes': [],
            },
            bases=('cusrequisition.cusrequisitioninfo',),
        ),
    ]
