# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-18 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cusrequisition', '0002_auto_20190928_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cusrequisitioninfo',
            name='status',
        ),
        migrations.AddField(
            model_name='cusrequisitioninfo',
            name='order_status',
            field=models.IntegerField(choices=[(0, '已取消'), (1, '未处理'), (2, '已递交'), (3, '异常')], default=1, verbose_name='需求单单状态'),
        ),
        migrations.AlterField(
            model_name='cusrequisitioninfo',
            name='manufactory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.ManuInfo', verbose_name='工厂名称'),
        ),
    ]
