# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-19 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.CompanyInfo', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_manager',
            field=models.IntegerField(choices=[(0, '非管理'), (1, '管理')], default=0, verbose_name='是否管理'),
        ),
    ]
