# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-27 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='platform',
            field=models.SmallIntegerField(blank=True, choices=[(0, '京东'), (1, '淘系')], null=True, verbose_name='平台'),
        ),
    ]
