# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-04-07 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200221_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='category',
            field=models.SmallIntegerField(choices=[(0, '外埠'), (1, '本埠')], default=0, verbose_name='平台'),
        ),
    ]
