# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-04-15 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('users', '0006_userprofile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.DepartmentInfo', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.SmallIntegerField(choices=[(0, '外埠'), (1, '本埠')], default=0, verbose_name='归属'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.CompanyInfo', verbose_name='公司'),
        ),
    ]
