# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-09-14 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200415_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='platform',
            field=models.SmallIntegerField(choices=[(0, '无'), (1, '淘系'), (2, '非淘'), (3, '官方商城'), (4, '呼叫中心')], default=0, verbose_name='平台'),
        ),
    ]
