# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-18 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftInTalkInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('receiver', models.CharField(max_length=50, verbose_name='收货人')),
                ('mobile', models.CharField(max_length=50, verbose_name='电话')),
                ('address', models.CharField(max_length=250, verbose_name='地址')),
                ('goods_name', models.CharField(max_length=50, verbose_name='赠品名称')),
                ('quantity', models.SmallIntegerField(verbose_name='赠品数量')),
                ('servicer', models.CharField(max_length=50, verbose_name='客服')),
                ('nickname', models.CharField(max_length=50, verbose_name='用户网名')),
                ('order_id', models.CharField(max_length=50, verbose_name='订单号')),
                ('order_status', models.IntegerField(choices=[(0, '已取消'), (1, '未处理'), (2, '已完成')], default=1, verbose_name='赠品单状态')),
                ('submit_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作人')),
            ],
            options={
                'verbose_name': 'ASS-GT-赠品订单提取查询',
                'verbose_name_plural': 'ASS-GT-赠品订单提取查询',
                'db_table': 'ass_gt_oriorder',
            },
        ),
        migrations.CreateModel(
            name='GiftOrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('shop', models.CharField(max_length=50, verbose_name='店铺名称')),
                ('nickname', models.CharField(max_length=50, verbose_name='网名')),
                ('receiver', models.CharField(max_length=50, verbose_name='收件人')),
                ('address', models.CharField(max_length=250, verbose_name='地址')),
                ('mobile', models.CharField(max_length=50, verbose_name='手机')),
                ('d_condition', models.CharField(default='款到发货', max_length=20, verbose_name='发货条件')),
                ('discount', models.SmallIntegerField(default=0, verbose_name='优惠金额')),
                ('post_fee', models.SmallIntegerField(default=0, verbose_name='邮费')),
                ('receivable', models.SmallIntegerField(default=0, verbose_name='应收合计')),
                ('goods_price', models.SmallIntegerField(default=0, verbose_name='货品价格')),
                ('total_prices', models.SmallIntegerField(default=0, verbose_name='货品总价')),
                ('goods_id', models.CharField(max_length=50, verbose_name='商家编码')),
                ('goods_name', models.CharField(max_length=50, verbose_name='货品名称')),
                ('quantity', models.SmallIntegerField(verbose_name='货品数量')),
                ('category', models.CharField(default='线下零售', max_length=20, verbose_name='订单类别')),
                ('buyer_remark', models.CharField(default='线下零售', max_length=20, verbose_name='买家备注')),
                ('province', models.CharField(max_length=50, verbose_name='省')),
                ('city', models.CharField(max_length=50, verbose_name='市')),
                ('district', models.CharField(max_length=50, verbose_name='区')),
                ('order_status', models.IntegerField(choices=[(0, '已取消'), (1, '未处理'), (2, '已完成')], default=1, verbose_name='赠品单状态')),
                ('submit_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='处理人')),
            ],
            options={
                'verbose_name': 'ASS-GT-赠品订单查询',
                'verbose_name_plural': 'ASS-GT-赠品订单查询',
                'db_table': 'ass_gt_order',
            },
        ),
        migrations.CreateModel(
            name='GiftInTalkPendding',
            fields=[
            ],
            options={
                'verbose_name': 'ASS-GT-赠品订单提取递交',
                'verbose_name_plural': 'ASS-GT-赠品订单提取递交',
                'proxy': True,
                'indexes': [],
            },
            bases=('giftintalk.giftintalkinfo',),
        ),
        migrations.CreateModel(
            name='GiftOrderPendding',
            fields=[
            ],
            options={
                'verbose_name': 'ASS-GT-赠品订单ERP导入',
                'verbose_name_plural': 'ASS-GT-赠品订单ERP导入',
                'proxy': True,
                'indexes': [],
            },
            bases=('giftintalk.giftorderinfo',),
        ),
    ]
