# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-09-15 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('callcentre', '0001_initial'),
        ('dialog', '0020_dowid'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftImportInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('shop', models.CharField(max_length=60, verbose_name='店铺名称')),
                ('nickname', models.CharField(max_length=50, verbose_name='网名')),
                ('receiver', models.CharField(max_length=50, verbose_name='收件人')),
                ('address', models.CharField(max_length=250, verbose_name='地址')),
                ('mobile', models.CharField(max_length=50, verbose_name='手机')),
                ('d_condition', models.CharField(default='款到发货', max_length=20, verbose_name='发货条件')),
                ('discount', models.SmallIntegerField(default=0, verbose_name='优惠金额')),
                ('post_fee', models.SmallIntegerField(default=0, verbose_name='邮费')),
                ('receivable', models.SmallIntegerField(default=0, verbose_name='应收合计')),
                ('goods_price', models.SmallIntegerField(default=0, verbose_name='货品价格')),
                ('total_prices', models.SmallIntegerField(default=0, verbose_name='货品总价')),
                ('goods_id', models.CharField(max_length=50, verbose_name='商家编码')),
                ('goods_name', models.CharField(max_length=50, verbose_name='货品名称')),
                ('quantity', models.SmallIntegerField(verbose_name='货品数量')),
                ('category', models.CharField(default='线下零售', max_length=20, verbose_name='订单类别')),
                ('buyer_remark', models.CharField(max_length=300, verbose_name='买家备注')),
                ('cs_memoranda', models.CharField(max_length=300, verbose_name='客服备注')),
                ('province', models.CharField(max_length=50, verbose_name='省')),
                ('city', models.CharField(max_length=50, verbose_name='市')),
                ('district', models.CharField(blank=True, max_length=50, null=True, verbose_name='区')),
                ('order_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='订单号')),
                ('order_status', models.IntegerField(choices=[(0, '已取消'), (1, '未处理'), (2, '已完成')], default=1, verbose_name='赠品单状态')),
                ('submit_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='处理人')),
                ('erp_order_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='原始单号')),
            ],
            options={
                'verbose_name': 'ASS-GT-手工ERP导入单据查询',
                'verbose_name_plural': 'ASS-GT-手工ERP导入单据查询',
                'db_table': 'ass_gt_erpimport',
            },
        ),
        migrations.CreateModel(
            name='GiftInTalkInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('cs_information', models.CharField(max_length=300, verbose_name='收件信息')),
                ('goods', models.CharField(max_length=250, verbose_name='赠品信息')),
                ('servicer', models.CharField(max_length=50, verbose_name='客服')),
                ('nickname', models.CharField(db_index=True, max_length=50, verbose_name='用户网名')),
                ('order_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='订单号')),
                ('mistakes', models.IntegerField(blank=True, choices=[(0, '货品名称错误'), (1, '14天内重复订单'), (2, '14天外重复订单'), (3, '收货人，电话，地址不全'), (4, '地址中，二级市出错，请使用标准系统信息'), (5, '网名错误'), (6, '系统出错，请重复提交，无法解决时联系管理员'), (7, '平台出错'), (8, '同名订单'), (9, '手机错误'), (10, '集运仓地址')], null=True, verbose_name='错误信息')),
                ('order_status', models.IntegerField(choices=[(0, '已取消'), (1, '未处理'), (2, '已完成')], default=1, verbose_name='赠品单状态')),
                ('platform', models.SmallIntegerField(choices=[(0, '无'), (1, '淘系'), (2, '京东'), (3, '官方商城'), (4, '呼叫中心')], default=0, verbose_name='平台')),
                ('submit_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作人')),
                ('order_category', models.SmallIntegerField(choices=[(1, '质量问题'), (2, '开箱即损'), (3, '礼品赠品')], default=3, verbose_name='单据类型')),
                ('shop', models.CharField(blank=True, max_length=150, null=True, verbose_name='店铺')),
                ('process_tag', models.SmallIntegerField(choices=[(0, '未处理'), (1, '待核实'), (2, '已确认'), (3, '待清账'), (4, '已处理'), (5, '特殊订单')], default=0, verbose_name='处理标签')),
            ],
            options={
                'verbose_name': 'ASS-GT-手工订单提取查询',
                'verbose_name_plural': 'ASS-GT-手工订单提取查询',
                'db_table': 'ass_gt_oriorder',
            },
        ),
        migrations.CreateModel(
            name='GiftOrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('shop', models.CharField(max_length=60, verbose_name='店铺名称')),
                ('nickname', models.CharField(max_length=50, verbose_name='网名')),
                ('receiver', models.CharField(max_length=50, verbose_name='收件人')),
                ('address', models.CharField(max_length=250, verbose_name='地址')),
                ('mobile', models.CharField(max_length=50, verbose_name='手机')),
                ('d_condition', models.CharField(default='款到发货', max_length=20, verbose_name='发货条件')),
                ('discount', models.SmallIntegerField(default=0, verbose_name='优惠金额')),
                ('post_fee', models.SmallIntegerField(default=0, verbose_name='邮费')),
                ('receivable', models.SmallIntegerField(default=0, verbose_name='应收合计')),
                ('goods_price', models.SmallIntegerField(default=0, verbose_name='货品价格')),
                ('total_prices', models.SmallIntegerField(default=0, verbose_name='货品总价')),
                ('goods_id', models.CharField(max_length=50, verbose_name='商家编码')),
                ('goods_name', models.CharField(max_length=50, verbose_name='货品名称')),
                ('quantity', models.SmallIntegerField(verbose_name='货品数量')),
                ('category', models.CharField(default='线下零售', max_length=20, verbose_name='订单类别')),
                ('buyer_remark', models.CharField(default='线下零售', max_length=300, verbose_name='买家备注')),
                ('cs_memoranda', models.CharField(blank=True, default='线下零售', max_length=300, null=True, verbose_name='客服备注')),
                ('province', models.CharField(max_length=50, verbose_name='省')),
                ('city', models.CharField(max_length=50, verbose_name='市')),
                ('district', models.CharField(blank=True, max_length=50, null=True, verbose_name='区')),
                ('order_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='订单号')),
                ('order_status', models.IntegerField(choices=[(0, '已取消'), (1, '未处理'), (2, '已完成')], default=1, verbose_name='赠品单状态')),
                ('submit_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='处理人')),
                ('order_category', models.SmallIntegerField(choices=[(1, '质量问题'), (2, '开箱即损'), (3, '礼品赠品')], default=3, verbose_name='单据类型')),
            ],
            options={
                'verbose_name': 'ASS-GT-手工预订单查询',
                'verbose_name_plural': 'ASS-GT-手工预订单查询',
                'db_table': 'ass_gt_order',
            },
        ),
        migrations.CreateModel(
            name='OrderCallList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('call_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='callcentre.OriCallLogInfo', verbose_name='400电话')),
                ('gift_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gift_call', to='giftintalk.GiftInTalkInfo', verbose_name='提取单据')),
            ],
            options={
                'verbose_name': '呼叫中心来源',
                'verbose_name_plural': '呼叫中心来源',
                'db_table': 'ass_gt_order_call',
            },
        ),
        migrations.CreateModel(
            name='OrderJDList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('gift_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gift_jd', to='giftintalk.GiftInTalkInfo', verbose_name='提取单据')),
                ('talk_jd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dialog.OriDetailJD', verbose_name='京东对话')),
            ],
            options={
                'verbose_name': '京东订单来源',
                'verbose_name_plural': '京东订单来源',
                'db_table': 'ass_gt_order_jd',
            },
        ),
        migrations.CreateModel(
            name='OrderOWList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('gift_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gift_ow', to='giftintalk.GiftInTalkInfo', verbose_name='提取单据')),
                ('talk_ow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dialog.OriDetailOW', verbose_name='官方商城对话')),
            ],
            options={
                'verbose_name': '官方商城订单来源',
                'verbose_name_plural': '官方商城订单来源',
                'db_table': 'ass_gt_order_ow',
            },
        ),
        migrations.CreateModel(
            name='OrderTBList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('gift_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gift_tb', to='giftintalk.GiftInTalkInfo', verbose_name='提取单据')),
                ('talk_tb', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dialog.OriDetailTB', verbose_name='淘宝对话')),
            ],
            options={
                'verbose_name': '淘宝订单来源',
                'verbose_name_plural': '淘宝订单来源',
                'db_table': 'ass_gt_order_tb',
            },
        ),
        migrations.CreateModel(
            name='GiftImportPendding',
            fields=[
            ],
            options={
                'verbose_name': 'ASS-GT-手工ERP导入单据',
                'verbose_name_plural': 'ASS-GT-手工ERP导入单据',
                'proxy': True,
                'indexes': [],
            },
            bases=('giftintalk.giftimportinfo',),
        ),
        migrations.CreateModel(
            name='GiftInTalkPendding',
            fields=[
            ],
            options={
                'verbose_name': 'ASS-GT-手工订单提取递交',
                'verbose_name_plural': 'ASS-GT-手工订单提取递交',
                'proxy': True,
                'indexes': [],
            },
            bases=('giftintalk.giftintalkinfo',),
        ),
        migrations.CreateModel(
            name='GiftOrderPendding',
            fields=[
            ],
            options={
                'verbose_name': 'ASS-GT-手工预订单处理',
                'verbose_name_plural': 'ASS-GT-手工预订单处理',
                'proxy': True,
                'indexes': [],
            },
            bases=('giftintalk.giftorderinfo',),
        ),
    ]
