# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-01 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftintalk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftintalkinfo',
            name='broken_part',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='故障部位'),
        ),
        migrations.AddField(
            model_name='giftintalkinfo',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='故障描述'),
        ),
        migrations.AddField(
            model_name='giftintalkinfo',
            name='m_sn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='机器序列号'),
        ),
        migrations.AddField(
            model_name='giftorderinfo',
            name='broken_part',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='故障部位'),
        ),
        migrations.AddField(
            model_name='giftorderinfo',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='故障描述'),
        ),
        migrations.AddField(
            model_name='giftorderinfo',
            name='m_sn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='机器序列号'),
        ),
        migrations.AlterField(
            model_name='giftimportinfo',
            name='order_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='giftintalkinfo',
            name='mistakes',
            field=models.IntegerField(blank=True, choices=[(0, '货品名称错误'), (1, '14天内重复订单'), (2, '14天外重复订单'), (3, '收货人，电话，地址不全'), (4, '地址中，二级市出错，请使用标准系统信息'), (5, '网名错误'), (6, '系统出错，请重复提交，无法解决时联系管理员'), (7, '平台出错'), (8, '同名订单'), (9, '手机错误'), (10, '集运仓地址'), (11, '无店铺'), (12, '售后配件需要补全sn、部件和描述')], null=True, verbose_name='错误信息'),
        ),
    ]
