# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-24 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftintalk', '0002_auto_20201113_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriGiftList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('goods_id', models.CharField(db_index=True, max_length=60, verbose_name='货品ID')),
                ('ori_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftintalk.GiftInTalkInfo', verbose_name='原始递交订单')),
            ],
            options={
                'verbose_name': 'ASS-GT-手工原始单列表',
                'verbose_name_plural': 'ASS-GT-手工原始单列表',
                'db_table': 'ass_gt_list_oriorder',
            },
        ),
        migrations.AlterModelOptions(
            name='ordercalllist',
            options={'verbose_name': 'ASS-GT-呼叫中心来源', 'verbose_name_plural': 'ASS-GT-呼叫中心来源'},
        ),
        migrations.AlterModelOptions(
            name='orderjdlist',
            options={'verbose_name': 'ASS-GT-京东订单来源', 'verbose_name_plural': 'ASS-GT-京东订单来源'},
        ),
        migrations.AlterModelOptions(
            name='orderowlist',
            options={'verbose_name': 'ASS-GT-官方商城订单来源', 'verbose_name_plural': 'ASS-GT-官方商城订单来源'},
        ),
        migrations.AlterModelOptions(
            name='ordertblist',
            options={'verbose_name': 'ASS-GT-淘宝订单来源', 'verbose_name_plural': 'ASS-GT-淘宝订单来源'},
        ),
        migrations.AlterUniqueTogether(
            name='origiftlist',
            unique_together=set([('ori_order', 'goods_id')]),
        ),
    ]
