# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-24 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftintalk', '0002_auto_20191020_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftintalkinfo',
            name='mistakes',
            field=models.IntegerField(blank=True, choices=[(0, '货品名称错误'), (1, '订单重复'), (2, '订单号错误'), (3, '收货人，电话，地址不全'), (4, '地址中，二级市出错'), (5, '系统出错，请重复提交，无法解决时联系管理员')], null=True, verbose_name='错误信息'),
        ),
    ]
