# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-24 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftintalk', '0003_giftintalkinfo_mistakes'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftimportinfo',
            name='cs_memoranda',
            field=models.CharField(default='线下零售', max_length=300, verbose_name='客服备注'),
        ),
        migrations.AddField(
            model_name='giftorderinfo',
            name='cs_memoranda',
            field=models.CharField(default='线下零售', max_length=300, verbose_name='客服备注'),
        ),
        migrations.AlterField(
            model_name='giftimportinfo',
            name='buyer_remark',
            field=models.CharField(default='线下零售', max_length=300, verbose_name='买家留言'),
        ),
        migrations.AlterField(
            model_name='giftorderinfo',
            name='buyer_remark',
            field=models.CharField(default='线下零售', max_length=300, verbose_name='买家留言'),
        ),
    ]
