# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-24 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftintalk', '0004_auto_20191024_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftintalkinfo',
            name='mistakes',
            field=models.IntegerField(blank=True, choices=[(0, '货品名称错误'), (1, '订单号错误'), (2, '订单重复'), (3, '收货人，电话，地址不全'), (4, '地址中，二级市出错'), (5, '系统出错，请重复提交，无法解决时联系管理员')], null=True, verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='giftorderinfo',
            name='cs_memoranda',
            field=models.CharField(blank=True, default='线下零售', max_length=300, null=True, verbose_name='客服备注'),
        ),
    ]
