# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-02 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftintalk', '0004_auto_20191128_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftintalkinfo',
            name='order_category',
            field=models.SmallIntegerField(choices=[(1, '质量问题'), (2, '开箱即损'), (3, '礼品赠品')], default=3, verbose_name='单据类型'),
        ),
        migrations.AddField(
            model_name='giftorderinfo',
            name='order_category',
            field=models.SmallIntegerField(choices=[(1, '质量问题'), (2, '开箱即损'), (3, '礼品赠品')], default=3, verbose_name='单据类型'),
        ),
        migrations.AlterField(
            model_name='giftimportinfo',
            name='shop',
            field=models.SmallIntegerField(choices=[(0, '无'), (1, '小狗电器旗舰店'), (2, '小狗京东自营')], verbose_name='店铺名称'),
        ),
    ]
