# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-04 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftintalk', '0005_auto_20191202_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftInTalkRepeat',
            fields=[
            ],
            options={
                'verbose_name': 'ASS-GT-赠品订单提取重复订单罗列',
                'verbose_name_plural': 'ASS-GT-赠品订单提取重复订单罗列',
                'proxy': True,
                'indexes': [],
            },
            bases=('giftintalk.giftintalkinfo',),
        ),
        migrations.AlterField(
            model_name='giftintalkinfo',
            name='mistakes',
            field=models.IntegerField(blank=True, choices=[(0, '货品名称错误'), (1, '14天内重复订单'), (2, '14天外重复订单'), (3, '收货人，电话，地址不全'), (4, '地址中，二级市出错，请使用京东系统信息'), (5, '网名错误'), (6, '系统出错，请重复提交，无法解决时联系管理员')], null=True, verbose_name='错误信息'),
        ),
    ]
