# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-26 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftintalk', '0005_auto_20191024_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftimportinfo',
            name='erp_order_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='原始单号'),
        ),
        migrations.AlterField(
            model_name='giftimportinfo',
            name='buyer_remark',
            field=models.CharField(max_length=300, verbose_name='买家备注'),
        ),
        migrations.AlterField(
            model_name='giftimportinfo',
            name='cs_memoranda',
            field=models.CharField(max_length=300, verbose_name='客服备注'),
        ),
        migrations.AlterField(
            model_name='giftintalkinfo',
            name='mistakes',
            field=models.IntegerField(blank=True, choices=[(0, '货品名称错误'), (1, '订单号错误'), (2, '订单重复'), (3, '收货人，电话，地址不全'), (4, '地址中，二级市出错，请使用京东系统信息'), (5, '网名错误'), (6, '系统出错，请重复提交，无法解决时联系管理员')], null=True, verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='giftorderinfo',
            name='buyer_remark',
            field=models.CharField(default='线下零售', max_length=300, verbose_name='买家备注'),
        ),
    ]
