# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-04 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftintalk', '0006_auto_20191204_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftintalkinfo',
            name='nickname',
            field=models.CharField(db_index=True, max_length=50, verbose_name='用户网名'),
        ),
    ]
