# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-26 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftintalk', '0006_auto_20191026_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftimportinfo',
            name='erp_order_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='原始单号'),
        ),
    ]
