# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-05-18 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftintalk', '0007_auto_20191204_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftintalkinfo',
            name='shop',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='店铺'),
        ),
    ]
