# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-05-18 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftintalk', '0008_giftintalkinfo_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftorderinfo',
            name='shop',
            field=models.CharField(max_length=60, verbose_name='店铺名称'),
        ),
    ]
