# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-05-20 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftintalk', '0009_auto_20200518_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftimportinfo',
            name='shop',
            field=models.CharField(max_length=60, verbose_name='店铺名称'),
        ),
    ]
