# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-05-27 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftintalk', '0010_auto_20200520_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftintalkinfo',
            name='mistakes',
            field=models.IntegerField(blank=True, choices=[(0, '货品名称错误'), (1, '14天内重复订单'), (2, '14天外重复订单'), (3, '收货人，电话，地址不全'), (4, '地址中，二级市出错，请使用京东系统信息'), (5, '网名错误'), (6, '系统出错，请重复提交，无法解决时联系管理员'), (7, '平台出错')], null=True, verbose_name='错误信息'),
        ),
    ]
