# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-06-04 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftintalk', '0012_auto_20200604_0914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiftInTalkRepeat',
        ),
    ]
