# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-06-13 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0014_oridetailjd_category'),
        ('giftintalk', '0013_delete_giftintalkrepeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftintalkinfo',
            name='dialog_detialjd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dialog.OriDetailJD', verbose_name='京东来源ID'),
        ),
        migrations.AddField(
            model_name='giftintalkinfo',
            name='dialog_detialtb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dialog.OriDetailTB', verbose_name='淘宝来源ID'),
        ),
        migrations.AlterField(
            model_name='giftintalkinfo',
            name='mistakes',
            field=models.IntegerField(blank=True, choices=[(0, '货品名称错误'), (1, '14天内重复订单'), (2, '14天外重复订单'), (3, '收货人，电话，地址不全'), (4, '地址中，二级市出错，请使用京东系统信息'), (5, '网名错误'), (6, '系统出错，请重复提交，无法解决时联系管理员'), (7, '平台出错'), (8, '同名订单')], null=True, verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='giftintalkinfo',
            name='platform',
            field=models.SmallIntegerField(choices=[(0, '无'), (1, '淘系'), (2, '京东')], default=0, verbose_name='平台'),
        ),
    ]
