# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-06-13 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftintalk', '0014_auto_20200613_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftintalkinfo',
            name='dialog_detialjd',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dialog.OriDetailJD', verbose_name='京东来源ID'),
        ),
        migrations.AlterField(
            model_name='giftintalkinfo',
            name='dialog_detialtb',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dialog.OriDetailTB', verbose_name='淘宝来源ID'),
        ),
    ]
