# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-06-16 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0014_oridetailjd_category'),
        ('giftintalk', '0016_auto_20200616_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderJDList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('gift_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gift_jd', to='giftintalk.GiftInTalkInfo', verbose_name='提取单据')),
                ('talk_tb', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dialog.OriDetailJD', verbose_name='京东对话')),
            ],
            options={
                'verbose_name': '京东订单来源',
                'verbose_name_plural': '京东订单来源',
                'db_table': 'ass_gt_order_jd',
            },
        ),
        migrations.CreateModel(
            name='OrderTBList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('gift_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gift_tb', to='giftintalk.GiftInTalkInfo', verbose_name='提取单据')),
                ('talk_tb', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dialog.OriDetailTB', verbose_name='淘宝对话')),
            ],
            options={
                'verbose_name': '淘宝订单来源',
                'verbose_name_plural': '淘宝订单来源',
                'db_table': 'ass_gt_order_tb',
            },
        ),
    ]
