# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-06-16 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftintalk', '0017_orderjdlist_ordertblist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderjdlist',
            old_name='talk_tb',
            new_name='talk_jd',
        ),
    ]
