# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-08-08 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftintalk', '0020_orderowlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderowlist',
            old_name='talk_jd',
            new_name='talk_ow',
        ),
    ]
