# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-08-08 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftintalk', '0021_auto_20200808_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftintalkinfo',
            name='platform',
            field=models.SmallIntegerField(choices=[(0, '无'), (1, '淘系'), (2, '京东'), (3, '官方商城')], default=0, verbose_name='平台'),
        ),
    ]
