# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-20 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_auto_20190720_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('platform', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='平台名称')),
                ('status', models.IntegerField(choices=[(0, '已取消'), (1, '正常')], default=1, verbose_name='平台状态')),
            ],
            options={
                'verbose_name': 'BASE-平台类型',
                'verbose_name_plural': 'BASE-平台类型',
                'db_table': 'base_platform',
            },
        ),
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('shop_name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='店铺名')),
                ('group_name', models.CharField(max_length=30, verbose_name='店铺分组')),
                ('status', models.IntegerField(choices=[(0, '已取消'), (1, '正常')], default=1, verbose_name='店铺状态')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.CompanyInfo', verbose_name='公司')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.PlatformInfo', verbose_name='平台')),
            ],
            options={
                'verbose_name': 'BASE-店铺',
                'verbose_name_plural': 'BASE-店铺',
                'db_table': 'base_shop',
            },
        ),
    ]
