# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-24 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinfo',
            name='shop_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='店铺ID'),
        ),
    ]
