# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-04-01 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platforminfo',
            name='cateory',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='类型'),
        ),
    ]
