# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-04-01 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200401_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platforminfo',
            old_name='cateory',
            new_name='category',
        ),
    ]
