# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-27 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('information', models.TextField(max_length=600, verbose_name='初始问题信息')),
                ('submit_time', models.DateTimeField(blank=True, null=True, verbose_name='客服提交时间')),
                ('servicer', models.CharField(blank=True, max_length=60, null=True, verbose_name='客服')),
                ('services_interval', models.IntegerField(blank=True, null=True, verbose_name='客服处理间隔(分钟)')),
                ('servicer_feedback', models.TextField(blank=True, null=True, verbose_name='客服反馈')),
                ('handler', models.CharField(blank=True, max_length=30, null=True, verbose_name='组长处理人')),
                ('handle_time', models.DateTimeField(blank=True, null=True, verbose_name='组长处理时间')),
                ('process_interval', models.IntegerField(blank=True, null=True, verbose_name='组长处理间隔(分钟)')),
                ('feedback', models.TextField(blank=True, max_length=900, null=True, verbose_name='反馈内容')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('order_status', models.SmallIntegerField(choices=[(0, '已被取消'), (1, '未递交'), (2, '工单在理'), (3, '终审未理'), (4, '工单完结')], default=1, verbose_name='工单状态')),
                ('category', models.SmallIntegerField(choices=[(0, '产品'), (1, '业务'), (2, '权限'), (3, '其他')], verbose_name='工单类型')),
                ('process_tag', models.SmallIntegerField(choices=[(0, '未分类'), (1, '待核实'), (2, '待审批'), (3, '已解决')], default=0, verbose_name='处理标签')),
                ('mistake_tag', models.SmallIntegerField(choices=[(0, '正常'), (1, '反馈信息为空'), (2, '驳回'), (3, '没有确认解决'), (4, '平台错误')], default=0, verbose_name='异常原因')),
                ('emergency_tag', models.SmallIntegerField(choices=[(0, '常规'), (1, '紧急'), (2, '要命')], default=0, verbose_name='紧急程度')),
                ('platform', models.SmallIntegerField(choices=[(0, '无'), (1, '淘系'), (2, '非淘')], default=0, verbose_name='平台')),
            ],
            options={
                'verbose_name': 'EXT-求助工单-查询',
                'verbose_name_plural': 'EXT-求助工单-查询',
                'db_table': 'ext_workorderemergency_order',
            },
        ),
        migrations.CreateModel(
            name='WOCheck',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-求助工单-审核',
                'verbose_name_plural': 'EXT-求助工单-审核',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorderemergency.workorder',),
        ),
        migrations.CreateModel(
            name='WOCreate',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-求助工单-创建',
                'verbose_name_plural': 'EXT-求助工单-创建',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorderemergency.workorder',),
        ),
        migrations.CreateModel(
            name='WOFinish',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-求助工单-终审',
                'verbose_name_plural': 'EXT-求助工单-终审',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorderemergency.workorder',),
        ),
    ]
