# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-06-29 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderemergency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='platform',
            field=models.SmallIntegerField(choices=[(0, '无'), (1, '淘系'), (2, '非淘')], default=0, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '反馈信息为空'), (2, '驳回'), (3, '没有确认解决'), (4, '平台错误')], default=0, verbose_name='异常原因'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='process_tag',
            field=models.SmallIntegerField(choices=[(0, '未分类'), (1, '待核实'), (2, '待审批'), (3, '已解决')], default=0, verbose_name='处理标签'),
        ),
    ]
