# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-09-22 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dialog', '0021_auto_20200922_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchCompensation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('order_id', models.CharField(max_length=60, verbose_name='批次单号')),
                ('amount', models.FloatField(verbose_name='补偿总金额')),
                ('quantity', models.IntegerField(verbose_name='补偿单数量')),
                ('order_status', models.IntegerField(choices=[(0, '已取消'), (1, '未处理'), (2, '已完成')], default=1, verbose_name='单据状态')),
                ('process_tag', models.IntegerField(choices=[(0, '未处理'), (1, '待核实'), (2, '已确认'), (3, '待清账'), (4, '已处理'), (5, '特殊订单')], default=0, verbose_name='处理标签')),
                ('mistake_tag', models.SmallIntegerField(choices=[(0, '正常'), (1, '重复建单'), (2, '无补寄原因'), (3, '无店铺'), (4, '补寄配件记录格式错误'), (5, '补寄原因错误'), (6, '单据创建失败')], default=0, verbose_name='错误列表')),
            ],
            options={
                'verbose_name': 'CRM-补偿汇总单-查询',
                'verbose_name_plural': 'CRM-补偿汇总单-查询',
                'db_table': 'ass_compen_batch',
            },
        ),
        migrations.CreateModel(
            name='BatchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('servicer', models.CharField(max_length=50, verbose_name='客服')),
                ('shop', models.CharField(max_length=60, verbose_name='店铺')),
                ('goods_name', models.TextField(verbose_name='货品名称')),
                ('nickname', models.CharField(db_index=True, max_length=50, verbose_name='用户网名')),
                ('order_id', models.TextField(verbose_name='订单号')),
                ('compensation', models.FloatField(verbose_name='补偿金额')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='姓名')),
                ('alipay_id', models.CharField(db_index=True, max_length=150, verbose_name='支付宝')),
                ('actual_receipts', models.FloatField(verbose_name='实收金额')),
                ('receivable', models.FloatField(verbose_name='应收金额')),
                ('checking', models.FloatField(verbose_name='验算结果')),
                ('memorandum', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('batch_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compensation.BatchCompensation', verbose_name='批次单')),
            ],
            options={
                'verbose_name': 'CRM-补偿汇总明细单-查询',
                'verbose_name_plural': 'CRM-补偿汇总明细单-查询',
                'db_table': 'ass_compen_batchinfro',
            },
        ),
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('servicer', models.CharField(max_length=50, verbose_name='客服')),
                ('shop', models.CharField(max_length=60, verbose_name='店铺')),
                ('goods_name', models.TextField(verbose_name='货品名称')),
                ('nickname', models.CharField(db_index=True, max_length=50, verbose_name='用户网名')),
                ('order_id', models.TextField(verbose_name='订单号')),
                ('compensation', models.FloatField(verbose_name='补偿金额')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='姓名')),
                ('alipay_id', models.CharField(db_index=True, max_length=150, verbose_name='支付宝')),
                ('actual_receipts', models.FloatField(verbose_name='实收金额')),
                ('receivable', models.FloatField(verbose_name='应收金额')),
                ('checking', models.FloatField(verbose_name='验算结果')),
                ('memorandum', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('order_status', models.IntegerField(choices=[(0, '已取消'), (1, '未处理'), (2, '已完成')], default=1, verbose_name='单据状态')),
                ('process_tag', models.IntegerField(choices=[(0, '未处理'), (1, '待核实'), (2, '已确认'), (3, '待清账'), (4, '已处理'), (5, '特殊订单')], default=0, verbose_name='处理标签')),
                ('mistake_tag', models.SmallIntegerField(choices=[(0, '正常'), (1, '重复建单'), (2, '无补寄原因'), (3, '无店铺'), (4, '补寄配件记录格式错误'), (5, '补寄原因错误'), (6, '单据创建失败')], default=0, verbose_name='错误列表')),
            ],
            options={
                'verbose_name': 'CRM-补偿单-查询',
                'verbose_name_plural': 'CRM-补偿单-查询',
                'db_table': 'ass_compen',
            },
        ),
        migrations.CreateModel(
            name='DiaToOriist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('dialog_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='com_dialog_tb', to='dialog.OriDetailTB', verbose_name='对话明细')),
            ],
            options={
                'verbose_name': 'CRM-补偿单提取对照表-查询',
                'verbose_name_plural': 'CRM-补偿单提取对照表-查询',
                'db_table': 'ass_compen_dia2ori',
            },
        ),
        migrations.CreateModel(
            name='OriCompensation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('servicer', models.CharField(max_length=50, verbose_name='客服')),
                ('shop', models.CharField(max_length=60, verbose_name='店铺')),
                ('goods_name', models.CharField(max_length=50, verbose_name='货品名称')),
                ('nickname', models.CharField(db_index=True, max_length=50, verbose_name='用户网名')),
                ('order_id', models.CharField(db_index=True, max_length=60, verbose_name='订单号')),
                ('order_category', models.SmallIntegerField(choices=[(1, '差价补偿'), (2, '运费补偿'), (3, '退货退款')], default=1, verbose_name='单据类型')),
                ('compensation', models.FloatField(verbose_name='补偿金额')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='姓名')),
                ('alipay_id', models.CharField(db_index=True, max_length=150, verbose_name='支付宝')),
                ('actual_receipts', models.FloatField(verbose_name='实收金额')),
                ('receivable', models.FloatField(verbose_name='应收金额')),
                ('checking', models.FloatField(verbose_name='验算结果')),
                ('memorandum', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('order_status', models.IntegerField(choices=[(0, '已取消'), (1, '未处理'), (2, '已完成')], default=1, verbose_name='单据状态')),
                ('process_tag', models.IntegerField(choices=[(0, '未处理'), (1, '待核实'), (2, '已确认'), (3, '待清账'), (4, '已处理'), (5, '特殊订单')], default=0, verbose_name='处理标签')),
                ('mistake_tag', models.SmallIntegerField(choices=[(0, '正常'), (1, '重复建单'), (2, '无补寄原因'), (3, '无店铺'), (4, '补寄配件记录格式错误'), (5, '补寄原因错误'), (6, '单据创建失败')], default=0, verbose_name='错误列表')),
            ],
            options={
                'verbose_name': 'CRM-原始补偿单-查询',
                'verbose_name_plural': 'CRM-原始补偿单-查询',
                'db_table': 'ass_compen_ori',
            },
        ),
        migrations.CreateModel(
            name='OriToCList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('order_status', models.IntegerField(choices=[(0, '已取消'), (1, '已生成')], default=1, verbose_name='单据状态')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compensation.Compensation', verbose_name='补偿单')),
                ('ori_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='compensation.OriCompensation', verbose_name='原始补偿单')),
            ],
            options={
                'verbose_name': 'CRM-补偿单验算表-查询',
                'verbose_name_plural': 'CRM-补偿单验算表-查询',
                'db_table': 'ass_compen_list',
            },
        ),
        migrations.AddField(
            model_name='diatooriist',
            name='ori_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='com_create', to='compensation.OriCompensation', verbose_name='原始补偿单'),
        ),
        migrations.AddField(
            model_name='batchinfo',
            name='compensation_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compensation.Compensation', verbose_name='补偿单'),
        ),
        migrations.CreateModel(
            name='BCheck',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-补偿汇总单-未审核',
                'verbose_name_plural': 'CRM-补偿汇总单-未审核',
                'proxy': True,
                'indexes': [],
            },
            bases=('compensation.batchcompensation',),
        ),
        migrations.CreateModel(
            name='CCheck',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-补偿单-未审核',
                'verbose_name_plural': 'CRM-补偿单-未审核',
                'proxy': True,
                'indexes': [],
            },
            bases=('compensation.compensation',),
        ),
        migrations.CreateModel(
            name='OCCheck',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-原始补偿单-未审核',
                'verbose_name_plural': 'CRM-原始补偿单-未审核',
                'proxy': True,
                'indexes': [],
            },
            bases=('compensation.oricompensation',),
        ),
    ]
