# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-09-23 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensation',
            name='handle_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处理时间'),
        ),
        migrations.AddField(
            model_name='compensation',
            name='handler',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='处理人'),
        ),
        migrations.AddField(
            model_name='oricompensation',
            name='handle_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处理时间'),
        ),
        migrations.AddField(
            model_name='oricompensation',
            name='handler',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='处理人'),
        ),
        migrations.AlterField(
            model_name='oricompensation',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '重复建单'), (2, '特殊订单才能追加'), (3, '追加单保存出错'), (4, '实收减应收不等于校验金额'), (5, '差价金额不等于校验金额'), (6, '恢复单保存出错'), (7, '补偿单保存出错')], default=0, verbose_name='错误列表'),
        ),
    ]
