# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-09-24 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0002_auto_20200923_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSubmit',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-补偿汇总单-未审核',
                'verbose_name_plural': 'CRM-补偿汇总单-未审核',
                'proxy': True,
                'indexes': [],
            },
            bases=('compensation.batchcompensation',),
        ),
        migrations.AlterModelOptions(
            name='bcheck',
            options={'verbose_name': 'CRM-补偿汇总单-未结算', 'verbose_name_plural': 'CRM-补偿汇总单-未结算'},
        ),
        migrations.AddField(
            model_name='batchcompensation',
            name='handle_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处理时间'),
        ),
        migrations.AddField(
            model_name='batchcompensation',
            name='handler',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='处理人'),
        ),
        migrations.AddField(
            model_name='batchcompensation',
            name='oa_order_id',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='OA单号'),
        ),
        migrations.AddField(
            model_name='batchinfo',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '重复建单'), (2, '无补寄原因'), (3, '无店铺'), (4, '补寄配件记录格式错误'), (5, '补寄原因错误'), (6, '单据创建失败')], default=0, verbose_name='错误列表'),
        ),
        migrations.AddField(
            model_name='batchinfo',
            name='paid_amount',
            field=models.FloatField(default=0, verbose_name='已付金额'),
        ),
        migrations.AddField(
            model_name='batchinfo',
            name='process_tag',
            field=models.IntegerField(choices=[(0, '未处理'), (1, '待核实'), (2, '已确认'), (3, '待清账'), (4, '已处理'), (5, '特殊订单')], default=0, verbose_name='处理标签'),
        ),
        migrations.AlterField(
            model_name='batchcompensation',
            name='order_status',
            field=models.IntegerField(choices=[(0, '已取消'), (1, '未处理'), (2, '未结算'), (3, '已完成')], default=1, verbose_name='单据状态'),
        ),
        migrations.AlterField(
            model_name='batchinfo',
            name='compensation_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='compensation.Compensation', verbose_name='补偿单'),
        ),
        migrations.AlterField(
            model_name='compensation',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '汇总单保存出错'), (2, '无补寄原因'), (3, '无店铺'), (4, '补寄配件记录格式错误'), (5, '补寄原因错误'), (6, '单据创建失败')], default=0, verbose_name='错误列表'),
        ),
        migrations.AlterField(
            model_name='oricompensation',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '重复建单'), (2, '特殊订单才能追加'), (3, '追加单保存出错'), (4, '实收减应收不等于校验金额'), (5, '差价金额不等于校验金额'), (6, '恢复单保存出错'), (7, '补偿单保存出错'), (8, '相同单号存在多个差价，需要设置特殊订单'), (9, '相同单号存在多个差价，需要设置特殊订单')], default=0, verbose_name='错误列表'),
        ),
        migrations.AlterField(
            model_name='oricompensation',
            name='order_category',
            field=models.SmallIntegerField(choices=[(1, '差价补偿'), (2, '错误重置'), (3, '退货退款')], default=1, verbose_name='单据类型'),
        ),
        migrations.AlterField(
            model_name='oricompensation',
            name='process_tag',
            field=models.IntegerField(choices=[(0, '未处理'), (1, '待核实'), (2, '已确认'), (3, '待清账'), (4, '已处理'), (5, '特殊订单'), (6, '重置')], default=0, verbose_name='处理标签'),
        ),
    ]
