# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-25 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0003_auto_20201225_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchinfo',
            name='bank',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='开户行'),
        ),
        migrations.AddField(
            model_name='compensation',
            name='bank',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='开户行'),
        ),
        migrations.AlterField(
            model_name='batchinfo',
            name='alipay_id',
            field=models.CharField(db_index=True, max_length=150, verbose_name='银行卡号'),
        ),
        migrations.AlterField(
            model_name='compensation',
            name='alipay_id',
            field=models.CharField(db_index=True, max_length=150, verbose_name='银行卡号'),
        ),
    ]
