# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-09-24 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0003_auto_20200924_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='BICheck',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-补偿汇总明细单-未结算',
                'verbose_name_plural': 'CRM-补偿汇总明细单-未结算',
                'proxy': True,
                'indexes': [],
            },
            bases=('compensation.batchinfo',),
        ),
        migrations.RemoveField(
            model_name='batchcompensation',
            name='amount',
        ),
        migrations.AlterField(
            model_name='compensation',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '汇总单保存出错'), (2, '汇总单明细保存出错'), (3, '无店铺'), (4, '补寄配件记录格式错误'), (5, '补寄原因错误'), (6, '单据创建失败')], default=0, verbose_name='错误列表'),
        ),
    ]
