# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-09-24 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0004_auto_20200924_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchcompensation',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '无OA单号'), (2, '无补寄原因'), (3, '无店铺'), (4, '补寄配件记录格式错误'), (5, '补寄原因错误'), (6, '单据创建失败')], default=0, verbose_name='错误列表'),
        ),
    ]
