# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-25 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0004_auto_20201225_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchinfo',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='compensation',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='oricompensation',
            name='bank',
        ),
        migrations.AlterField(
            model_name='batchinfo',
            name='alipay_id',
            field=models.CharField(db_index=True, max_length=150, verbose_name='支付宝'),
        ),
        migrations.AlterField(
            model_name='compensation',
            name='alipay_id',
            field=models.CharField(db_index=True, max_length=150, verbose_name='支付宝'),
        ),
        migrations.AlterField(
            model_name='oricompensation',
            name='alipay_id',
            field=models.CharField(db_index=True, max_length=150, verbose_name='支付宝'),
        ),
    ]
