# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-24 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20201121_1337'),
        ('cslabel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('order_status', models.SmallIntegerField(choices=[(0, '已取消'), (1, '待关联'), (2, '已完成')], db_index=True, default=1, verbose_name='单据状态')),
                ('mistake_tag', models.SmallIntegerField(choices=[(0, '正常')], default=0, verbose_name='错误列表')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.CustomerInfo', verbose_name='客户')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cslabel.LabelInfo', verbose_name='标签')),
                ('label_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cslabel.LabelOrder', verbose_name='标签关联单')),
            ],
            options={
                'verbose_name': 'CRM-标签-完整明细查询',
                'verbose_name_plural': 'CRM-标签-完整明细查询',
                'db_table': 'crm_label_result',
            },
        ),
        migrations.AlterUniqueTogether(
            name='labeldetial',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='labeldetial',
            name='label',
        ),
        migrations.AlterUniqueTogether(
            name='labelresult',
            unique_together=set([('label', 'customer')]),
        ),
    ]
