# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-08 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cslabel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelorder',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '个别明细单出错，无法审核'), (2, '没有客户')], default=0, verbose_name='错误列表'),
        ),
    ]
