# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-08 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cslabel', '0002_auto_20201208_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelorder',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '个别明细单出错，无法审核'), (2, '没有客户'), (3, '保存任务出错'), (4, '保存任务镜像出错'), (5, '保存明细出错'), (6, '保存镜像明细出错')], default=0, verbose_name='错误列表'),
        ),
    ]
