# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-25 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cslabel', '0002_auto_20201124_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelorder',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '个别明细单出错，无法审核')], default=0, verbose_name='错误列表'),
        ),
    ]
