# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-25 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cslabel', '0003_labelorder_mistake_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeldetial',
            name='service_num',
            field=models.IntegerField(default=0, verbose_name='关联任务次数'),
        ),
        migrations.AddField(
            model_name='labelresult',
            name='service_num',
            field=models.IntegerField(default=0, verbose_name='关联任务次数'),
        ),
    ]
