# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-27 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_auto_20200326_1524'),
        ('shop', '0001_initial'),
        ('geography', '0001_initial'),
        ('goods', '0002_auto_20200103_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('goods_id', models.CharField(db_index=True, max_length=50, verbose_name='货品编码')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('price', models.FloatField(verbose_name='含税单价')),
                ('memorandum', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('goods_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.MachineInfo', verbose_name='货品名称')),
            ],
            options={
                'verbose_name': 'EXT-发票工单-货品明细',
                'verbose_name_plural': 'EXT-发票工单-货品明细',
                'db_table': 'ext_workorder_invoice_goods',
            },
        ),
        migrations.CreateModel(
            name='InvoiceGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('goods_id', models.CharField(db_index=True, max_length=50, verbose_name='货品编码')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('price', models.FloatField(verbose_name='含税单价')),
                ('memorandum', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('goods_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.MachineInfo', verbose_name='货品名称')),
            ],
            options={
                'verbose_name': 'EXT-发票订单-货品明细',
                'verbose_name_plural': 'EXT-发票订单-货品明细',
                'db_table': 'ext_invoice_order_goods',
            },
        ),
        migrations.CreateModel(
            name='InvoiceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('order_id', models.CharField(max_length=100, unique=True, verbose_name='源单号')),
                ('order_category', models.SmallIntegerField(choices=[(1, '专票'), (2, '普票')], verbose_name='发票类型')),
                ('invoice_id', models.CharField(blank=True, max_length=60, null=True, verbose_name='发票号码')),
                ('title', models.CharField(max_length=150, verbose_name='发票抬头')),
                ('tax_id', models.CharField(max_length=60, verbose_name='纳税人识别号')),
                ('phone', models.CharField(blank=True, max_length=60, null=True, verbose_name='联系电话')),
                ('bank', models.CharField(blank=True, max_length=100, null=True, verbose_name='银行名称')),
                ('account', models.CharField(blank=True, max_length=60, null=True, verbose_name='银行账户')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('remark', models.CharField(blank=True, max_length=230, null=True, verbose_name='发票备注')),
                ('sent_consignee', models.CharField(max_length=150, verbose_name='收件人姓名')),
                ('sent_smartphone', models.CharField(max_length=30, verbose_name='收件人手机')),
                ('sent_district', models.CharField(max_length=30, verbose_name='收件区县')),
                ('sent_address', models.CharField(max_length=200, verbose_name='收件地址')),
                ('amount', models.FloatField(verbose_name='发票税前开票总额')),
                ('ori_amount', models.FloatField(verbose_name='源工单开票总额')),
                ('is_deliver', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], verbose_name='是否打印快递')),
                ('track_no', models.CharField(blank=True, max_length=60, null=True, verbose_name='快递单号')),
                ('submit_time', models.DateTimeField(blank=True, null=True, verbose_name='申请提交时间')),
                ('handle_time', models.DateTimeField(blank=True, null=True, verbose_name='开票处理时间')),
                ('handle_interval', models.IntegerField(blank=True, null=True, verbose_name='开票处理间隔(分钟)')),
                ('message', models.CharField(blank=True, max_length=300, null=True, verbose_name='工单留言')),
                ('memorandum', models.CharField(blank=True, max_length=300, null=True, verbose_name='工单反馈')),
                ('process_tag', models.SmallIntegerField(choices=[(0, '未处理'), (1, '开票中'), (2, '已开票'), (3, '待买票'), (4, '信息错'), (5, '已打单'), (6, '已处理')], default=0, verbose_name='处理标签')),
                ('mistake_tag', models.SmallIntegerField(choices=[(0, '正常'), (1, '返回单号为空'), (2, '处理意见为空'), (3, '经销商反馈为空'), (4, '先标记为已处理才能审核'), (5, '先标记为已对账才能审核'), (6, '工单必须为取消状态'), (7, '先标记为终端清才能审核')], default=0, verbose_name='错误原因')),
                ('order_status', models.SmallIntegerField(choices=[(0, '已被取消'), (1, '开票处理'), (2, '终审复核'), (3, '工单完结')], default=1, verbose_name='工单状态')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainc_invoice', to='company.MainInfo', verbose_name='收款开票公司')),
                ('sent_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.CityInfo', verbose_name='收件城市')),
                ('sent_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.ProvinceInfo', verbose_name='收件省份')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ShopInfo', verbose_name='店铺')),
            ],
            options={
                'verbose_name': 'EXT-发票订单-查询',
                'verbose_name_plural': 'EXT-发票订单-查询',
                'db_table': 'ext_invoice_order',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('order_id', models.CharField(max_length=100, unique=True, verbose_name='源单号')),
                ('order_category', models.SmallIntegerField(choices=[(1, '专票'), (2, '普票')], verbose_name='发票类型')),
                ('title', models.CharField(max_length=150, verbose_name='发票抬头')),
                ('tax_id', models.CharField(max_length=60, verbose_name='纳税人识别号')),
                ('phone', models.CharField(blank=True, max_length=60, null=True, verbose_name='联系电话')),
                ('bank', models.CharField(blank=True, max_length=100, null=True, verbose_name='银行名称')),
                ('account', models.CharField(blank=True, max_length=60, null=True, verbose_name='银行账户')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('remark', models.CharField(blank=True, max_length=230, null=True, verbose_name='发票备注')),
                ('sent_consignee', models.CharField(max_length=150, verbose_name='收件人姓名')),
                ('sent_smartphone', models.CharField(max_length=30, verbose_name='收件人手机')),
                ('sent_district', models.CharField(max_length=30, verbose_name='收件区县')),
                ('sent_address', models.CharField(max_length=200, verbose_name='收件地址')),
                ('amount', models.FloatField(default=0, verbose_name='申请税前开票总额')),
                ('is_deliver', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], verbose_name='是否打印快递')),
                ('submit_time', models.DateTimeField(blank=True, null=True, verbose_name='申请提交时间')),
                ('handle_time', models.DateTimeField(blank=True, null=True, verbose_name='开票处理时间')),
                ('handle_interval', models.IntegerField(blank=True, null=True, verbose_name='开票处理间隔(分钟)')),
                ('message', models.CharField(blank=True, max_length=300, null=True, verbose_name='工单留言')),
                ('memorandum', models.CharField(blank=True, max_length=300, null=True, verbose_name='工单反馈')),
                ('process_tag', models.SmallIntegerField(choices=[(0, '未处理'), (1, '开票中'), (2, '已开票'), (3, '待买票'), (4, '信息错'), (5, '已打单'), (6, '已处理')], default=0, verbose_name='处理标签')),
                ('mistake_tag', models.SmallIntegerField(choices=[(0, '正常'), (1, '没开票公司'), (2, '货品错误'), (3, '专票信息缺'), (4, '收件手机错'), (5, '超限额发票'), (6, '递交发票订单出错'), (7, '生成发票货品出错'), (8, '单货品超限额非法')], default=0, verbose_name='错误原因')),
                ('order_status', models.SmallIntegerField(choices=[(0, '已被取消'), (1, '申请未报'), (2, '正在审核'), (3, '单据生成')], default=1, verbose_name='工单状态')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainc', to='company.MainInfo', verbose_name='收款开票公司')),
                ('sent_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.CityInfo', verbose_name='收件城市')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ShopInfo', verbose_name='店铺')),
            ],
            options={
                'verbose_name': 'EXT-发票工单-查询',
                'verbose_name_plural': 'EXT-发票工单-查询',
                'db_table': 'ext_workorder_invoice',
            },
        ),
        migrations.AddField(
            model_name='invoiceorder',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorderinvoice.WorkOrder', verbose_name='来源单号'),
        ),
        migrations.AddField(
            model_name='invoicegoods',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorderinvoice.InvoiceOrder', verbose_name='发票订单'),
        ),
        migrations.AddField(
            model_name='goodsdetail',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorderinvoice.WorkOrder', verbose_name='发票工单'),
        ),
        migrations.CreateModel(
            name='IOCheck',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-发票订单-未终审',
                'verbose_name_plural': 'EXT-发票订单-未终审',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorderinvoice.invoiceorder',),
        ),
        migrations.CreateModel(
            name='IOhandle',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-发票订单-未开票',
                'verbose_name_plural': 'EXT-发票订单-未开票',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorderinvoice.invoiceorder',),
        ),
        migrations.CreateModel(
            name='WOCheck',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-发票工单-未审核',
                'verbose_name_plural': 'EXT-发票工单-未审核',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorderinvoice.workorder',),
        ),
        migrations.CreateModel(
            name='WOUnhandle',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-发票工单-未递交',
                'verbose_name_plural': 'EXT-发票工单-未递交',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorderinvoice.workorder',),
        ),
        migrations.AlterUniqueTogether(
            name='goodsdetail',
            unique_together=set([('invoice', 'goods_name')]),
        ),
    ]
