# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-30 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderinvoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceorder',
            name='amount',
            field=models.FloatField(default=0, verbose_name='发票税前开票总额'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '没开票公司'), (2, '货品错误'), (3, '专票信息缺'), (4, '收件手机错'), (5, '超限额发票'), (6, '递交发票订单出错'), (7, '生成发票货品出错'), (8, '单货品超限额非法'), (9, '发票订单生成重复'), (10, '生成发票订单出错'), (11, '生成发票订单货品出错')], default=0, verbose_name='错误原因'),
        ),
    ]
