# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-30 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorderinvoice', '0002_auto_20200330_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('shop', models.CharField(max_length=60, verbose_name='店铺')),
                ('ori_order_id', models.CharField(db_index=True, max_length=250, verbose_name='原始单号')),
                ('nickname', models.CharField(max_length=200, verbose_name='网名')),
                ('consignee', models.CharField(max_length=200, verbose_name='收货人')),
                ('address', models.CharField(max_length=300, verbose_name='地址')),
                ('smartphone', models.CharField(max_length=60, verbose_name='手机')),
                ('condition_deliver', models.CharField(default='款到发货', max_length=30, verbose_name='发货条件')),
                ('discounts', models.SmallIntegerField(default=0, verbose_name='优惠金额')),
                ('postage', models.SmallIntegerField(default=0, verbose_name='邮费')),
                ('receivable', models.SmallIntegerField(default=0, verbose_name='应收合计')),
                ('goods_price', models.SmallIntegerField(default=0, verbose_name='货品价格')),
                ('goods_amount', models.SmallIntegerField(default=0, verbose_name='货品总价')),
                ('goods_id', models.CharField(max_length=100, verbose_name='商家编码')),
                ('good_name', models.CharField(max_length=100, verbose_name='商家编码')),
                ('quantity', models.SmallIntegerField(default=1, verbose_name='货品数量')),
                ('order_category', models.CharField(default='线下零售', max_length=30, verbose_name='发货条件')),
                ('meesage', models.CharField(max_length=150, verbose_name='买家备注')),
                ('province', models.CharField(max_length=60, verbose_name='省')),
                ('city', models.CharField(max_length=60, verbose_name='市')),
                ('district', models.CharField(max_length=60, verbose_name='区')),
                ('logistic', models.CharField(max_length=60, verbose_name='快递公司')),
                ('track_no', models.CharField(max_length=60, verbose_name='快递单号')),
                ('order_status', models.SmallIntegerField(choices=[(0, '已被取消'), (1, '等待打单'), (2, '打印完成')], default=1, verbose_name='单据状态')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ori_work_order', to='workorderinvoice.WorkOrder', verbose_name='来源单号')),
            ],
            options={
                'verbose_name': 'EXT-发票快递单-查询',
                'verbose_name_plural': 'EXT-发票快递单-查询',
                'db_table': 'ext_invoice_deliver',
            },
        ),
        migrations.AlterField(
            model_name='invoiceorder',
            name='is_deliver',
            field=models.SmallIntegerField(choices=[(0, '否'), (1, '是')], verbose_name='是否顺丰'),
        ),
        migrations.AlterField(
            model_name='invoiceorder',
            name='process_tag',
            field=models.SmallIntegerField(choices=[(0, '未处理'), (1, '开票中'), (2, '已开票'), (3, '待买票'), (4, '信息错'), (5, '待打单'), (6, '已打单'), (7, '已处理')], default=0, verbose_name='处理标签'),
        ),
        migrations.AlterField(
            model_name='invoiceorder',
            name='track_no',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='快递信息'),
        ),
        migrations.CreateModel(
            name='DOCheck',
            fields=[
            ],
            options={
                'verbose_name': 'EXT-发票快递单-待打单',
                'verbose_name_plural': 'EXT-发票快递单-待打单',
                'proxy': True,
                'indexes': [],
            },
            bases=('workorderinvoice.deliverorder',),
        ),
    ]
