# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-30 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorderinvoice', '0004_auto_20200330_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverorder',
            old_name='good_name',
            new_name='goods_name',
        ),
    ]
