# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-30 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorderinvoice', '0005_auto_20200330_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverorder',
            old_name='meesage',
            new_name='message',
        ),
    ]
