# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-31 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderinvoice', '0006_auto_20200330_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverorder',
            name='district',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='区'),
        ),
        migrations.AlterField(
            model_name='deliverorder',
            name='goods_id',
            field=models.CharField(default='00000090', max_length=100, verbose_name='商家编码'),
        ),
        migrations.AlterField(
            model_name='deliverorder',
            name='goods_name',
            field=models.CharField(default='文件：发票', max_length=100, verbose_name='商家编码'),
        ),
        migrations.AlterField(
            model_name='deliverorder',
            name='track_no',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='快递单号'),
        ),
        migrations.AlterField(
            model_name='invoiceorder',
            name='sent_district',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='收件区县'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='is_deliver',
            field=models.SmallIntegerField(choices=[(0, '否'), (1, '是')], verbose_name='是否发顺丰'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='sent_district',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='收件区县'),
        ),
    ]
