# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-31 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderinvoice', '0007_auto_20200331_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverorder',
            name='process_tag',
            field=models.SmallIntegerField(choices=[(0, '待打印'), (1, '已打印')], default=0, verbose_name='单据状态'),
        ),
        migrations.AlterField(
            model_name='invoiceorder',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '无发票号'), (2, '快递单错误')], default=0, verbose_name='错误原因'),
        ),
    ]
