# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-31 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderinvoice', '0008_auto_20200331_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverorder',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '未打印'), (2, '快递信息回写失败')], default=0, verbose_name='错误原因'),
        ),
    ]
