# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-04-01 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderinvoice', '0009_deliverorder_mistake_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='is_deliver',
            field=models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否发顺丰'),
        ),
    ]
