# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-04-01 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderinvoice', '0011_auto_20200401_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverorder',
            name='memorandum',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='单据备注'),
        ),
        migrations.AlterField(
            model_name='deliverorder',
            name='process_tag',
            field=models.SmallIntegerField(choices=[(0, '待打印'), (1, '已打印'), (2, '暂停发')], default=0, verbose_name='单据状态'),
        ),
    ]
