# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-04-01 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderinvoice', '0012_auto_20200401_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceorder',
            name='process_tag',
            field=models.SmallIntegerField(choices=[(0, '未处理'), (1, '开票中'), (2, '已开票'), (3, '待开票'), (4, '待打单'), (5, '已开票已打单'), (6, '已处理')], default=0, verbose_name='处理标签'),
        ),
    ]
