# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-04-03 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderinvoice', '0013_auto_20200401_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceorder',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='发票号码'),
        ),
        migrations.AlterField(
            model_name='invoiceorder',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '无发票号'), (2, '快递单错误'), (3, '快递未发货')], default=0, verbose_name='错误原因'),
        ),
    ]
