# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-04-04 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderinvoice', '0014_auto_20200403_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceorder',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '无发票号'), (2, '快递单错误'), (3, '快递未发货'), (4, '驳回出错')], default=0, verbose_name='错误原因'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '没开票公司'), (2, '货品错误'), (3, '专票信息缺'), (4, '收件手机错'), (5, '超限额发票'), (6, '递交发票订单出错'), (7, '生成发票货品出错'), (8, '单货品超限额非法'), (9, '发票订单生成重复'), (10, '生成发票订单出错'), (11, '生成发票订单货品出错'), (12, '单据被驳回'), (13, '税号错误')], default=0, verbose_name='错误原因'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='process_tag',
            field=models.SmallIntegerField(choices=[(0, '未处理'), (1, '开票中'), (2, '已开票'), (3, '待买票'), (4, '信息错'), (5, '被驳回'), (6, '已处理')], default=0, verbose_name='处理标签'),
        ),
    ]
