# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-04-07 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderinvoice', '0015_auto_20200404_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverorder',
            name='consignee',
            field=models.CharField(max_length=200, verbose_name='收件人'),
        ),
        migrations.AlterField(
            model_name='deliverorder',
            name='order_category',
            field=models.CharField(default='线下零售', max_length=30, verbose_name='订单类型'),
        ),
        migrations.AlterField(
            model_name='deliverorder',
            name='shop',
            field=models.CharField(max_length=60, verbose_name='店铺名称'),
        ),
    ]
