# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-04-07 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderinvoice', '0016_auto_20200407_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverorder',
            name='goods_name',
            field=models.CharField(default='文件：发票', max_length=100, verbose_name='货品名称'),
        ),
        migrations.AlterField(
            model_name='deliverorder',
            name='order_category',
            field=models.CharField(default='线下零售', max_length=30, verbose_name='订单类别'),
        ),
    ]
