# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-04-13 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20200326_1524'),
        ('workorderinvoice', '0019_workorder_sign_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceorder',
            name='sign_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_sign_company', to='company.MainInfo', verbose_name='创建公司'),
        ),
    ]
