# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-04-13 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorderinvoice', '0020_invoiceorder_sign_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicegoods',
            name='goods_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='货品简称'),
        ),
    ]
