# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-04-15 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('workorderinvoice', '0023_auto_20200414_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceorder',
            name='sign_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.DepartmentInfo', verbose_name='创建部门'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='sign_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.DepartmentInfo', verbose_name='创建部门'),
        ),
    ]
