# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-04-15 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorderinvoice', '0024_auto_20200415_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicegoods',
            old_name='goods_title',
            new_name='goods_nickname',
        ),
        migrations.AlterField(
            model_name='invoiceorder',
            name='sign_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_sign_department', to='department.DepartmentInfo', verbose_name='创建部门'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='sign_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sign_department', to='department.DepartmentInfo', verbose_name='创建部门'),
        ),
    ]
