# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-02-14 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstomanufactoryinfo',
            name='category',
            field=models.IntegerField(choices=[(0, '整机装配厂'), (1, '常规配件')], default=0, verbose_name='对照类型'),
        ),
    ]
