# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-28 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relationship', '0001_initial'),
        ('warehouse', '0001_initial'),
        ('manufactory', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufactorytowarehouse',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseInfo', verbose_name='仓库'),
        ),
        migrations.AddField(
            model_name='goodstomanufactoryinfo',
            name='goods_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo', verbose_name='机器名称'),
        ),
        migrations.AddField(
            model_name='goodstomanufactoryinfo',
            name='manufactory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.ManufactoryInfo', verbose_name='工厂名字'),
        ),
        migrations.CreateModel(
            name='CusPartToManufactoryInfo',
            fields=[
            ],
            options={
                'verbose_name': 'BA-R-客供件工厂对照表',
                'verbose_name_plural': 'BA-R-客供件工厂对照表',
                'proxy': True,
                'indexes': [],
            },
            bases=('relationship.goodstomanufactoryinfo',),
        ),
        migrations.CreateModel(
            name='MachineToManufactoryInfo',
            fields=[
            ],
            options={
                'verbose_name': 'BA-R-整机工厂对照表',
                'verbose_name_plural': 'BA-R-整机工厂对照表',
                'proxy': True,
                'indexes': [],
            },
            bases=('relationship.goodstomanufactoryinfo',),
        ),
        migrations.CreateModel(
            name='PartToManufactoryInfo',
            fields=[
            ],
            options={
                'verbose_name': 'BA-R-配件工厂对照表',
                'verbose_name_plural': 'BA-R-配件工厂对照表',
                'proxy': True,
                'indexes': [],
            },
            bases=('relationship.goodstomanufactoryinfo',),
        ),
    ]
