# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-18 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0002_auto_20190928_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstomanufactoryinfo',
            name='manufactory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.ManuInfo', verbose_name='工厂名字'),
        ),
        migrations.AlterField(
            model_name='manufactorytowarehouse',
            name='manufactory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.ManuInfo', verbose_name='工厂'),
        ),
    ]
