# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-26 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufactory', '0001_initial'),
        ('warehouse', '0001_initial'),
        ('relationship', '0003_auto_20190625_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufactoryToWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '停用')], default=0, verbose_name='状态')),
                ('manufactory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manufactory.ManufactoryInfo', verbose_name='工厂')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseInfo', verbose_name='仓库')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
