# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-26 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0005_auto_20190626_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufactorytowarehouse',
            options={'verbose_name': '工厂与仓库对照表', 'verbose_name_plural': '工厂与仓库对照表'},
        ),
    ]
