# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-27 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('version_number', models.CharField(max_length=55, verbose_name='版本号')),
                ('description', models.TextField(verbose_name='版本说明')),
            ],
            options={
                'verbose_name': '版本说明',
                'verbose_name_plural': '版本说明',
                'db_table': 'base_changelog',
            },
        ),
    ]
