# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-15 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webchatcus', '0003_auto_20201215_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oriwebchatinfo',
            name='birthday',
        ),
    ]
