# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-15 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webchatcus', '0004_remove_oriwebchatinfo_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webchatinfo',
            name='birthday',
        ),
    ]
