# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-16 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webchatcus', '0005_remove_webchatinfo_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oriwarrantyinfo',
            name='birthday',
        ),
    ]
