# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-16 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchatcus', '0007_auto_20201216_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oriwarrantyinfo',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '已导入过的订单'), (2, '还未生成客户档案')], default=0, verbose_name='错误列表'),
        ),
    ]
