# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-24 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('goods_name', models.CharField(max_length=60, verbose_name='货品名称')),
                ('goods_id', models.CharField(max_length=30, verbose_name='货品编码')),
                ('category', models.IntegerField(verbose_name='货品类型')),
                ('size', models.CharField(max_length=10, verbose_name='规格')),
                ('inventory', models.IntegerField(verbose_name='库存')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseInfo', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
                'db_table': 'oms_stk_stock',
            },
        ),
        migrations.CreateModel(
            name='StockInOrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('stockin_id', models.CharField(max_length=30, verbose_name='入库单号')),
                ('status', models.IntegerField(choices=[(0, '未处理'), (1, '已入库'), (2, '取消')], default=0, verbose_name='状态')),
                ('category', models.IntegerField(choices=[(0, '合格'), (1, '不合格')], default=0, verbose_name='入库单类型')),
                ('batch_num', models.CharField(max_length=30, verbose_name='批次号')),
                ('warehouse', models.CharField(max_length=60, verbose_name='仓库名称')),
                ('goods_name', models.CharField(max_length=60, verbose_name='货品名称')),
                ('goods_id', models.CharField(max_length=30, verbose_name='货品编码')),
                ('quantity', models.IntegerField(verbose_name='入库数量')),
            ],
            options={
                'verbose_name': '入库单',
                'verbose_name_plural': '入库单',
                'db_table': 'oms_stk_stockin',
            },
        ),
        migrations.CreateModel(
            name='StockOutInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('stockout_id', models.CharField(max_length=30, verbose_name='出库单号')),
                ('source_order_id', models.CharField(max_length=30, verbose_name='关联单号')),
                ('status', models.IntegerField(choices=[(0, '未处理'), (1, '已完成'), (2, '取消')], default=0, verbose_name='状态')),
                ('goods_name', models.CharField(max_length=60, verbose_name='货品名称')),
                ('goods_id', models.CharField(max_length=30, verbose_name='货品编码')),
                ('quantity', models.IntegerField(verbose_name='发货数量')),
                ('warehouse', models.CharField(max_length=60, verbose_name='仓库名称')),
                ('nickname', models.CharField(max_length=60, verbose_name='昵称')),
                ('receiver', models.CharField(max_length=60, verbose_name='收货人')),
                ('province', models.CharField(max_length=30, verbose_name='省份')),
                ('city', models.CharField(max_length=30, verbose_name='城市')),
                ('district', models.CharField(max_length=60, verbose_name='区县')),
                ('mobile', models.CharField(max_length=30, verbose_name='收货人手机')),
                ('memorandum', models.TextField(verbose_name='备注')),
            ],
            options={
                'verbose_name': '出库单',
                'verbose_name_plural': '出库单',
                'db_table': 'oms_stk_stockout',
            },
        ),
    ]
