# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-27 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('goods_name', models.CharField(max_length=60, verbose_name='货品名称')),
                ('goods_id', models.CharField(max_length=30, verbose_name='货品编码')),
                ('category', models.IntegerField(choices=[(0, '整机'), (1, '配件'), (2, '礼品')], default=0, verbose_name='货品类型')),
                ('size', models.CharField(blank=True, max_length=10, null=True, verbose_name='规格')),
                ('quantity', models.IntegerField(verbose_name='库存')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseInfo', verbose_name='仓库')),
            ],
            options={
                'verbose_name': 'WMS-S-库存',
                'verbose_name_plural': 'WMS-S-库存',
                'db_table': 'wms_stk_stock',
            },
        ),
        migrations.CreateModel(
            name='StockGiftInfo',
            fields=[
            ],
            options={
                'verbose_name': 'WMS-S-礼品库存',
                'verbose_name_plural': 'WMS-S-礼品库存',
                'proxy': True,
                'indexes': [],
            },
            bases=('stock.stockinfo',),
        ),
        migrations.CreateModel(
            name='StockMachineInfo',
            fields=[
            ],
            options={
                'verbose_name': 'WMS-S-整机库存',
                'verbose_name_plural': 'WMS-S-整机库存',
                'proxy': True,
                'indexes': [],
            },
            bases=('stock.stockinfo',),
        ),
        migrations.CreateModel(
            name='StockPartInfo',
            fields=[
            ],
            options={
                'verbose_name': 'WMS-S-配件库存',
                'verbose_name_plural': 'WMS-S-配件库存',
                'proxy': True,
                'indexes': [],
            },
            bases=('stock.stockinfo',),
        ),
    ]
