# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-25 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinorderinfo',
            name='category',
            field=models.IntegerField(choices=[(0, '质检入库'), (1, '采购入库')], default=0, verbose_name='入库单类型'),
        ),
        migrations.AlterField(
            model_name='stockinorderinfo',
            name='status',
            field=models.IntegerField(choices=[(0, '未处理'), (1, '已入库'), (2, '已取消')], default=0, verbose_name='状态'),
        ),
    ]
