# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-28 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseInfo', verbose_name='仓库'),
        ),
        migrations.CreateModel(
            name='StockGiftInfo',
            fields=[
            ],
            options={
                'verbose_name': 'WMS-S-礼品库存',
                'verbose_name_plural': 'WMS-S-礼品库存',
                'proxy': True,
                'indexes': [],
            },
            bases=('stock.stockinfo',),
        ),
        migrations.CreateModel(
            name='StockMachineInfo',
            fields=[
            ],
            options={
                'verbose_name': 'WMS-S-整机库存',
                'verbose_name_plural': 'WMS-S-整机库存',
                'proxy': True,
                'indexes': [],
            },
            bases=('stock.stockinfo',),
        ),
        migrations.CreateModel(
            name='StockPartInfo',
            fields=[
            ],
            options={
                'verbose_name': 'WMS-S-配件库存',
                'verbose_name_plural': 'WMS-S-配件库存',
                'proxy': True,
                'indexes': [],
            },
            bases=('stock.stockinfo',),
        ),
    ]
