# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-25 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20190625_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinorderinfo',
            name='planorder_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='批次号'),
        ),
        migrations.AddField(
            model_name='stockoutinfo',
            name='category',
            field=models.IntegerField(choices=[(0, '常规出库'), (1, '客供出库')], default=0, verbose_name='出库类型'),
        ),
        migrations.AlterField(
            model_name='stockoutinfo',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='stockoutinfo',
            name='district',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='区县'),
        ),
        migrations.AlterField(
            model_name='stockoutinfo',
            name='memorandum',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='stockoutinfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='收货人手机'),
        ),
        migrations.AlterField(
            model_name='stockoutinfo',
            name='nickname',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='stockoutinfo',
            name='province',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='stockoutinfo',
            name='receiver',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='收货人'),
        ),
    ]
