# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-26 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20190625_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinorderinfo',
            name='stockin_id',
        ),
    ]
