# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-26 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_stockinorderinfo_stockin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinorderinfo',
            name='source_order_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='关联单号'),
        ),
    ]
