# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-26 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_stockinorderinfo_source_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='source_order_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='来源单号'),
        ),
        migrations.AlterField(
            model_name='stockinorderinfo',
            name='source_order_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='来源单号'),
        ),
    ]
