# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-26 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20190626_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinfo',
            name='source_order_id',
        ),
    ]
