# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-01 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manuorder', '0003_auto_20191030_1309'),
        ('warehouse', '0002_auto_20191018_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('qc_order_id', models.CharField(max_length=30, unique=True, verbose_name='质检单号')),
                ('goods_name', models.CharField(max_length=60, verbose_name='货品名称')),
                ('order_status', models.IntegerField(choices=[(0, '已取消'), (1, '未处理'), (2, '已确认'), (3, '已递交'), (4, '异常')], default=1, verbose_name='质检单状态')),
                ('manufactory', models.CharField(max_length=60, verbose_name='工厂名称')),
                ('goods_id', models.CharField(max_length=30, verbose_name='货品编码')),
                ('quantity', models.IntegerField(verbose_name='验货数量')),
                ('total_quantity', models.IntegerField(verbose_name='订单数量')),
                ('accumulation', models.IntegerField(verbose_name='累计数量')),
                ('result', models.IntegerField(choices=[(0, '合格'), (1, '不合格')], verbose_name='验货结果')),
                ('category', models.IntegerField(choices=[(0, '首检'), (1, '复检'), (2, '召回')], verbose_name='验货类型')),
                ('check_quantity', models.IntegerField(verbose_name='抽检数量')),
                ('a_flaw', models.IntegerField(verbose_name='A类缺陷')),
                ('b1_flaw', models.IntegerField(verbose_name='B1类缺陷')),
                ('b2_flaw', models.IntegerField(verbose_name='B2类缺陷')),
                ('c_flaw', models.IntegerField(verbose_name='C类缺陷')),
                ('memorandum', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('qc_time', models.DateTimeField(verbose_name='验货时间')),
                ('batch_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuorder.ManuOrderInfo', verbose_name='批次号码')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseInfo', verbose_name='仓库名称')),
            ],
            options={
                'verbose_name': 'OMS-QC-质检单明细表',
                'verbose_name_plural': 'OMS-QC-质检单明细表',
                'db_table': 'oms_qc_order',
            },
        ),
        migrations.CreateModel(
            name='QCOriInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('order_status', models.SmallIntegerField(choices=[(0, '已取消'), (1, '未递交'), (2, '已递交'), (3, '异常')], default=1, verbose_name='质检单状态')),
                ('quantity', models.IntegerField(verbose_name='验货数量')),
                ('result', models.SmallIntegerField(choices=[(0, '合格'), (1, '不合格')], default=0, verbose_name='验货结果')),
                ('category', models.SmallIntegerField(choices=[(0, '首检'), (1, '复检'), (2, '召回')], default=0, verbose_name='验货类型')),
                ('check_quantity', models.IntegerField(verbose_name='抽检数量')),
                ('a_flaw', models.IntegerField(verbose_name='A类缺陷')),
                ('b1_flaw', models.IntegerField(verbose_name='B1类缺陷')),
                ('b2_flaw', models.IntegerField(verbose_name='B2类缺陷')),
                ('c_flaw', models.IntegerField(verbose_name='C类缺陷')),
                ('memorandum', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('qc_order_id', models.CharField(max_length=30, null=True, verbose_name='质检单号')),
                ('error_info', models.SmallIntegerField(choices=[(0, '正常'), (1, '质检数超订单数'), (2, '工厂没关联仓库'), (3, '已存在入库单，请联系管理员处理'), (4, '生入库单出现意外'), (5, '已递交过，检查处理'), (6, '递交质检单出现意外')], default=0, verbose_name='错误原因')),
                ('qc_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='质检时间')),
                ('batch_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuorder.ManuOrderInfo', verbose_name='批次号码')),
            ],
            options={
                'verbose_name': 'OMS-QC-原始质检单明细表',
                'verbose_name_plural': 'OMS-QC-原始质检单明细表',
                'db_table': 'oms_qc_oriorder',
            },
        ),
        migrations.CreateModel(
            name='QCSubmitInfo',
            fields=[
            ],
            options={
                'verbose_name': 'OMS-QC-未递交质检单明细表',
                'verbose_name_plural': 'OMS-QC-未递交质检单明细表',
                'proxy': True,
                'indexes': [],
            },
            bases=('qcorder.qcinfo',),
        ),
        migrations.CreateModel(
            name='QCSubmitOriInfo',
            fields=[
            ],
            options={
                'verbose_name': 'OMS-QC-未递交原始质检单',
                'verbose_name_plural': 'OMS-QC-未递交原始质检单',
                'proxy': True,
                'indexes': [],
            },
            bases=('qcorder.qcoriinfo',),
        ),
    ]
