# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-24 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manuorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('batch_num', models.CharField(max_length=30, verbose_name='批次号码')),
                ('qc_order_id', models.CharField(max_length=30, verbose_name='质检单号')),
                ('goods_name', models.CharField(max_length=60, verbose_name='货品名称')),
                ('status', models.IntegerField(choices=[(0, '未处理'), (1, '已确认'), (2, '已递交'), (3, '取消')], default=0, verbose_name='质检单状态')),
                ('manufactory', models.CharField(max_length=60, verbose_name='工厂名称')),
                ('goods_id', models.CharField(max_length=30, verbose_name='货品编码')),
                ('quantity', models.IntegerField(verbose_name='验货数量')),
                ('total_quantity', models.IntegerField(verbose_name='订单数量')),
                ('accumulation', models.IntegerField(verbose_name='累计数量')),
                ('result', models.IntegerField(choices=[(0, '合格'), (1, '不合格')], verbose_name='验货结果')),
                ('category', models.IntegerField(choices=[(0, '首检'), (1, '复检')], verbose_name='验货类型')),
                ('check_quantity', models.IntegerField(verbose_name='抽检数量')),
                ('a_flaw', models.IntegerField(verbose_name='A类缺陷')),
                ('b1_flaw', models.IntegerField(verbose_name='B1类缺陷')),
                ('b2_flaw', models.IntegerField(verbose_name='B2类缺陷')),
                ('c_flaw', models.IntegerField(verbose_name='C类缺陷')),
                ('dpu', models.FloatField(verbose_name='百台故障率')),
                ('memorandum', models.CharField(max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '工厂验货明细表',
                'verbose_name_plural': '工厂验货明细表',
                'db_table': 'oms_qc_order',
            },
        ),
        migrations.CreateModel(
            name='QCOriInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('quantity', models.IntegerField(verbose_name='验货数量')),
                ('result', models.IntegerField(choices=[(0, '合格'), (1, '不合格')], default=0, verbose_name='验货结果')),
                ('category', models.IntegerField(choices=[(0, '首检'), (1, '复检')], default=0, verbose_name='验货类型')),
                ('check_quantity', models.IntegerField(verbose_name='抽检数量')),
                ('a_flaw', models.IntegerField(verbose_name='A类缺陷')),
                ('b1_flaw', models.IntegerField(verbose_name='B1类缺陷')),
                ('b2_flaw', models.IntegerField(verbose_name='B2类缺陷')),
                ('c_flaw', models.IntegerField(verbose_name='C类缺陷')),
                ('dpu', models.FloatField(verbose_name='百台故障率')),
                ('memorandum', models.CharField(max_length=200, verbose_name='备注')),
                ('batch_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuorder.ManuOrderInfo', verbose_name='批次号码')),
            ],
            options={
                'verbose_name': '工厂验货原始明细表',
                'verbose_name_plural': '工厂验货原始明细表',
                'db_table': 'oms_qc_oriorder',
            },
        ),
    ]
