# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-24 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcoriinfo',
            name='status',
            field=models.IntegerField(choices=[(0, '未递交'), (1, '有错误'), (2, '已递交'), (3, '取消')], default=0, verbose_name='质检单状态'),
        ),
    ]
