# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-24 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcoriinfo',
            name='status',
            field=models.IntegerField(choices=[(0, '已取消'), (1, '未递交'), (2, '已递交'), (3, '异常')], default=1, verbose_name='质检单状态'),
        ),
    ]
