# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-13 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcorder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qcoriinfo',
            old_name='error_info',
            new_name='error_tag',
        ),
        migrations.AddField(
            model_name='qcinfo',
            name='error_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '仓库错误'), (2, '其他错误')], default=0, verbose_name='错误原因'),
        ),
        migrations.AddField(
            model_name='qcinfo',
            name='sn_end',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='产品序列号尾号'),
        ),
        migrations.AddField(
            model_name='qcinfo',
            name='sn_start',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='产品序列号首号'),
        ),
    ]
