# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-28 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcorder', '0002_auto_20191024_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qcoriinfo',
            old_name='status',
            new_name='order_status',
        ),
        migrations.RemoveField(
            model_name='qcinfo',
            name='status',
        ),
        migrations.AddField(
            model_name='qcinfo',
            name='order_status',
            field=models.IntegerField(choices=[(0, '已取消'), (1, '未处理'), (2, '已确认'), (3, '已递交'), (4, '异常')], default=1, verbose_name='质检单状态'),
        ),
    ]
