# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-26 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcorder', '0002_auto_20191213_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qcinfo',
            old_name='qc_time',
            new_name='qc_date',
        ),
        migrations.RenameField(
            model_name='qcoriinfo',
            old_name='qc_time',
            new_name='qc_date',
        ),
    ]
