# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-26 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcorder', '0003_auto_20190625_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcoriinfo',
            name='memorandum',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
    ]
