# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-03 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcorder', '0003_auto_20191226_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcinfo',
            name='error_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '仓库错误'), (2, '其他错误'), (3, '重复导入')], default=0, verbose_name='错误原因'),
        ),
        migrations.AlterField(
            model_name='qcinfo',
            name='result',
            field=models.IntegerField(choices=[(0, '不合格'), (1, '合格')], verbose_name='验货结果'),
        ),
        migrations.AlterField(
            model_name='qcoriinfo',
            name='result',
            field=models.SmallIntegerField(choices=[(0, '不合格'), (1, '合格')], default=0, verbose_name='验货结果'),
        ),
    ]
