# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-26 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcorder', '0006_remove_qcoriinfo_dpu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qcinfo',
            name='dpu',
        ),
    ]
