# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-26 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcorder', '0007_remove_qcinfo_dpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcinfo',
            name='category',
            field=models.IntegerField(choices=[(0, '首检'), (1, '复检'), (2, '召回')], verbose_name='验货类型'),
        ),
        migrations.AlterField(
            model_name='qcoriinfo',
            name='category',
            field=models.IntegerField(choices=[(0, '首检'), (1, '复检'), (2, '召回')], default=0, verbose_name='验货类型'),
        ),
    ]
