# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-27 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcorder', '0008_auto_20190626_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcoriinfo',
            name='qc_order_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='质检单号'),
        ),
    ]
