# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_refund_jdfbp', '0002_auto_20181203_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundresource',
            name='renew_express_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='换新订单'),
        ),
    ]
