# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_refund_jdfbp', '0003_auto_20181203_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundresource',
            name='handling_status',
            field=models.CharField(choices=[('0', '未审核'), ('1', '已审核')], default=0, max_length=30, verbose_name='最终录入状态'),
        ),
    ]
