# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-08 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_refund_jdfbp', '0005_auto_20181204_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundresource',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='售后服务单整体时长'),
        ),
    ]
