# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-08 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_refund_jdfbp', '0007_auto_20181208_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundresource',
            name='bs_handle_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='商家首次处理时间'),
        ),
    ]
