# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_refund_jdfbp', '0008_auto_20181208_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundresource',
            name='buyer_problem_desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='客户问题描述'),
        ),
    ]
