# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_refund_jdfbp', '0009_auto_20181210_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refundresource',
            old_name='handling_status',
            new_name='handlingstatus',
        ),
    ]
