# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-08 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_refund_jdfbp', '0012_refundresource_creator'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='refundresource',
            table='refundresource',
        ),
    ]
