# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-10 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_refund_jdfbp', '0013_auto_20190408_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundresource',
            name='handlingstatus',
            field=models.SmallIntegerField(choices=[(0, '未审核'), (1, '已处理'), (2, '已完结')], default=0, verbose_name='最终录入状态'),
        ),
    ]
