# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-10 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_refund_jdfbp', '0014_auto_20190410_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundresource',
            name='order_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='服务单状态'),
        ),
    ]
