# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-10 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoneu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editionstatement',
            name='version_number',
            field=models.CharField(max_length=55, verbose_name='版本号'),
        ),
    ]
