# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-23 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        ('goods', '0002_auto_20200103_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriStockOutInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('order_id', models.CharField(max_length=30, verbose_name='订单编号')),
                ('ori_order_id', models.CharField(max_length=30, verbose_name='子单原始单号')),
                ('sub_order_id', models.CharField(max_length=30, verbose_name='原始子订单号')),
                ('warehouse', models.CharField(max_length=30, verbose_name='仓库')),
                ('shop', models.CharField(max_length=30, verbose_name='店铺')),
                ('status', models.CharField(max_length=30, verbose_name='出库单状态')),
                ('goods_id', models.CharField(max_length=30, verbose_name='商家编码')),
                ('goods_name', models.CharField(max_length=30, verbose_name='货品简称')),
                ('quantity', models.IntegerField(verbose_name='货品数量')),
                ('price', models.FloatField(verbose_name='货品成交价')),
                ('amount', models.FloatField(verbose_name='货品成交总价')),
                ('nickname', models.CharField(max_length=30, verbose_name='客户网名')),
                ('buyer', models.CharField(max_length=30, verbose_name='收件人')),
                ('area', models.CharField(max_length=30, verbose_name='收货地区')),
                ('address', models.CharField(max_length=30, verbose_name='收货地址')),
                ('smartphone', models.CharField(max_length=30, verbose_name='收件人手机')),
                ('deliver_time', models.CharField(max_length=30, verbose_name='发货时间')),
                ('memorandum', models.CharField(max_length=30, verbose_name='买家留言')),
                ('remark', models.CharField(max_length=30, verbose_name='客服备注')),
                ('order_status', models.IntegerField(choices=[(0, '已取消'), (1, '未处理'), (2, '已完成')], default=1, verbose_name='单据状态')),
                ('mistake_tag', models.SmallIntegerField(choices=[(0, '正常'), (1, '递交重复'), (2, '货品非法'), (3, '仓库非法'), (4, '店铺非法'), (5, '先标记为已对账才能审核'), (6, '工单必须为取消状态'), (7, '先标记为终端清才能审核')], default=0, verbose_name='错误原因')),
            ],
            options={
                'verbose_name': 'WMS-O-原始出库单',
                'verbose_name_plural': 'WMS-O-原始出库单',
                'db_table': 'wms_stk_oristockout',
            },
        ),
        migrations.CreateModel(
            name='StockOutInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('order_id', models.CharField(max_length=30, verbose_name='订单编号')),
                ('ori_order_id', models.CharField(max_length=30, verbose_name='子单原始单号')),
                ('sub_order_id', models.CharField(max_length=30, verbose_name='原始子订单号')),
                ('shop', models.CharField(max_length=30, verbose_name='店铺')),
                ('status', models.CharField(max_length=30, verbose_name='出库单状态')),
                ('goods_id', models.CharField(max_length=30, verbose_name='商家编码')),
                ('quantity', models.IntegerField(verbose_name='货品数量')),
                ('price', models.FloatField(verbose_name='货品成交价')),
                ('amount', models.FloatField(verbose_name='货品成交总价')),
                ('nickname', models.CharField(max_length=30, verbose_name='客户网名')),
                ('buyer', models.CharField(max_length=30, verbose_name='收件人')),
                ('area', models.CharField(max_length=30, verbose_name='收货地区')),
                ('address', models.CharField(max_length=30, verbose_name='收货地址')),
                ('smartphone', models.CharField(max_length=30, verbose_name='收件人手机')),
                ('deliver_time', models.CharField(max_length=30, verbose_name='发货时间')),
                ('memorandum', models.CharField(max_length=30, verbose_name='买家留言')),
                ('remark', models.CharField(max_length=30, verbose_name='客服备注')),
                ('order_status', models.IntegerField(choices=[(0, '已取消'), (1, '未处理'), (2, '已完成')], default=1, verbose_name='单据状态')),
                ('mistake_tag', models.SmallIntegerField(choices=[(0, '正常'), (1, '递交重复'), (2, '货品非法'), (3, '仓库非法'), (4, '店铺非法'), (5, '先标记为已对账才能审核'), (6, '工单必须为取消状态'), (7, '先标记为终端清才能审核')], default=0, verbose_name='错误原因')),
                ('goods_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo', verbose_name='货品简称')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseInfo', verbose_name='仓库')),
            ],
            options={
                'verbose_name': 'WMS-O-原始出库单',
                'verbose_name_plural': 'WMS-O-原始出库单',
                'db_table': 'wms_stk_stockout',
            },
        ),
        migrations.CreateModel(
            name='OriSOUnhandle',
            fields=[
            ],
            options={
                'verbose_name': 'WMS-O-原始出库单未审核',
                'verbose_name_plural': 'WMS-O-原始出库单未审核',
                'proxy': True,
                'indexes': [],
            },
            bases=('stockout.oristockoutinfo',),
        ),
        migrations.CreateModel(
            name='SOUnhandle',
            fields=[
            ],
            options={
                'verbose_name': 'WMS-O-未审核出库单',
                'verbose_name_plural': 'WMS-O-未审核出库单',
                'proxy': True,
                'indexes': [],
            },
            bases=('stockout.stockoutinfo',),
        ),
    ]
