# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-23 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockoutinfo',
            options={'verbose_name': 'WMS-O-出库单', 'verbose_name_plural': 'WMS-O-出库单'},
        ),
    ]
