# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-18 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockout', '0002_auto_20190928_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockoutinfo',
            name='address',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='地址'),
        ),
    ]
