# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-28 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockout', '0003_stockoutinfo_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockoutinfo',
            old_name='status',
            new_name='order_status',
        ),
    ]
