# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-27 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DialogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('name', models.CharField(max_length=30, verbose_name='标签名')),
                ('category', models.SmallIntegerField(choices=[(0, '无法定义'), (1, '售前'), (2, '售后')], default=0, verbose_name='标签类型')),
                ('order_status', models.SmallIntegerField(choices=[(0, '被取消'), (1, '正常')], default=1, verbose_name='单据状态')),
            ],
            options={
                'verbose_name': 'CRM-对话-标签',
                'verbose_name_plural': 'CRM-对话-标签',
                'db_table': 'crm_dialog_tag',
            },
        ),
        migrations.CreateModel(
            name='DOWID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('dialog_id', models.CharField(max_length=30, unique=True, verbose_name='对话ID')),
            ],
            options={
                'verbose_name': 'CRM-官网对话信息-对话ID',
                'verbose_name_plural': 'CRM-官网对话信息-对话ID',
                'db_table': 'crm_diadetail_dowid',
            },
        ),
        migrations.CreateModel(
            name='OriDetailJD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('sayer', models.CharField(db_index=True, max_length=150, verbose_name='讲话者')),
                ('d_status', models.SmallIntegerField(choices=[(0, '客服'), (1, '顾客')], verbose_name='角色')),
                ('time', models.DateTimeField(db_index=True, verbose_name='时间')),
                ('interval', models.IntegerField(verbose_name='对话间隔(秒)')),
                ('content', models.TextField(verbose_name='内容')),
                ('index', models.IntegerField(default=0, verbose_name='对话负面指数')),
                ('category', models.SmallIntegerField(choices=[(0, '常规'), (1, '订单')], default=0, verbose_name='内容类型')),
                ('extract_tag', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], db_index=True, default=0, verbose_name='是否提取订单')),
                ('sensitive_tag', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否过滤')),
                ('order_status', models.SmallIntegerField(choices=[(0, '被取消'), (1, '未过滤'), (2, '未质检')], db_index=True, default=1, verbose_name='单据状态')),
                ('mistake_tag', models.SmallIntegerField(choices=[(0, '正常'), (1, '对话格式错误'), (2, '重复导入')], default=0, verbose_name='错误列表')),
            ],
            options={
                'verbose_name': 'CRM-京东对话信息-查询',
                'verbose_name_plural': 'CRM-京东对话信息-查询',
                'db_table': 'crm_diadetail_orijingdong',
            },
        ),
        migrations.CreateModel(
            name='OriDetailOW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('sayer', models.CharField(db_index=True, max_length=150, verbose_name='讲话者')),
                ('d_status', models.SmallIntegerField(choices=[(0, '客服'), (1, '顾客')], verbose_name='角色')),
                ('time', models.DateTimeField(db_index=True, verbose_name='时间')),
                ('interval', models.IntegerField(verbose_name='对话间隔(秒)')),
                ('content', models.TextField(verbose_name='内容')),
                ('index', models.IntegerField(default=0, verbose_name='对话负面指数')),
                ('category', models.SmallIntegerField(choices=[(0, '常规'), (1, '订单')], default=0, verbose_name='内容类型')),
                ('extract_tag', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], db_index=True, default=0, verbose_name='是否提取订单')),
                ('sensitive_tag', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否过滤')),
                ('order_status', models.SmallIntegerField(choices=[(0, '被取消'), (1, '正常')], db_index=True, default=1, verbose_name='单据状态')),
                ('mistake_tag', models.SmallIntegerField(choices=[(0, '正常'), (1, '对话格式错误'), (2, '重复导入')], default=0, verbose_name='错误列表')),
            ],
            options={
                'verbose_name': 'CRM-官网对话信息-查询',
                'verbose_name_plural': 'CRM-官网对话信息-查询',
                'db_table': 'crm_diadetail_oriofficial',
            },
        ),
        migrations.CreateModel(
            name='OriDetailTB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('sayer', models.CharField(db_index=True, max_length=150, verbose_name='讲话者')),
                ('d_status', models.SmallIntegerField(choices=[(0, '客服'), (1, '顾客')], verbose_name='角色')),
                ('time', models.DateTimeField(db_index=True, verbose_name='时间')),
                ('interval', models.IntegerField(verbose_name='对话间隔(秒)')),
                ('content', models.TextField(verbose_name='内容')),
                ('index', models.IntegerField(default=0, verbose_name='对话负面指数')),
                ('category', models.SmallIntegerField(choices=[(0, '常规'), (1, '订单'), (2, '差价')], default=0, verbose_name='内容类型')),
                ('extract_tag', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], db_index=True, default=0, verbose_name='是否提取订单')),
                ('sensitive_tag', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否过滤')),
                ('order_status', models.SmallIntegerField(choices=[(0, '被取消'), (1, '正常')], db_index=True, default=1, verbose_name='单据状态')),
                ('mistake_tag', models.SmallIntegerField(choices=[(0, '正常'), (1, '对话格式错误'), (2, '重复导入'), (3, '差价货品名称错误'), (4, '差价金额填写错误'), (5, '差价收款人姓名错误'), (6, '差价支付宝名称错误'), (7, '差价订单号错误'), (8, '差价核算公式格式错误'), (9, '差价核算公式计算错误'), (10, '差价核算结果与上报差价不等'), (11, '差价类型只能是1或者3')], default=0, verbose_name='错误列表')),
            ],
            options={
                'verbose_name': 'CRM-淘系对话信息-查询',
                'verbose_name_plural': 'CRM-淘系对话信息-查询',
                'db_table': 'crm_diadetail_oritaobao',
            },
        ),
        migrations.CreateModel(
            name='OriDialogJD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('shop', models.CharField(db_index=True, max_length=60, verbose_name='店铺')),
                ('customer', models.CharField(db_index=True, max_length=150, verbose_name='客户')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('min', models.IntegerField(verbose_name='总人次')),
                ('category', models.SmallIntegerField(choices=[(0, '自动'), (1, '人工')], default=1, verbose_name='对话类型')),
                ('order_status', models.SmallIntegerField(choices=[(0, '被取消'), (1, '正常')], db_index=True, default=1, verbose_name='单据状态')),
            ],
            options={
                'verbose_name': 'CRM-京东对话客户-查询',
                'verbose_name_plural': 'CRM-京东对话客户-查询',
                'db_table': 'crm_dialog_orijingdong',
            },
        ),
        migrations.CreateModel(
            name='OriDialogOW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('shop', models.CharField(db_index=True, max_length=60, verbose_name='店铺')),
                ('customer', models.CharField(db_index=True, max_length=150, verbose_name='客户')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('min', models.IntegerField(verbose_name='总人次')),
                ('order_status', models.SmallIntegerField(choices=[(0, '被取消'), (1, '正常')], db_index=True, default=1, verbose_name='单据状态')),
            ],
            options={
                'verbose_name': 'CRM-官网对话客户-查询',
                'verbose_name_plural': 'CRM-官网对话客户-查询',
                'db_table': 'crm_dialog_oriofficial',
            },
        ),
        migrations.CreateModel(
            name='OriDialogTB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('shop', models.CharField(db_index=True, max_length=60, verbose_name='店铺')),
                ('customer', models.CharField(db_index=True, max_length=150, verbose_name='客户')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('min', models.IntegerField(verbose_name='总人次')),
                ('order_status', models.SmallIntegerField(choices=[(0, '被取消'), (1, '正常')], db_index=True, default=1, verbose_name='单据状态')),
            ],
            options={
                'verbose_name': 'CRM-淘系对话客户-查询',
                'verbose_name_plural': 'CRM-淘系对话客户-查询',
                'db_table': 'crm_dialog_oritaobao',
            },
        ),
        migrations.CreateModel(
            name='SensitiveInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('words', models.CharField(max_length=10, unique=True, verbose_name='敏感字')),
                ('index', models.IntegerField(verbose_name='指数')),
                ('category', models.SmallIntegerField(choices=[(0, '负向'), (1, '正面')], default=0, verbose_name='敏感字类型')),
                ('order_status', models.SmallIntegerField(choices=[(0, '被取消'), (1, '正常')], default=1, verbose_name='单据状态')),
            ],
            options={
                'verbose_name': 'CRM-对话-敏感字',
                'verbose_name_plural': 'CRM-对话-敏感字',
                'db_table': 'crm_dialog_sensitive',
            },
        ),
        migrations.CreateModel(
            name='ServicerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('name', models.CharField(max_length=150, verbose_name='昵称')),
                ('platform', models.CharField(max_length=60, verbose_name='平台')),
                ('category', models.SmallIntegerField(choices=[(0, '机器人'), (1, '人工')], default=1, verbose_name='客服类型')),
            ],
            options={
                'verbose_name': 'CRM-对话-客服网名',
                'verbose_name_plural': 'CRM-对话-客服网名',
                'db_table': 'crm_dialog_servicer',
            },
        ),
    ]
