# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-27 10:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dialog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerinfo',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='人名'),
        ),
        migrations.AddField(
            model_name='oridialogtb',
            name='dialog_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dialog.DialogTag', verbose_name='对话标签'),
        ),
        migrations.AddField(
            model_name='oridialogow',
            name='dialog_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dialog.DialogTag', verbose_name='对话标签'),
        ),
        migrations.AddField(
            model_name='oridialogjd',
            name='dialog_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dialog.DialogTag', verbose_name='对话标签'),
        ),
        migrations.AddField(
            model_name='oridetailtb',
            name='dialog_tb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialog.OriDialogTB', verbose_name='对话'),
        ),
        migrations.AddField(
            model_name='oridetailow',
            name='dialog_ow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialog.OriDialogOW', verbose_name='对话'),
        ),
        migrations.AddField(
            model_name='oridetailjd',
            name='dialog_jd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialog.OriDialogJD', verbose_name='对话'),
        ),
        migrations.CreateModel(
            name='CheckODJD',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-京东对话信息-未过滤',
                'verbose_name_plural': 'CRM-京东对话信息-未过滤',
                'proxy': True,
                'indexes': [],
            },
            bases=('dialog.oridetailjd',),
        ),
        migrations.CreateModel(
            name='CheckODOW',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-官网对话信息-未过滤',
                'verbose_name_plural': 'CRM-官网对话信息-未过滤',
                'proxy': True,
                'indexes': [],
            },
            bases=('dialog.oridetailow',),
        ),
        migrations.CreateModel(
            name='CheckODTB',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-淘宝对话信息-未过滤',
                'verbose_name_plural': 'CRM-淘宝对话信息-未过滤',
                'proxy': True,
                'indexes': [],
            },
            bases=('dialog.oridetailtb',),
        ),
        migrations.CreateModel(
            name='ExceptionODJD',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-京东对话信息-敏感对话',
                'verbose_name_plural': 'CRM-京东对话信息-敏感对话',
                'proxy': True,
                'indexes': [],
            },
            bases=('dialog.oridetailjd',),
        ),
        migrations.CreateModel(
            name='ExceptionODOW',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-官网对话信息-敏感对话',
                'verbose_name_plural': 'CRM-官网对话信息-敏感对话',
                'proxy': True,
                'indexes': [],
            },
            bases=('dialog.oridetailow',),
        ),
        migrations.CreateModel(
            name='ExceptionODTB',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-淘宝对话信息-敏感对话',
                'verbose_name_plural': 'CRM-淘宝对话信息-敏感对话',
                'proxy': True,
                'indexes': [],
            },
            bases=('dialog.oridetailtb',),
        ),
        migrations.CreateModel(
            name='ExtractODJD',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-京东对话信息-未提取',
                'verbose_name_plural': 'CRM-京东对话信息-未提取',
                'proxy': True,
                'indexes': [],
            },
            bases=('dialog.oridetailjd',),
        ),
        migrations.CreateModel(
            name='ExtractODOW',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-官网对话信息-未提取',
                'verbose_name_plural': 'CRM-官网对话信息-未提取',
                'proxy': True,
                'indexes': [],
            },
            bases=('dialog.oridetailow',),
        ),
        migrations.CreateModel(
            name='ExtractODTB',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-淘宝对话信息-未提取',
                'verbose_name_plural': 'CRM-淘宝对话信息-未提取',
                'proxy': True,
                'indexes': [],
            },
            bases=('dialog.oridetailtb',),
        ),
        migrations.CreateModel(
            name='MyExtractODOW',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-官网对话信息-未提取个人',
                'verbose_name_plural': 'CRM-官网对话信息-未提取个人',
                'proxy': True,
                'indexes': [],
            },
            bases=('dialog.oridetailow',),
        ),
        migrations.CreateModel(
            name='MyExtractODTB',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-淘宝对话信息-未提取个人',
                'verbose_name_plural': 'CRM-淘宝对话信息-未提取个人',
                'proxy': True,
                'indexes': [],
            },
            bases=('dialog.oridetailtb',),
        ),
        migrations.AlterUniqueTogether(
            name='oridialogtb',
            unique_together=set([('shop', 'customer')]),
        ),
        migrations.AlterUniqueTogether(
            name='oridialogow',
            unique_together=set([('shop', 'customer')]),
        ),
        migrations.AlterUniqueTogether(
            name='oridialogjd',
            unique_together=set([('shop', 'customer')]),
        ),
    ]
