# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-05-09 15:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dialog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('name', models.CharField(max_length=150, verbose_name='昵称')),
                ('platform', models.CharField(max_length=60, verbose_name='平台')),
                ('category', models.SmallIntegerField(choices=[(0, '自动'), (1, '人工')], default=1, verbose_name='客服类型')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='人名')),
            ],
            options={
                'verbose_name': 'CRM-对话-客服网名',
                'verbose_name_plural': 'CRM-对话-客服网名',
                'db_table': 'crm_dialog_servicer',
            },
        ),
        migrations.AddField(
            model_name='oridialogjd',
            name='category',
            field=models.SmallIntegerField(choices=[(0, '自动'), (1, '人工')], default=1, verbose_name='对话类型'),
        ),
    ]
