# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-08 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0002_auto_20201127_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oridetailjd',
            old_name='index',
            new_name='index_num',
        ),
        migrations.RenameField(
            model_name='oridetailow',
            old_name='index',
            new_name='index_num',
        ),
        migrations.RenameField(
            model_name='oridetailtb',
            old_name='index',
            new_name='index_num',
        ),
        migrations.RenameField(
            model_name='sensitiveinfo',
            old_name='index',
            new_name='index_num',
        ),
    ]
