# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-05-09 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0002_auto_20200509_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerinfo',
            name='category',
            field=models.SmallIntegerField(choices=[(0, '机器人'), (1, '人工')], default=1, verbose_name='客服类型'),
        ),
    ]
