# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-05-13 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0003_auto_20200509_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitiveInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('words', models.CharField(max_length=10, verbose_name='敏感字')),
                ('index', models.IntegerField(verbose_name='指数')),
                ('category', models.SmallIntegerField(choices=[(0, '负向'), (1, '正面')], default=0, verbose_name='敏感字类型')),
                ('order_status', models.SmallIntegerField(choices=[(0, '被取消'), (1, '正常')], default=1, verbose_name='单据状态')),
            ],
            options={
                'verbose_name': 'CRM-对话-标签',
                'verbose_name_plural': 'CRM-对话-标签',
                'db_table': 'crm_dialog_sensitive',
            },
        ),
    ]
