# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-05-14 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0004_sensitiveinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='oridetailjd',
            name='extract_tag',
            field=models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否提取订单'),
        ),
        migrations.AddField(
            model_name='oridetailjd',
            name='index',
            field=models.IntegerField(default=0, verbose_name='对话负面指数'),
        ),
        migrations.AddField(
            model_name='oridetailjd',
            name='sensitive_tag',
            field=models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否过滤'),
        ),
        migrations.AlterField(
            model_name='oridetailjd',
            name='order_status',
            field=models.SmallIntegerField(choices=[(0, '被取消'), (1, '未过滤'), (2, '未质检')], default=1, verbose_name='单据状态'),
        ),
    ]
