# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-05-14 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0005_auto_20200514_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensitiveinfo',
            options={'verbose_name': 'CRM-对话-敏感字', 'verbose_name_plural': 'CRM-对话-敏感字'},
        ),
    ]
