# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-05-14 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0006_auto_20200514_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckODJD',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-京东对话信息-未过滤',
                'verbose_name_plural': 'CRM-京东对话信息-未过滤',
                'proxy': True,
                'indexes': [],
            },
            bases=('dialog.oridetailjd',),
        ),
        migrations.CreateModel(
            name='ExtractODJD',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-京东对话信息-未提取',
                'verbose_name_plural': 'CRM-京东对话信息-未提取',
                'proxy': True,
                'indexes': [],
            },
            bases=('dialog.oridetailjd',),
        ),
        migrations.AlterField(
            model_name='sensitiveinfo',
            name='words',
            field=models.CharField(max_length=10, unique=True, verbose_name='敏感字'),
        ),
    ]
