# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-05-18 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0007_auto_20200514_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionODJD',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-京东对话信息-敏感对话',
                'verbose_name_plural': 'CRM-京东对话信息-敏感对话',
                'proxy': True,
                'indexes': [],
            },
            bases=('dialog.oridetailjd',),
        ),
        migrations.AddField(
            model_name='oridetailjd',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '对话格式错误')], default=1, verbose_name='错误列表'),
        ),
    ]
