# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-05-21 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0009_auto_20200518_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckODTB',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-淘宝对话信息-未过滤',
                'verbose_name_plural': 'CRM-淘宝对话信息-未过滤',
                'proxy': True,
                'indexes': [],
            },
            bases=('dialog.oridetailtb',),
        ),
        migrations.CreateModel(
            name='ExceptionODTB',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-淘宝对话信息-敏感对话',
                'verbose_name_plural': 'CRM-淘宝对话信息-敏感对话',
                'proxy': True,
                'indexes': [],
            },
            bases=('dialog.oridetailtb',),
        ),
        migrations.CreateModel(
            name='ExtractODTB',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-淘宝对话信息-未提取',
                'verbose_name_plural': 'CRM-淘宝对话信息-未提取',
                'proxy': True,
                'indexes': [],
            },
            bases=('dialog.oridetailtb',),
        ),
    ]
