# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-05-21 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0010_checkodtb_exceptionodtb_extractodtb'),
    ]

    operations = [
        migrations.AddField(
            model_name='oridetailtb',
            name='extract_tag',
            field=models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否提取订单'),
        ),
        migrations.AddField(
            model_name='oridetailtb',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '对话格式错误')], default=0, verbose_name='错误列表'),
        ),
        migrations.AddField(
            model_name='oridetailtb',
            name='sensitive_tag',
            field=models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否过滤'),
        ),
    ]
