# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-05-21 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0011_auto_20200521_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='oridetailtb',
            name='index',
            field=models.IntegerField(default=0, verbose_name='对话负面指数'),
        ),
    ]
