# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-06-11 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0013_oridetailtb_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='oridetailjd',
            name='category',
            field=models.SmallIntegerField(choices=[(0, '常规'), (1, '订单')], default=0, verbose_name='内容类型'),
        ),
    ]
