# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-06-16 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0014_oridetailjd_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oridetailtb',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '对话格式错误'), (2, '重复导入')], default=0, verbose_name='错误列表'),
        ),
    ]
