# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-07-07 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0015_auto_20200616_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyExtractODTB',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-淘宝对话信息-未提取个人',
                'verbose_name_plural': 'CRM-淘宝对话信息-未提取个人',
                'proxy': True,
                'indexes': [],
            },
            bases=('dialog.oridetailtb',),
        ),
    ]
