# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-07-15 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0016_myextractodtb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oridetailjd',
            old_name='status',
            new_name='d_status',
        ),
        migrations.RenameField(
            model_name='oridetailtb',
            old_name='status',
            new_name='d_status',
        ),
        migrations.AlterField(
            model_name='oridetailjd',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '对话格式错误'), (2, '重复导入')], default=0, verbose_name='错误列表'),
        ),
    ]
