# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-07-17 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0017_auto_20200715_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oridialogjd',
            name='customer',
            field=models.CharField(db_index=True, max_length=150, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='oridialogtb',
            name='customer',
            field=models.CharField(db_index=True, max_length=150, verbose_name='客户'),
        ),
        migrations.AlterUniqueTogether(
            name='oridialogjd',
            unique_together=set([('shop', 'customer')]),
        ),
        migrations.AlterUniqueTogether(
            name='oridialogtb',
            unique_together=set([('shop', 'customer')]),
        ),
    ]
