# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-08-06 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0018_auto_20200717_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriDetailOW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('sayer', models.CharField(db_index=True, max_length=150, verbose_name='讲话者')),
                ('d_status', models.SmallIntegerField(choices=[(0, '客服'), (1, '顾客')], verbose_name='角色')),
                ('time', models.DateTimeField(db_index=True, verbose_name='时间')),
                ('interval', models.IntegerField(verbose_name='对话间隔(秒)')),
                ('content', models.TextField(verbose_name='内容')),
                ('index', models.IntegerField(default=0, verbose_name='对话负面指数')),
                ('category', models.SmallIntegerField(choices=[(0, '常规'), (1, '订单')], default=0, verbose_name='内容类型')),
                ('extract_tag', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否提取订单')),
                ('sensitive_tag', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否过滤')),
                ('order_status', models.SmallIntegerField(choices=[(0, '被取消'), (1, '正常')], default=1, verbose_name='单据状态')),
                ('mistake_tag', models.SmallIntegerField(choices=[(0, '正常'), (1, '对话格式错误'), (2, '重复导入')], default=0, verbose_name='错误列表')),
            ],
            options={
                'verbose_name': 'CRM-官网对话信息-查询',
                'verbose_name_plural': 'CRM-官网对话信息-查询',
                'db_table': 'crm_diadetail_oriofficial',
            },
        ),
        migrations.CreateModel(
            name='OriDialogOW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('shop', models.CharField(db_index=True, max_length=60, verbose_name='店铺')),
                ('customer', models.CharField(db_index=True, max_length=150, verbose_name='客户')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('min', models.IntegerField(verbose_name='总人次')),
                ('order_status', models.SmallIntegerField(choices=[(0, '被取消'), (1, '正常')], default=1, verbose_name='单据状态')),
                ('dialog_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dialog.DialogTag', verbose_name='对话标签')),
            ],
            options={
                'verbose_name': 'CRM-官网对话客户-查询',
                'verbose_name_plural': 'CRM-官网对话客户-查询',
                'db_table': 'crm_dialog_oriofficial',
            },
        ),
        migrations.AddField(
            model_name='oridetailow',
            name='dialog_ow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialog.OriDialogOW', verbose_name='对话'),
        ),
        migrations.CreateModel(
            name='CheckODOW',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-官网对话信息-未过滤',
                'verbose_name_plural': 'CRM-官网对话信息-未过滤',
                'proxy': True,
                'indexes': [],
            },
            bases=('dialog.oridetailow',),
        ),
        migrations.CreateModel(
            name='ExceptionODOW',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-官网对话信息-敏感对话',
                'verbose_name_plural': 'CRM-官网对话信息-敏感对话',
                'proxy': True,
                'indexes': [],
            },
            bases=('dialog.oridetailow',),
        ),
        migrations.CreateModel(
            name='ExtractODOW',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-官网对话信息-未提取',
                'verbose_name_plural': 'CRM-官网对话信息-未提取',
                'proxy': True,
                'indexes': [],
            },
            bases=('dialog.oridetailow',),
        ),
        migrations.CreateModel(
            name='MyExtractODOW',
            fields=[
            ],
            options={
                'verbose_name': 'CRM-官网对话信息-未提取个人',
                'verbose_name_plural': 'CRM-官网对话信息-未提取个人',
                'proxy': True,
                'indexes': [],
            },
            bases=('dialog.oridetailow',),
        ),
        migrations.AlterUniqueTogether(
            name='oridialogow',
            unique_together=set([('shop', 'customer')]),
        ),
    ]
