# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-08-27 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0019_auto_20200806_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOWID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(default='system', max_length=30, verbose_name='创建者')),
                ('dialog_id', models.CharField(max_length=30, unique=True, verbose_name='对话ID')),
            ],
            options={
                'verbose_name': 'CRM-官网对话信息-对话ID',
                'verbose_name_plural': 'CRM-官网对话信息-对话ID',
                'db_table': 'crm_diadetail_dowid',
            },
        ),
    ]
