# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-10-15 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0022_auto_20201015_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oridialogjd',
            name='order_status',
            field=models.SmallIntegerField(choices=[(0, '被取消'), (1, '正常')], db_index=True, default=1, verbose_name='单据状态'),
        ),
        migrations.AlterField(
            model_name='oridialogow',
            name='order_status',
            field=models.SmallIntegerField(choices=[(0, '被取消'), (1, '正常')], db_index=True, default=1, verbose_name='单据状态'),
        ),
        migrations.AlterField(
            model_name='oridialogtb',
            name='order_status',
            field=models.SmallIntegerField(choices=[(0, '被取消'), (1, '正常')], db_index=True, default=1, verbose_name='单据状态'),
        ),
    ]
